using DuetCanMessage.SourceGenerators.Model;

namespace DuetCanMessage.SourceGenerators.Emit;

/// <summary>
/// Emits the C++ generic message parameter tables: a drop-in replacement for CANlib's
/// <c>CanMessageGenericTables.h</c>.
/// </summary>
/// <remarks>
/// CANlib writes each entry through a macro (<c>UINT16_PARAM('P')</c>) so that the type and the element
/// size cannot get out of step by hand. Nothing is written by hand here, so the macros are expanded at
/// generation time and the resulting aggregate initialisers say outright what each entry is. The
/// <c>ParamDescriptor</c> type itself still comes from CANlib's <c>CanMessageGenericTableFormat.h</c>,
/// because it is the type both ends of the link agree on.
/// </remarks>
public sealed class CppTablesEmitter(CanSchema schema)
{
    public string Emit()
    {
        CodeWriter writer = new();
        writer.Line("/*");
        writer.Line(" * CanMessageGenericTables.h");
        writer.Line(" *");
        writer.Line(" * <auto-generated>");
        writer.Line(" *     Generated by src/DuetCanMessage.SourceGenerators from Schema/can-messages.json.");
        writer.Line(" *     Do not edit this file directly: edit the schema and re-run the generator, otherwise");
        writer.Line(" *     the C++ and C# parameter tables will drift apart.");
        writer.Line(" * </auto-generated>");
        writer.Line(" */");
        writer.Line();
        writer.Line($"#ifndef {schema.CppTablesHeaderGuard}");
        writer.Line($"#define {schema.CppTablesHeaderGuard}");
        writer.Line();
        writer.Line("#include \"CanMessageGenericTableFormat.h\"");
        writer.Line();
        writer.Line("// Parameter tables for various messages that use the generic format.");
        writer.Line("// For backwards compatibility, any new parameters added to a table must be added at the end of that table.");
        writer.Line("// Maximum length of data is 60 bytes.");
        writer.Line();

        foreach (GenericTableDef table in schema.GenericTables)
        {
            writer.Doc(table.Doc, "// ");
            writer.Line($"constexpr ParamDescriptor {table.Name}[] =");
            using (writer.Block("{", "};"))
            {
                // Line the trailing comments up with each other, as CANlib's tables do
                int width = table.Params.Count == 0 ? 0 : table.Params.Max(p => Entry(p).Length) + 1;
                foreach (GenericParamDef param in table.Params)
                {
                    string entry = Entry(param) + ",";
                    writer.Line(param.Doc is null ? entry : $"{entry.PadRight(width)}  // {param.Doc}");
                }
                writer.Line("{ 0, ParamDescriptor::none, 0 }");
            }
            writer.Line();
        }

        writer.Line($"#endif /* {schema.CppTablesHeaderGuard} */");
        return writer.ToString();
    }

    /// <summary>One table entry, i.e. what CANlib's per-type macro would have expanded to.</summary>
    private static string Entry(GenericParamDef param) =>
        $"{{ '{param.Letter}', ParamDescriptor::{param.Type.CppEnumerator}, {param.MaxLength} }}";
}
