using DuetCanMessage.SourceGenerators.Model;

namespace DuetCanMessage.SourceGenerators.Emit;

/// <summary>
/// Emits the C# side of the enums CANlib declares.
/// </summary>
/// <remarks>
/// These carry values that travel on the wire, so they have to agree with CANlib even more surely than the
/// layouts do: a wrong value is not misread, it means something else. CanMessageType used to be transcribed
/// by hand next to a TODO asking for exactly this.
/// <para>
/// Retired ids are emitted as comments rather than dropped. The comment is the record that the number is
/// spent — reusing one would have an expansion board on older firmware act on a message that now means
/// something else.
/// </para>
/// </remarks>
public sealed class CSharpEnumEmitter(CanSchema schema)
{
    public string Emit(MessageTypeEnumDef definition)
    {
        CodeWriter writer = new("    ");
        writer.Line("// <auto-generated>");
        writer.Line("//     Generated by src/DuetCanMessage.SourceGenerators from Schema/can-messages.json.");
        writer.Line("//     Do not edit this file directly: edit the schema and re-run the generator, otherwise");
        writer.Line($"//     these values will drift away from CANlib's {definition.CppHeader}, which nothing else would catch.");
        writer.Line("// </auto-generated>");
        writer.Line();
        writer.Line($"namespace {schema.CSharpSharedNamespace};");
        writer.Line();

        writer.XmlDoc(definition.Doc);
        using (writer.Block($"public enum {definition.CSharpName} : {definition.UnderlyingType}", "}"))
        {
            writer.Outdent();
            writer.Line("{");
            writer.Indent();

            bool needsBlank = false;
            foreach (MessageTypeDef entry in definition.Values)
            {
                if (entry.Section is not null)
                {
                    writer.Line();
                    writer.Line($"// {entry.Section}");
                    needsBlank = false;
                    continue;
                }
                if (!entry.IsGenerated(Language.CSharp))
                {
                    continue;
                }

                string name = Naming.MessageTypeMember(entry.Name);
                if (entry.Retired)
                {
                    // Kept as a comment so the id is visibly spent rather than free to reuse
                    writer.Line($"// {name} = {entry.Value},{Trailing(entry.Doc)}");
                    needsBlank = false;
                    continue;
                }

                if (entry.Doc is not null)
                {
                    if (needsBlank)
                    {
                        writer.Line();
                    }
                    writer.XmlDoc(entry.Doc);
                }
                string value = entry.IsAlias ? Naming.MessageTypeMember(entry.Value) : entry.Value;
                writer.Line($"{name} = {value},");
                needsBlank = entry.Doc is not null;
            }
        }
        EmitPriorities(writer, definition);
        return writer.ToString();
    }

    /// <summary>
    /// Emit the order the values are dealt with in, for an enum that declares one
    /// </summary>
    /// <remarks>
    /// The priority is emitted beside the enum rather than being read from the value, because the values
    /// are a compatibility constraint and the order is a design choice. Keeping the two in one declaration
    /// is what stops them drifting: a value added to the schema without a priority fails here rather than
    /// silently sorting last
    /// </remarks>
    private static void EmitPriorities(CodeWriter writer, MessageTypeEnumDef definition)
    {
        List<MessageTypeDef> ordered = [.. definition.Values
            .Where(entry => entry.Section is null && !entry.Retired && !entry.IsAlias && entry.IsGenerated(Language.CSharp))
            .Where(entry => entry.Priority is not null)
            .OrderBy(entry => entry.Priority!.Value)];
        if (ordered.Count == 0)
        {
            return;
        }

        writer.Line();
        writer.XmlDoc($"The order {definition.CSharpName} values are dealt with in, lowest first");
        using (writer.Block($"public static class {definition.CSharpName}Priority", "}"))
        {
            writer.Outdent();
            writer.Line("{");
            writer.Indent();

            writer.XmlDoc("Get the priority of an event type, lowest first");
            writer.Line($"public static int Of({definition.CSharpName} value) => value switch");
            writer.Line("{");
            writer.Indent();
            foreach (MessageTypeDef entry in ordered)
            {
                writer.Line($"{definition.CSharpName}.{Naming.MessageTypeMember(entry.Name)} => {entry.Priority},");
            }
            writer.Line("_ => int.MaxValue");
            writer.Outdent();
            writer.Line("};");
        }
    }

    private static string Trailing(string? doc) => doc is null ? "" : $" // {doc}";

    /// <summary>
    /// Emit a group of related constants, such as the CAN addresses, as a static class.
    /// </summary>
    public string Emit(ConstantGroupDef group)
    {
        CodeWriter writer = new("    ");
        writer.Line("// <auto-generated>");
        writer.Line("//     Generated by src/DuetCanMessage.SourceGenerators from Schema/can-messages.json.");
        writer.Line("//     Do not edit this file directly: edit the schema and re-run the generator, otherwise");
        writer.Line($"//     these values will drift away from CANlib's {group.CppHeader}, which nothing else would catch.");
        writer.Line("// </auto-generated>");
        writer.Line();
        writer.Line($"namespace {schema.CSharpSharedNamespace};");
        writer.Line();

        writer.XmlDoc(group.Doc);
        using (writer.Block($"public static class {group.Name}", "}"))
        {
            writer.Outdent();
            writer.Line("{");
            writer.Indent();

            bool needsBlank = false;
            foreach (ConstantDef constant in group.Values)
            {
                if (needsBlank)
                {
                    writer.Line();
                }
                needsBlank = true;
                writer.XmlDoc(constant.Doc);
                writer.Line($"public const {Types.CSharp(schema, constant.Type)} {constant.Name} = {Value(constant.Value)};");
            }
        }
        return writer.ToString();
    }

    /// <summary>Render a constant's value, which the schema keeps in CANlib's own spelling.</summary>
    private static string Value(string value) =>
        value.Replace("ul", "u", StringComparison.OrdinalIgnoreCase).Replace("'", "");
}
