using DuetCanMessage.SourceGenerators.Model;

namespace DuetCanMessage.SourceGenerators.Emit;

/// <summary>
/// Emits the C# side of the generic message parameter tables.
/// </summary>
/// <remarks>
/// The table is the contract between the two ends of the link: the sender packs the parameters it is
/// sending in table order and sets the matching bit of the message's paramMap, and the receiver walks the
/// same table to work out where each value is. So the C# tables have to agree with CANlib's entry for
/// entry, which is what the generated conformance fixture checks.
/// </remarks>
public sealed class CSharpTablesEmitter(CanSchema schema)
{
    public string Emit()
    {
        CodeWriter writer = new("    ");
        writer.Line("// <auto-generated>");
        writer.Line("//     Generated by src/DuetCanMessage.SourceGenerators from Schema/can-messages.json.");
        writer.Line("//     Do not edit this file directly: edit the schema and re-run the generator, otherwise");
        writer.Line("//     the C# and C++ parameter tables will drift apart.");
        writer.Line("// </auto-generated>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("using System;");
        writer.Line("using System.Collections.Immutable;");
        foreach (string u in schema.CSharpUsings)
        {
            writer.Line($"using {u};");
        }
        writer.Line();
        writer.Line($"namespace {schema.CSharpNamespace};");
        writer.Line();

        EmitParamType(writer);
        EmitParamDescriptor(writer);
        EmitTables(writer);
        return writer.ToString();
    }

    /// <summary>
    /// Emit one message type per table, giving each parameter a property of the right type. The letter-keyed
    /// <c>CanGenericWriter</c> underneath can only report a wrong letter or type by throwing at run time;
    /// going through the message's own properties moves both to compile time.
    /// </summary>
    public string EmitMessages()
    {
        CodeWriter writer = new("    ");
        writer.Line("// <auto-generated>");
        writer.Line("//     Generated by src/DuetCanMessage.SourceGenerators from Schema/can-messages.json.");
        writer.Line("//     Do not edit this file directly: edit the schema and re-run the generator.");
        writer.Line("// </auto-generated>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("using System;");
        writer.Line("using System.Collections.Immutable;");
        writer.Line("using System.Runtime.InteropServices;");
        writer.Line("using DuetAPI.Commands;");
        foreach (string u in schema.CSharpUsings)
        {
            writer.Line($"using {u};");
        }
        writer.Line();
        writer.Line($"namespace {schema.CSharpNamespace};");
        writer.Line();

        foreach (GenericTableDef table in schema.GenericTables.Where(t => t.IsGenerated(Language.CSharp)))
        {
            EmitMessage(writer, table);
        }
        return writer.ToString();
    }

    /// <summary>
    /// Emit the message type for a table: a <c>CanMessageGeneric</c> that knows which message type it is
    /// sent under and which parameters it can carry, so that it is built and sent like any other message
    /// rather than through a builder of its own.
    /// </summary>
    /// <remarks>
    /// It wraps <c>CanMessageGeneric</c> in a single field at offset 0 rather than restating its fields, so
    /// the wire format is inherited and cannot drift — these are the same 64 bytes the expansion board
    /// already reads, only the C# type differs. Staying a struct is what keeps it an <c>ICanMessage</c>: the
    /// send path serializes the value itself, exactly as it does for the messages CANlib defines with a
    /// struct of their own, so a generic message is used no differently from any other.
    /// </remarks>
    private void EmitMessage(CodeWriter writer, GenericTableDef table)
    {
        string name = MessageName(table);
        string doc = table.Doc is null ? $"The {table.BaseName} generic message." : CodeWriter.Escape(table.Doc);
        string identity = $"Sent as <see cref=\"CanMessageType.{Naming.MessageTypeMember(table.MessageType!)}\" />.";
        writer.XmlDocRaw($"""
            {doc}

            {identity}
            Carries a <see cref="CanMessageGeneric" /> body: the parameters of
            <see cref="CanGenericTables.{table.Name}" /> that are being sent, packed in table order, plus a
            bitmap saying which those are.

            Every parameter is optional, so each is a nullable property: it reads back null when the message
            is not carrying that parameter, and assigning null takes it back out. They may be set in any
            order, and taken from a G-code command with <see cref="FromCode" />.
            """);
        // Deriving the layout from the wrapped message rather than restating it is what keeps this type from
        // ever disagreeing with the format the expansion board reads
        writer.Line("[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 64)]");
        using (writer.Block($"public struct {name} : ICanGenericMessage<{name}>", "}"))
        {
            writer.Outdent();
            writer.Line("{");
            writer.Indent();

            writer.XmlDocRaw("The generic message body, in the format the expansion board reads");
            writer.Line("[FieldOffset(0)] public CanMessageGeneric Generic;");
            writer.Line();

            writer.Line("/// <inheritdoc cref=\"ICanMessage{TSelf}.MessageType\" />");
            writer.Line($"public static CanMessageType MessageType => CanMessageType.{Naming.MessageTypeMember(table.MessageType!)};");
            writer.Line();

            writer.Line("/// <inheritdoc cref=\"ICanGenericMessage{TSelf}.ParamTable\" />");
            writer.Line($"public static ImmutableArray<CanParamDescriptor> ParamTable => CanGenericTables.{table.Name};");
            writer.Line();

            // Without this the interface default would report sizeof (64) and every message would go out
            // padded to the full data area
            writer.XmlDocRaw("""
                Number of payload bytes this message occupies: the parameters actually present, plus the
                request ID and parameter map.

                The parameter map and the table are enough to work this out, because each present parameter's
                size follows from its table entry and, for the variable-length ones, from the data itself.
                """);
            writer.Line("public readonly uint GetActualDataLength() => CanGenericLayout.ActualDataLength(Generic.Data, Generic.ParamMap, ParamTable);");
            writer.Line();

            writer.Line("/// <inheritdoc cref=\"ICanGenericMessage{TSelf}.FromCode\" />");
            writer.Line("public void FromCode(Code code) => CanGenericWriter.FromCode(ref Generic, ParamTable, code);");
            writer.Line();

            writer.Line("/// <inheritdoc cref=\"ICanGenericMessage{TSelf}.Clear\" />");
            writer.Line("public void Clear() => Generic = default;");

            foreach (GenericParamDef param in table.Params)
            {
                EmitParam(writer, param);
            }
        }
        writer.Line();
    }

    /// <summary>The name of the generated message type for a table.</summary>
    private static string MessageName(GenericTableDef table) => $"CanMessage{table.BaseName}";

    /// <summary>Emit one parameter as a nullable property over the table entry it stands for.</summary>
    private static void EmitParam(CodeWriter writer, GenericParamDef param)
    {
        writer.Line();
        string summary = param.Doc is null
            ? $"The '{param.Letter}' parameter, or null if the message does not carry it."
            : $"The '{param.Letter}' parameter, or null if the message does not carry it: {CodeWriter.Escape(param.Doc)}";
        writer.XmlDocRaw(summary);
        if (!param.CanComeFromGCode)
        {
            // The property keeps the lowercase name on purpose: the letter is the parameter's identity on the
            // wire, and an uppercase alias would suggest it maps to that G-code letter, which is the very
            // thing CANlib moved it out of A..Z to prevent
            writer.Line("/// <remarks>Outside A..Z, so a G-code command can never supply this parameter; the caller has to.</remarks>");
        }
        using (writer.Block($"public {PropertyType(param)} {param.Letter}", "}"))
        {
            writer.Outdent();
            writer.Line("{");
            writer.Indent();
            writer.Line($"readonly get => {Read(param)};");
            writer.Line($"set => {Write(param)};");
        }
    }

    /// <summary>The type of a parameter's property, i.e. the narrowest C# type that the entry accepts.</summary>
    private static string PropertyType(GenericParamDef param) => param.Type.Id switch
    {
        "uint64" => "ulong?",
        "uint32" => "uint?",
        "uint16" or "pwmFreq" => "ushort?",
        "uint8" or "localDriver" => "byte?",
        "int32" => "int?",
        "int16" => "short?",
        "int8" => "sbyte?",
        "float" or "float16" => "float?",
        "char" => "char?",
        "string" or "reducedString" => "string?",
        "uint8Array" or "uint16Array" or "uint32Array" => "uint[]?",
        "floatArray" => "float[]?",
        _ => throw new InvalidOperationException($"no C# property type for parameter type '{param.Type.Id}'")
    };

    /// <summary>
    /// The call a property getter makes into the letter-keyed parser. The parser answers in the widest type
    /// of each family, so an entry narrower than that casts the result back down to the width the table
    /// declares.
    /// </summary>
    private static string Read(GenericParamDef param)
    {
        string getter = param.Type.Id switch
        {
            "uint64" => "GetUInt64",
            "uint32" or "uint16" or "pwmFreq" or "uint8" or "localDriver" => "GetUInt",
            "int32" or "int16" or "int8" => "GetInt",
            "float" or "float16" => "GetFloat",
            "char" => "GetChar",
            "string" or "reducedString" => "GetString",
            "uint8Array" or "uint16Array" or "uint32Array" => "GetUIntArray",
            "floatArray" => "GetFloatArray",
            _ => throw new InvalidOperationException($"no parser call for parameter type '{param.Type.Id}'")
        };
        string read = $"CanGenericParser.{getter}(Generic, ParamTable, '{param.Letter}')";
        return param.Type.Id switch
        {
            "uint16" or "pwmFreq" or "uint8" or "localDriver" or "int16" or "int8" => $"({PropertyType(param)}){read}",
            _ => read
        };
    }

    /// <summary>The call a property setter makes into the letter-keyed writer.</summary>
    private static string Write(GenericParamDef param)
    {
        string setter = param.Type.Id switch
        {
            "uint64" => "SetUInt64",
            "uint32" or "uint16" or "pwmFreq" or "uint8" => "SetUInt",
            "int32" or "int16" or "int8" => "SetInt",
            "float" or "float16" => "SetFloat",
            "char" => "SetChar",
            "string" or "reducedString" => "SetString",
            "localDriver" => "SetDriverId",
            "uint8Array" or "uint16Array" or "uint32Array" => "SetUIntArray",
            "floatArray" => "SetFloatArray",
            _ => throw new InvalidOperationException($"no writer call for parameter type '{param.Type.Id}'")
        };
        return $"CanGenericWriter.{setter}(ref Generic, ParamTable, '{param.Letter}', value)";
    }

    private static void EmitParamType(CodeWriter writer)
    {
        writer.XmlDocRaw("""
            Type of a parameter in a generic message's parameter table.

            Mirrors <c>ParamDescriptor::ParamType</c> in CANlib's <c>CanMessageGenericTableFormat.h</c>. The
            value never appears on the wire, but its low nibble is the element size in bytes, which is what
            decides how much room the parameter takes in the packed data, so these have to keep CANlib's
            numbering for both sides to pack a message identically.
            """);
        using (writer.Block("public enum CanParamType : byte", "}"))
        {
            writer.Outdent();
            writer.Line("{");
            writer.Indent();
            writer.XmlDocRaw("Absent, and the terminator of a parameter table");
            writer.Line("None = 0x00,");
            foreach (ParamType type in ParamTypes.Ordered)
            {
                writer.Line();
                writer.XmlDocRaw($"CANlib's <c>ParamDescriptor::{type.CppEnumerator}</c>"
                    + (type.IsArray
                        ? ", a length byte followed by that many elements"
                        : type.ItemSize == 0 ? ", a null-terminated string" : $", {type.ItemSize} byte(s)"));
                writer.Line($"{type.CSharpName} = 0x{type.Value:X2},");
            }
        }
        writer.Line();
    }

    private static void EmitParamDescriptor(CodeWriter writer)
    {
        writer.XmlDocRaw("""
            One possible parameter of a generic message, identified by its G-code letter.
            """);
        writer.Line("/// <param name=\"Letter\">G-code letter that identifies the parameter. A letter outside A..Z marks a retired table entry: the position is still reserved so that the entries after it do not shift, but the parameter is never sent.</param>");
        writer.Line("/// <param name=\"Type\">How the value is packed into the message data.</param>");
        writer.Line("/// <param name=\"MaxArrayLength\">Number of elements, for the array types only.</param>");
        using (writer.Block("public readonly record struct CanParamDescriptor(char Letter, CanParamType Type, byte MaxArrayLength)", "}"))
        {
            writer.Outdent();
            writer.Line("{");
            writer.Indent();
            writer.XmlDocRaw("Size of one element in bytes, or 0 for the string types, which are null-terminated");
            writer.Line("public int ItemSize => (int)Type & 0x0F;");
            writer.Line();
            writer.XmlDocRaw("True if the value is a length byte followed by that many elements");
            writer.Line("public bool IsArray => ((int)Type & 0x80) != 0;");
            writer.Line();
            writer.XmlDocRaw("""
                True if a G-code command may supply this parameter, i.e. its letter is in A..Z.

                CANlib puts a parameter outside A..Z to keep it away from G-code while holding its table
                position, so that the parameters after it stay on the bits the receiver expects. Some of
                those are retired entries that are never sent at all (M569.1's <c>h</c>); others carry a
                value the sender fills in itself, such as the driver number in M915's <c>d</c>. The two
                cannot be told apart from the table, so the rule is only about where a value may come from:
                never from a command, always available to a caller that knows what it is doing.
                """);
            writer.Line("public bool CanComeFromGCode => Letter is >= 'A' and <= 'Z';");
        }
        writer.Line();
    }

    private void EmitTables(CodeWriter writer)
    {
        writer.XmlDocRaw("""
            The parameter tables of the generic CAN messages, mirroring CANlib's <c>CanMessageGenericTables.h</c>.

            For backwards compatibility a new parameter must be added at the end of its table: the paramMap
            bit and the packing order both follow the position in the table, so inserting one anywhere else
            would silently change the meaning of every message built from it.
            """);
        using (writer.Block("public static class CanGenericTables", "}"))
        {
            writer.Outdent();
            writer.Line("{");
            writer.Indent();

            bool first = true;
            foreach (GenericTableDef table in schema.GenericTables.Where(t => t.IsGenerated(Language.CSharp)))
            {
                if (!first)
                {
                    writer.Line();
                }
                first = false;

                // The schema's own prose has to be escaped; the sentence added below is markup on purpose
                string doc = table.Doc is null ? $"Parameters of {table.BaseName}" : CodeWriter.Escape(table.Doc);
                doc += $"\nSent as <see cref=\"CanMessageType.{Naming.MessageTypeMember(table.MessageType!)}\" />.";
                writer.XmlDocRaw(doc);
                using (writer.Block($"public static ImmutableArray<CanParamDescriptor> {table.Name} {{ get; }} =", "];"))
                {
                    writer.Outdent();
                    writer.Line("[");
                    writer.Indent();
                    foreach (GenericParamDef param in table.Params)
                    {
                        string entry = $"new('{param.Letter}', CanParamType.{param.Type.CSharpName}, {param.MaxLength}),";
                        writer.Line(param.Doc is null ? entry : $"{entry,-64} // {param.Doc}");
                    }
                }
            }
        }
        writer.Line();
    }
}
