; generated by PrusaSlicer 2.4.1-beta1+n8 on 2022-02-11 at 16:36:00 UTC


;
; thumbnail_JPG begin 160x160 16296
; /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPER
; ETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4e
; Hh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCACgAKADASIAAhEBAx
; EB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQID
; AAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRk
; dISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2
; t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQ
; AAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEI
; FEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2
; hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU
; 1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD491iw1DTNRmstUtZ7a7jYiSOZSG
; B9eev171Ur0PwFdX3i5Y/Cut6ZcaxYIAI9QQfv9KUn7/mHjyhzlXOPQg9bmo2dv4E0WHVvC0cOuzSF
; kbxEBuitGPASKMMdknfdIM8/KO9AEmimPwz4YFr8Q3jvrCdPMs9AfJvIi3AlDcG3XGTjPzeneqXxHh
; vtcsv7W8O3iX/hS1JMNnbReUdNHTbLCDkHt5vIbrkZxXn97dXV9dyXd7czXNxKd0kszl3c+pJ5Jqxo
; Wr6loepR6jpN5Ja3UfR0wcjuCDwynuCCD3oAo1ueC9K1/UdWE3h9mt57IefJeGcQJaqOrtISAoH159
; 67/S/CfhzxZDY6zqaL4Wub7cY7CKaKKPUmAODbhzmHc2F+YFMn5fSuQ8c65qwZ/C/9mN4f02ycD+y1
; GG3gD55XwDK567jxzwAKAO8k8T+FZb6eLT73TrbxaYhH/wAJHJp6x2ssgJyUUMREzcfvgozg8KDXlP
; iXSdV0bVpbPWYJI7o/vCzNuEobkOrdHU/3gTms2u28C6rqWsrb+D73R5PEWmkkw24cJNZ5OWeKU8Rj
; uQ3yeuOtAHE16j4K+0+F/D8v/Ccusfhu9R3i0O6hcz3j7RtkiXAMI6fvcjpxntNqehaR4G06fW/D6w
; +Lp1nMQvHjSS20wgnG9Fc7pehDMNnpurzDUr271K/nv7+4kubqdy8sshyzMe5oA9I8XRXXibwys/gi
; 4B8OWMe640K33JLZEcmSVSx87/rrk/RcEV5fVrStRv8ASr+K/wBNu5rS6iOUlicqw/8Are1ep6X4d0
; TxrpFtrXiYL4Ou5rlIlvfKEdtqm4klkQ42uB1ZfkyefSgDzTwzpmq6trUFroscjXoPmI6Ps8rbzvL8
; BQuM7iRivV21/wAHx6hFZ6vd6bd+KzAUbxJHaJPZxTkqVLJ92UgAgzbeCc4PUcZ461bVNG87whZaXc
; eG9NjJMtt5xaW8z0eaQcSAgcAfJ6etcTQBu+ONM1/T9dml8Ql57m6ZpVvN/mR3Qz/rEccMp9unTA6V
; hV1fgbXdSE8Pht9OOvaXeS7TpbgklmPLRN1jf/aH45FdjdeEvD3huzvta0aM+K722P8Ax4PJDMumAr
; 964WMsJipOMrhAVO70oAyPh9DqOgaU+s+ILn7F4Wuvv2dxAJv7UxxtiiZlycH/AFmRt457Vd114/En
; hlbH4chLPToVaW90RNwvZGHWRmLE3C+gH3Rxt7153rmr6jreovqGqXTXNwwC7iAoVQMBVUABVA6AAA
; VVtp57a4S4tppIZozuSSNirKfUEcg0AMZWVirAqwOCCMEGrWkWGoanqMNlpdrPc3cjARxwqSxPrx0+
; vavSdMsbf4g6LNrPiqMaDNbFVk8SeUFguyWxskj+UPIBn5k54+bsayvHF5d+EvO8MaHpcuj2VxGjPf
; ly1xqceOH8xWKeUeoWPj1JNAGL4n8Um/sv7F0ayi0nQY5NyWsQ+eYjo8z9ZH+vA6ACqXhbxJqvhu7l
; m06SNop08u5tp4xJBcJ/dkQ8MOT9M8VtX3haw1rTpdZ8EyzXKRAveaVMQbq0GTyvTzo+PvLyOMjqao
; eGvCdzqdjJrGo3KaToUJIlv5gDuYD7kSZBlfthencigDWj8Oab40Wa48FQvbaqimWfRJZM5UY3NbyH
; 7wGfuN8wHTdT8aB4DJWRLPxD4oikII+c2mnOp/ATSZ/4ACO+Kz9W8VwWli2jeELeTTNOYIJrlgBeXh
; XnMjgnaueQinA96uWfiDRvFaLYeNy0F/jbb69CmZFPYXCD/Wr/ALX3h79gDk9Y1TUtZv3v9Vvri9un
; +9LPIXbHpz0A7AcCuj0/xVaapaRaT41t5dQtoxsg1CIj7ZaDGAAx/wBYg/uN+BFZur+Ete07ULaz+w
; ve/bADZS2QM8d0D3jZfvfTqO4FbI0jRPBwMviVYdV1tdhj0eORhHbkjOblwMEjj92pz6kdKALI+G7W
; ytrV/run/wDCJqQV1aB9xnBJ+SOL73m8EFSOCDk4Gaydb8VQrp8mh+F7I6TpDrsmZ9j3V4N2QZpQoO
; OnyLhR79acnxC8UHWZdQub4XkUy+XLYXC77R4s/wCq8rOAg7AYI7EHmrVx4e0rxSJL7wWTFeEb5tCm
; fMq+vkOf9ao/u/fA7HrQBzfh/W9U0DUFvtKu3t5QNrAcpIp6q6nhlPoQRXVx6Vo3jpVPh2CLSPEm0l
; 9KBxb3mFyWgY/6tuCfLPHoeMVg+HPCuo6xJNI7Q6dYWsgjvL28cRRW5PY7iCz8H5Fyx9K7Xwza3Wpl
; 9F+G1lLbWozFqGu3iILiRWGCFOMxJjOEQ7jnk1dOnKpJRgrtgZMGiaZ4Tu47bVLE+IPFDKDFo0aF4L
; Z85AmZGzI2OfLUY9T2qj8SNN8Zpexar4qt5gLhAYiOYoR2iAHEeOm3j8a+i/DPh+PSbCzW9nXVdRtY
; fJXUZ4FE+zJwgbltozwCTitW9tba9tJLS8gjnglXbJHIoZWHoQa+io8Pt0r1JWl+C9TNzPl3w94uh/
; stfD3iuzfV9EAxDtYLdWR/vQyEcD/YOVPoOc6B+G09xatrun63YS+FlUyPqsm4GEAgFJIlBcSfMPlA
; IPrg5rvPEfwn0XTrq612ysr7VLeNC0eixHaHfnrJuDBBwdqgsexrzZviH4sttZW5trv+z4oEFuumxI
; RaJGODEYmJBHXOck5POa8PFYSrhp8tRf5MtNMdqfiy10qxn0TwPHcadZy/Jdag8n+l3wHqRjy4z/cX
; 8Sc4rmdF1TUdG1KHUtKvJrO7hOUlibBHt7g9CDwRwa7BNG0XxwJJ/DYg0fXSSz6PJJiG5Jyf9GY9D/
; 0zb8DWDoPhLW9W1K4shbfYBZ5+23F8DDFaAdfNYj5T2xjPtXMM3Yo9B8d3CxRJa+HvEkpCqqjZY3rY
; 4AH/ACxkJHupJ7E0f8I7pngkrc+NYjc6uDvt9DhlRh2Ia5dSdqnOQgyx74BqFvEWleFIpLXwU0s2oO
; oWbXJRh8Y+ZbdCoMSnONxO4j+7VfS/FsV5aR6R4xtpdX05AViuFYfbbTJzmKQ/eH+w3yn260AY3iPX
; 9T1+5il1CWPZAnl28EMSxQwJnO1EUBVH4c981oeHfFT2VgNF1iyj1jQy5Y2kxw0JPV4X6xt344PcGm
; +JfClzpdoNV0+5j1fQ5CBFqFuuFBPRZE6xP/st+BNX9O8Mado1vFqvji4ltYXCvBpdsyNeXKsCQWG7
; 9ynT5mGSOg70AXtMsNP+H91Bq2vTvc+IYJFltdKs7oL5BHe5dQdv/XNfmPcgGpNS8RWHxEihh8R3ce
; j63bIUtLwEiylUkny5E58psnh14P8AEOM1w+s2eoWGqXNpqsE8F9HIROk4IcMecnPXOc575zVSgDR8
; Q6Jqmgag1jqto9vKBuUnlJFPRkYcMp9QSKt+FfDGoa+7zRmO002Aj7XqFwdsFuOvJPVsdFGSa7fRHT
; RPBjWHxGl8/Spwr6dpKsr38JbBE0eTmBMdm4bn5ecnP+IkV/rGlLqug3FveeE7aQ+VbWVsIf7OLdBN
; EOQxxjzCWDf3u1AE2kfEDT/CECaP4Zs5tS09t3224vZJIZLglWUmJUciD5WOGX5/U9qxdR8K2mp2Nx
; rPgu4l1C0gUyXVjKALuzXHJYDiRB/fX8QK5Ct/wHpfiXUdfik8LrOl5anzTco+xbde7u54VcZznqMj
; mgDBVWZgqgsxOAAMkmu103QrDwr9n1jxfNNHd7FuLPR7aVortzu+VpH24hXuOd57Ada73SrjQtZ1u+
; i8MRwS+MEgLf29Hp7rZtL825kRWIjc5wJmXBKnCjIJ6bwB8ObLQpV1bWJf7V15mMjXTszLGxHO3PU/
; 7RGfpXfgsuq4t+7ou5LkkULPRdW+JWkW9546s5NPiim86yjtLhk3xtklXjbcAeR8/Dkdexr0PTbGz0
; 2zjs7C2itreMYSONcAVYqG5uIrdMu3PZe5r7HCYKjg42gterMm2yVmCqWYgAdSTSI6uoZDkHvXP6pq
; B+zzXExZLeFC7hVLbVHUkAZNVvBPjDQvEluV0u8zPFw8Mg2yY9cdx7j8a1WJp8/JfULHUJIGlePBBQ
; DJ9a4n4h/DfSPFim8ixYapt4uETiTjgSDv9ev1xiu2RwevBpTIm/ZvG7GcZ5qq1GnWhyVFdAro+aW8
; DJ4VmXUfHF39ltUmK29rZvvnvioBOwjhF5XLtgjPAzWjP8QtP8W2TeHvF9vLp2meYr2l1YSSSPbsFC
; gyq7HzxgD5j8w5wecD3fX9G0zXdOew1WzjuYHHRhyp9VPUH3FeA/Er4W6j4daTUNIEl/pWcnAzLB/v
; AdR/tD8QO/yWYZPUw9509Y/ijSM7nJ+J/DOpaCY5pvKutPuD/ot/bNvgnHX5W7H1U4I7iqegaPqOu6
; nHp2mW5nuHBbGQqoo5LMx4VQOSTxXd/DT+1NC0qbUtfnisfCN0R51tf2zSrqBx0gj4JfAx5gIC8ZPG
; Kt6sT4h8LvafDQ/YtNhQyahokbsL2ToDI5LE3Cew+7kDb3rxSzP0zxFp3w5aaHw5dR63rE0Yju7zeT
; YIA4bZHGVBlPGN7EAZO0d6r6pYad4+vZtU8P3D2+uztvuNJvJyxmbHJt5WPz5IPyMd3pmuCqzpdne3
; +o29lp0Es93NIFhjiGWZu2KAO58EXd14za28L69plzq9vAu2HUYzi402L+80h4MK5ztc4HYjgVd1Kx
; tvh9ottq2gRx63eXnmLD4gRt1va8kbY0H3ZtuDufoSdoOM1y3iHxUbmwbRNBsl0bQxIX+zxOxkuD0D
; TuSd7e3CjsKoeGvEeqaBLKbKVHt512XNpOnmQXC+joeD9eo7EUAZ17dXV9dyXd7czXNxKd0kszl3c+
; pJ5Jq14f1rUtB1JdQ0q6a3nAKtwCroeqMp4ZT3B4rp38O6b4vikvvBUTw6iil7rQnbc4A6vbuf9Yn+
; wfmX/aHNWbHT9I8K6klitvD4p8VmVoY7aIlrOzk4A3Ar++cHPAOwdycU0m3ZAbOneDtC8V6fZa3dxr
; 4XubjcRYJNEq6kArHdaI7bkYsoXDfJ82QT0q7p3hHxJ4r36SdOPhDwtbyAfZTCvnTOnGZDw0j9fmb5
; R/COMV0fhX4c3F7qP/CR+P7t9X1ZznyJGDwoMcBhjDY9B8o9DXpagKAqgADgAdq+jwGRuVp4jbt/mZ
; yn2Mzw14f0nw7p4sdIs0t4+C5HLSH1Y9Sa1KZNLHCheRgo/nWJquqIIJJJJUt7ZBud3YKAB3JPAFfS
; NwpRstEiNy/e6gsZKQ4Zx1J6CuC8deONO8OoyTyG71Flylup556Fj0Ufr6CuQ8Y/FQxXK2/hpEfypP
; 3lxNGGV8HoozyD6n8PWsFtL0fx5cvN4ciTSvEEu6STSXcmG5YckwOfuk8ny2/A9q+dx+c292lq+/Qu
; MO5iaj408SXmtR6sNUntp4W3QrbuyJEf9kZ/POc967nw9pdn4sgtPFN1PH4M1AXSxtfxyLBb6ic4cx
; KSNkuM52/uyeu3JrnZdI0XwVGX8RxQ6t4gKKyaQd4htCcMGuGUjc2D/q1P+8e1c34l8Qat4ivzeate
; STsMiKPOI4V/uRr0RR6CvnJVJSlzN6mh7zY/Eq1tfEsvh3xNpd3oM8RCJJeSq27gYaQqqqu7rkDbz1
; xzVq88e+GdJ8R/2de6iPOkbY7KpZIskYLt0A/PHfFeJ6T4sin0uHQfFdo+q6VCpW2kVgLqyzj/AFTn
; qvA+Rsr9KvP8O5pkXV7DWbCTwuw3HV5n2CEAgGOSPlhKMj5ADuyMEjp6tPO8RCCi7NrqyeVH0pbzpL
; EksUiyxOoZHU5DA9CD3FTggjIrwTwf48t9K17SfC/hm3uJdIkvRDJcX8peWfzGVd6qABEo6hRnryc1
; 70jKRgce1fT4DHRxlPmSs1uZyVjzj4sfDT/hKZ/7X0y68nUkiEZjlYmOVVGFA/uHtxx7Dk14NcQa14
; Y1xVlS60zUrZg6EEo6HswI7e44NfX4dvP8sphcZ3etZfiHw3ofiKOBdb0yG7ELh0LZVhzyNykHB7jP
; NcGPyaFe86Wkvwf+Q4ztueKaXp1n8QNGuNX8SQ/8I/dwsobxD5YW0vGLBSsicAy853IeeSwGMmh43v
; rvwXJP4W8PWFzo0LgedqJlJuNSTHDB1O0RHPCpx/eJOaf8atC8U2OpJc6iI5tGi/d2H2SPy7e2Qn/V
; iME+WenXO71JzjB8MeLRZ2X9i+ILEa3oTHi2lfD2zH+OB+qNjt0Pcd6+Tq0Z0ZuE1Zmqdyxqnhay1a
; 3m1fwPNLe2qDfPpsv/AB+Wgxk8f8tEHPzLnjqB1qh4Y8KXerW0mqX039k6FB/r9SniYxjnGyMD/WSe
; ij8SOtb+haZZeBb+31XX5p5fEEMu6y0exmUukgxtNw6tlASfuD5j3xXpVl4Ofxvaabq/jXShpl3bvI
; DZWjmOGaNmL5aMcxuXYkkHJ781rhsJVxM+Wmv8kJtI4zwvZ6xrAl0n4d2c2haQdoudamMiXF3t4ILg
; kAEkny0wP7x717ZpGkwWOyeVvteomBIZ76SNRNOFzguVAyeep5OBknGat2VrbWVpHaWcEcEES7Y441
; Cqo9ABUrsqKWYgAdSa+wwOV0sIubeXf/IycmxaqXl9HB8q4eT0z0+tVL3UWbMducL/AHu5+npXBeKv
; FFyNEvbrwpHDq89pIY7zy23NajA/eFOrLk43DKgg5Nb4rG06Ebyf9eQkrmt4y8WafoVsbnU7kNMVJh
; t1PzyewHYe/SvOvEdxffEbSjJ4cvpHltoxJc6AwAmJAOZIiP8AXDvt+8PTmvNNRvrzUbprq+upbmdu
; ryMWP057e1dZpehWnhmGHW/FV1cW9wUWax0uzuPKvJcnKu7YPkpjnJG49h3r5HG5lUxLstI/1uaqNj
; J8MeFdR1wzT7obHTbR1W9v7txHFb5PfJBZvRVyT6Vp3fiXTtC099J8GRurSxmO71i4gCXU4OQVjGW8
; mMjsDuPc9q2tW8aWPxBhGk+J3XRJEnkl0+8twzQIzn7twmcsDjHmj5h1IIzXEeJNA1Xw/eLbanbeX5
; g3wyoweKdP76OOGX3FeaUb9j4m03X4otN8cpLJtVY4NZgTddwAdBJ/z2Qeh+YDoe1ZXiXwpqmiTQEi
; O/srsgWd7ZkyQ3GQOFOM7ucFSAQe1VvDPh7VfEV61rpduH8td800jiOKBO7O7YCj69e2TXbaR40sPh
; 7DLpnhZl12aScPeXd2jLbkoRjyI1fr1/enDegFAGTbeG9M8MwLqHjjf9qaMSW2goWS4l54MzY/cp3x
; neR0A61BN8RPE39pJcWt2tpYxoIotLjXNmsX/PMxNlWBxyTknrmp9T8O2HiQT6v4KmnuJCGmudIuZN
; 95D3Yof+Wyc5yPmA6g9a4tlZWKsCrA4IIwQaAO+s7LTPEV9a6v4LEOleILeRZm0eWTKSyKdwe2ZuDy
; B+6bkdAWr1r4deOf+Ek8+w1DT59P1azUfakMbCMEsFHJ+6SSBtbn0zXiukeFoNNtLbXfGFzLpdjIDJ
; bWiqwvL3AyDGNuEQnH7xsD0zXquiQ6p8TvDX2fX9Mk0nREZGsZba9kE0oVVX94H3CbhB+8cAg9Mgmv
; UyuviadXloq991/WxMkup6dG5PB/On1Bp9rHZWMFpE8rpCgRWlcu7ADGSx5J96nJAGTwK+4V7amIye
; GK4heGeJJYnGHR1DKw9CD1rxz4g/DfwjobyeJJp72DTIcPPp1uoZpWLhQqMzDYpLcnnA6CvVb3UQuY
; 7cgt/f6gfSvP/iBJH4h0LVfDulXVvea00aSizWZfNcLIrMACeWAGdv3j2Brys2VCdCXOtUtH5lRvcn
; +Dfg6xsNIj1rVtPlOvTSyecb1cvA6yOvygjKk4yT1OeuK9Krxj4LfEC8vnh8NatFc3cqITDeAlysaj
; J80noqj+LoBge9evWtzFNCk0MqTROMq6MGBHqCOtXlVWjLDxjT3SV/UJJ3LNY/iITQ2st6RLNFChcx
; xIWfgdlHJNaz5aNvLIDY4J7GhAwRQx5x81ehOPMrEnzH49+IN74gElhYq1pphPKniSUf7ZBIA9h+Oa
; xvAth4lvdeifwuLqO8hIdrmIlVt1/vyP0VPUnive/G/wu0DxNfC/V5NMu3kDTywIGEozzlSQNx/vfn
; mvG/iNqGpWMj+Fo9FHh/SYJNy2qjLXJHAllk/5atjuPlHYCviczwuJpVOarqn16f8AANotPY7WPVvB
; z3DLpF9pEHjh4Qo1gWzxWDTktu8oEgRyYIAlKbSRkBc5ryjxRaa3Z63PH4iS7XUWIeVrlizvno24k7
; gfXJBrMrtfBmq3muRQ+EtT0a78RWWD9lW2TN3Y+rRPjhOmUb5OM8da8so4qvTfAvm6V4Vkm8aTW7eE
; rpGkh0ychrm5fOA9suQ0fzdXyFIznPazqfhrTPAWmP4i08QeLJ4rx4Y7gENbacykBfORScyZPAJ2cA
; /NkV5rrGqalrN+9/qt9cXt0/3pZ5C7Y9OegHYDgUAd94zWTVvDJfwS8B8LW0cct1p8ESpdQOq4MlyB
; 80vOT5mSo/2a81q7omralompw6npN5LZ3cJyksZwRngj3BHY8V6LpPhzSfHthHrN2lt4TuHuVhe4Lo
; lpfsSAwhjZgVl5zhcp6laAOA8L2Gt6jrltb+HYbuXUg2+H7MSroR/EGGNuPXIxXrunzeHNQ8S29rNH
; Z6p46EeH1GKxMunCYlfmlVH+d15zKF2AnJDYzVGx8NeINYmufDHh/R5/C2gRsbe/ubyNGu7kg7v3jA
; Bn7YRSEH616n4L8I6N4UsBb6bbr57KBNcsMySn3PYew4r1cBlNXFe9LSPfv6Eykkcz4Q+Gvl6i2veM
; 7z+29YdxIpd2aOIjnv8Ae/EYHYV6NRVO9vkgyiYaT07D619fQw9LCw5YKyMm2yxPNHCm+RsDt71j31
; +8ytjKRKpLAc8Dkk1zfjTxdp3h+AT6lM0k8gPkwJyz/wCA9zXiWveO/Eeq6nFepfS2HkMGhjtZGRUI
; PDdeW9/5V52PzWFD3Vq+3+ZUY3On8dfE6W5Elh4cLwxZwb3kO49FUjK/Xr9K880y31HUNWgg09J7i/
; mlHkiPJkZ85BB65zzmvQtL02z+IOjT6nrKxeH7+0IEutsqx2V3kgBZF4/fdTlOvO4d6p+ML+48EPc+
; GfDtheaUkuRPqczq1xqERxgo6gBIT1CqTnuTXyeIxNTES5ps0SsY/iHxeZrBtE8NWbaFoZJL28UzNJ
; dHpunfPznj7v3R2FSfD/x5q/hK4EcbG601mzLaOePqh/hP6HuOmJNS8IW2paZPr3gu5k1GxhBe7sZB
; i8sRjJLgcSJ/tr+IGDWb4c8KX+rWcuqXEkel6ND/AK7UrtXEIOcbU2gmR/8AZUE+uKilWnRkpwdmNq
; 59JeDfFekeKLD7XpdwC6gedA5AkiP+0PT0PQ10KOG46GvmC88XwaJG2meBo5bC3EgaXUJDm6vCvTd2
; RM87B+JNel/Dj4q2essmna+YbG+wAk2cRTHpjn7re3Q/pX1mAzmFa0Kukvwf+RlKFtj1asvxL4f0nx
; Fp5sdXs0uI+ShPDRn1U9Qa0Ek7N+dSDmvblGM1yyV0QfPOv/CG90rUZ7mfVIYvD8MbTS3zLvkiQdF8
; sEF3PAGOPUiud1XxXbWmmy6H4QtH0zT5QouLtyReXmBz5jBiFTPPlrx65r6nYBlKsAQRgg968k+Ivw
; ftr5pdS8LCO1uSdzWRwsT+uw/wH26fSvl8fkbj7+H1Xb/I0jPueNeG9f1Xw/eNc6Zc+X5g2TROoeKd
; P7joeGX2NdH/AGPo3jKJp/DMcWla4DmTRpJf3dz1ObZm7/8ATNjn+6T0rM0HwXrup6jcW81rJp1tZc
; 6hd3aGOK0XgkuT3wQQo5Paus8OW80876L8NLOV3eMw3niS5jeJznkhMEiFSOMAFz69q+fjTnOXJFam
; hlQaLo3g+ZT4otxrOuHYYtDhkZVhLDINw4Xk8j92pJOeSK9D8P8AgDWPEuoJr/xDupZWXabXTUcCOJ
; P7hUcIvA+Rce5zmu68NeHY9Ngs59RnGqavbweQdRmjUTMn93d1IHQbiTjvW7X1OAySNO06+r7dPn3M
; pT7DYo44okiiRY40UKiqMBQOAAOwokdI13OwUepNQ3d3Fbrydz9lBrlvFHiKx0q1N7q12sEXOxOpY+
; ijua9upWhSjr0JSubGoanlG2N5USglnbjjv9BXlHjr4m21kJLHw8yXN0DhrrAaJR/s8/Mf0+tVdZ1a
; 6+IulfYvDWom1vUDGbR5yqPdqMkGKT+M46x8HjPPbzvQ/Desavf3FnbWwia0BN3JcusMdsAcEyM5AX
; B4wee2M18tjs4lN8tH7/8AI0UO5012ui/EC6+0WrQaJ4mm2h7eR8Wl85OMxsf9U54+U/KexFQL4a07
; woi3fjdWe+ZGaDQ42IkfsrTOp/dpnnAO4jpjrT31zRfB0T2nhMpqWsbiJtauLdcRY4H2VSTt/wCuh+
; Y9gKrWPiy21azg0jxtBNqNrENltqEZ/wBMtF7AMf8AWIOuxvwIrwW7lmT4n8T6r4gaKO7lWGytwFtr
; C3yltbgDGETJwfUnJPcmrug+KxFpiaD4iszrGiK2Y4mk2zWhPVoH/g915U9x3qDxT4WutGjiv7W4j1
; TRrj/j21K2U+U/+ywPMbjujYNaWkeE7TTLOLWvG802mWb5e20/y2F3fAc4UY/doeBvbj0zQBd0jTof
; h/dW2s+I7m7i1pQZLbR7WTZIOMq1xIrAxKc/cALEegq/qOvab8TYobXWL2Lw/rcAZbTDMNOnLMzbSp
; z5Lc435IbvXnWqW99aajcW+pQzw3iSETpOCHDd92ec1WoAva7pGpaHqUmnatZyWt1H1R8HI7EEcMp7
; EEg9qteGPDmpeIJpRaLHDa26GS5vLglILdQOrtg49gMk9ga7/QCuleClh+J8MkujyDOkWDxf8TDOeX
; iYkGKL13fKf4Rzzm/EWHUrzRYbrw+1vN4LgcrbRaeHCW7Hn/SEYlhLyMsxIPY44oA29B+JuleF/sWh
; Wr32tafCMXGoSuQzMQP9VGwBVF5wGOTn+HofX/D+t6drenpf6Vdx3MDjqp5U+jDqD7GvkCup+GU/iq
; HxEi+Fd5ncfvww/cBB1aXsFHJ3HGO1e1gM4qYe0KmsfxREoXPqoEOpAODj8qSJGSNVZySDyfWuU8O+
; N/D+raj/AGRDq1nLqUaAP5JbyZXA+YRM4BcA57cjkZHNdWkmeGr62jXp1488HdGbVjG8YeFdI8VWMV
; pq0crJFL5qGKQoQ2AD7HIGOa0NH0zT9HsEsNMtIrW2T7scYwM+p9T7nmrlRXNxFAm6RvoB1NNUqcZO
; okrvqIlJAGTwKzL3UeqW5z6v/hVDV9TVbaW4uZFhtYVLuT0VR3NeJeO/iVc6mr2GheZa2bKVklYYkk
; 9cc/KP1+lcWNzGnh46vX8SlG56V4j8QTR2OpDQUh1fVrEBprRZQZI0IOZCmdzqvG4LyNwzgcj5+1zW
; NR1q9a71K6knkJO0Mx2oD2UdAPYVJ4Xt9cudctl8OQ3smpo2+H7IGMikfxZHQDuenrXq0l34Qi1CIa
; teaHN43ijcG9+zv/ZyTqV2+cFIVpfvDzACmeWDYzXyGLx1TEv3tF2NUrHB+H/DUFrp8PiPxNqD6Xp5
; BktIYXxeXhHQwjB2rkD943A7Zro9S8f6b4zhbQdfgl0WykkVoL22laR1cKqhrocef93JbAYc49K4zx
; zB4mh1+U+Knu5b9xkTTyGQSJ2KNyGTnjbx6VhVxjNjxP4b1Pw9cRreJHLbTDdbXlu3mW9wv95H6Ee3
; BHcCq2gaNqevanHpukWj3V1ICQikAADkkkkBQPUkCu2+GH26002W912ezTwW8m27g1DLJcsOot4wdx
; mGeGTG3+I4BFXdYxqHhOS1+GZC6T5Q/tSy8tRqT4y26VuskY7bDtHcUAUtP1yx+HMVzZ6XeJrmszhF
; uQ3zadDjkqAGxO4OBuICjtnrUWuabZ+Pbu417wzNL/bM7GW80a5l3ylieWgc481f9j7y9sjp5/VnS7
; e+u9Rt7fTYZ5rx5AIEgBLlu23HOaAO28Lai/jY23hfxDZXOoyxqRaanBtFzaIOvmMxCyRADPzkFezD
; pV7WdJsfh3pdvqWnR2/iK8vcrb6x5cc1hbsrEERqdweX5ercDsD1rnNc8XA6U2geGLSTRtFYATp5oe
; e9YfxzSADd/uDCjJwKoeFvE2peH2nit/KubC6AW8sbhd8Fyo6Bl9R2YYI7GgDM1K9u9Sv57+/uJLm6
; ncvLLIcszHuaveF/EeseGr83mkXbQM42Sxkbo5k7o6nhlPoa328L2HimL7Z4GDm7AH2nRJpMzxf7cL
; HAlj9f4l7gjmpI7TQfBGZNXW213xEqnZp42TWVo+SD57BiJHH9xeAepPSgDoNP8D6X4zgtddhtZvC3
; 2qba1iVBS9O0sTZb2GScfdJ2jPB7VyXivxHdRw3HhnStMk8O6VHMwmsgXE0zAjm4LHLMMfd4UdhWFr
; Ws6nrOpnUtSu3nuiFAfAUKF4UKFACgdgAAK6jTvE2keIbVNL8dpKzooS21uBN11CB0WUf8tk+vzDsT
; 2AOKjd43WSNmR1IKspwQR3Fey/CT4l6neala+HdZhuNQkuHEdvcxKWlB9HA+8O+7qMc56jkH+G9/Bc
; vdXuqWNv4cVBKuuAl7eVCcAIF+ZpM5GzGQQc+tV9U8W2+nWcuj+CYJtKspAq3N8ZGF5e4znewOEQ5/
; 1a8epNdOGxdXDT5qb/yYmkz6Ye7UWjTW8kcq9FZWDLnOOo964Txz4107w9CzXMour9vuWqOAx9267R
; +H0zXiPhPxfrnhl2Gm3IMDkF7eYb4mwc/d7fUYNbt/pul+OZ21Dw5KbTXZfmudIups+e+OWtpGPzZx
; /q2O4diRgV7FfPXOmlCNpfgSoGXqPj3xPda0mqQ6lLaPCW8iOHARFPVSP4gRwd2c11mleFtM8f6Ymv
; zCDwlMbhYJ522CzvXPeFCylZMnlQdnfK8isFNG0XweFuPFSLqWsK6mPRYZwFi4zm5cA47fu1OfUiue
; 8S+INU8Q3UU2pTIVgj8q3gijWKGCMdERFACj/JzXgTnKcuaTuyzf8YatLoiXXhPR9JuNEtAFjvGuYw
; t5eEdTK2ThCeQinb069a4uuv0rxXaX+lwaB4xt5b+whOLW9iI+12QOeFY/fTJzsb8CMCpV+Ht9PPDd
; WWp2Nx4flBdtZL7IIVGNwkB+ZJBkfu+p7ZHNSBB4P8QXMsSeGNT0qfxFpdw2IrJNxngc/wAduwBKtx
; 937rdxXV6j4G0jwfZ32vzxnxQtpIirYZ2fYi65BvQhJUjIG1TgkHJxxXM3HifTtAsW0zwVHIksiFLn
; Wp4tl3NnOVjAYiGMjHQ7j3I6Vz3h3W9U8PapHqWkXb21ygK5HIdT1VgeGU9weKAH+JfEGreIr83mrX
; kk7DIijziOFf7ka9EUegqnpt9eabfRX2n3U1rdQndHNC5V1PTgiuxisNB8bA/2QtvoXiIgYsGfbaXr
; YOfKZuInOPuMdpJ4IqODwzpvhhFvfHO/7QY98GhwuyXMvOAZW2kRJ3/vHsB1oA2NL07T/iRbXOpahH
; a+G7+3I+1atlIbC4ZjwJFJG2U8n5M7upA61S8X6h/whVzceGfDmm3WlygMl1qN4kbXd0rDH7twMRxE
; dNh5B5JrmvFPifU/EEkaXEggsIAFtLCAlbe2UDACJnrjqx5Pc1e0HxYq2EWh+JrQ6xoikBELYuLQZ5
; aCTqv+6flPoOtAE2t+FbS8sJNd8GXEupaYo3XFpIB9ssecfvEH3k9HXj1x3zvC3he81yOa9e4t9N0m
; 2IFzqN2SsMZ67RgEu57KoJ5HQc10Oh6bF4Dlt9f8R3Vzbauq+ZZ6NAzxXDf3WnYY8pMj7v3mHYDmre
; r6/afEm3trS+vovD+qwEi3tw7Lpk5OSMKSfIkOcbuVbvigDGvvFVpotrLpXgeO5sYWZhPqcrj7XdDp
; gEAeUn+ypz6k1YXWdD8Y2/2bxQYtL13IEOtRxnZcdBi5Re//AE0UZ6ZBwSeT1rSdS0XUHsNVs5bS5Q
; AlJB1B6EHoQexHBqx4a0DUdfupYrJYkigj825uZ5BHDbp/edzwB+p7A0ALr/hzWND1COyvrRt8/Nu8
; R8yO4UnAaNlyHB9q6BPD+k+Eitz4yP2nUhkx6HA6sQdoKm4kVv3anIOwZYj+7W3pHj3SvBSRaJokM2
; uWsU3mTXtxJt2uUZGa0UrmE/MfnOS2OQBXN674XW606bxH4ZvpdZ01Tvu1kH+mWZOSTMgz8vB/eD5T
; 7HigCa1+JGvJfMbqKyu9KkiED6Q8IFmIgeFRB9wjnDD5snqadeeFtP8AENvPqvgRpZREpkudGncNd2
; 47mP8A57Rj1HzDjI7niq7jQNBXwv8AYvEvim+vNKIdZbKytCBe3A5+b7wMKf7TckHgGgDC8N+F9X12
; SZreEW9pbAm7vbkFLe2AGTvfBwfYZJ7A1t3XiPSvC8EmneCGke7dNlxr77o55AcZWBf+WSe/3z6jpW
; 3qXizSviPCdL12aHwxcpM01nNCWNlI7E589ck+Yf8Anr7nIrgvE3h/VfDmpGw1a1aCQjfG4+aOZD0d
; GHDKfUfzoA34/Eel+JoEs/GolF4keyHXIV3zjAAUTr/y2UYxu++PU1j+LfDGpeHLqNbryri0uF8y0v
; bdt8Fyn95G/mDyPSq/hvQdV8Q6iLHSrR55MbpHxhIU7u7dFUdya7rRfGdl8PrRNN0OePxFctIst3NI
; 0gs4mVukCEKd+MjzeOvAoAxLHwzp2iaeNX8aySR70D2ekW86rd3GRlWk4PkxH1I3HsO9Nk+ImureYs
; 4rG10oB410hLZfshjbGVdMfOTgZdstkZyKm17QV8Si48R+Fr281UtmW9sbuTzL61OOSTnM0fHDjnH3
; gK4mgDt5tA0jxZbvfeDVNrqajdcaFLJlj0+a2Y/6xep2H5hj+Liuf8PeG9Z17UZbHT7J2kgBa5eT5E
; t1HVpGPCAYOc+lamgeGVt7KLxD4jvn0jTNvm2oidftd2QcDyYycgZ/5aEbR79K6fVfHmk+NLW40HW4
; 5dDt5JUe1voSZGZkXaPtneb13DBUnOCOKAMVtY0PwazQeFWj1bWBuR9anhKpDkD/AI9k3dRz+8YZ9A
; Ac1DZ+LLbXIF0vx0Li/j6Qaqh3Xlofcn/XR+qMc+hBrE8S+HNU0CWIXsSPbzrvtruB/MguF9UccH6d
; R3Aqromk6lreox6dpNjPe3Uh+WKFNx+p9AO5PA70AaPiXwtf6NDHfRyw6jpM5It9RtCWhfHY90f1Vs
; Gr2leFbaz0+HWvF93JpmnzBmtrRFP2y8wOPLUqQiE8b349Aa6DSdcsPhklxa2VxB4g1mciO9gfcdPt
; wDkrgEedJkD5sYXnGap69p8fj68udd8O3l3c6s6+bc6PdytLcAAHPkOeZUAHC/eAHQ0Af//Z
; thumbnail_JPG end

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 149.429x13.0734,147.721x26.0472,144.889x38.8229,140.954x51.303,135.946x63.3928,129.904x75,122.873x86.0365,114.907x96.4182,106.066x106.066,96.4182x114.907,86.0365x122.873,75x129.904,63.3928x135.946,51.303x140.954,38.8229x144.889,26.0472x147.721,13.0734x149.429,9.18485e-15x150,-13.0734x149.429,-26.0472x147.721,-38.8229x144.889,-51.303x140.954,-63.3928x135.946,-75x129.904,-86.0365x122.873,-96.4182x114.907,-106.066x106.066,-114.907x96.4182,-122.873x86.0365,-129.904x75,-135.946x63.3928,-140.954x51.303,-144.889x38.8229,-147.721x26.0472,-149.429x13.0734,-150x1.83697e-14,-149.429x-13.0734,-147.721x-26.0472,-144.889x-38.8229,-140.954x-51.303,-135.946x-63.3928,-129.904x-75,-122.873x-86.0365,-114.907x-96.4182,-106.066x-106.066,-96.4182x-114.907,-86.0365x-122.873,-75x-129.904,-63.3928x-135.946,-51.303x-140.954,-38.8229x-144.889,-26.0472x-147.721,-13.0734x-149.429,-2.75546e-14x-150,13.0734x-149.429,26.0472x-147.721,38.8229x-144.889,51.303x-140.954,63.3928x-135.946,75x-129.904,86.0365x-122.873,96.4182x-114.907,106.066x-106.066,114.907x-96.4182,122.873x-86.0365,129.904x-75,135.946x-63.3928,140.954x-51.303,144.889x-38.8229,147.721x-26.0472,149.429x-13.0734,150x-3.67394e-14
; bed_temperature = 80
; before_layer_gcode = G92 E0 ; to keep PrusaSlicer happy
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = 
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M0\n
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #19C0C7
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = Kossel
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 30%
; fill_pattern = stars
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 80
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 225
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = reprapfirmware
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; infill_with_sheath = 0
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.2
; little_move_inwards = 1
; loop_clipping_length = 15%
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 1000,5000
; machine_max_acceleration_extruding = 10000,1250
; machine_max_acceleration_retracting = 10000,1250
; machine_max_acceleration_travel = 10000,1250
; machine_max_acceleration_x = 3000,1000
; machine_max_acceleration_y = 3000,1000
; machine_max_acceleration_z = 3000,200
; machine_max_feedrate_e = 60,120
; machine_max_feedrate_x = 250,200
; machine_max_feedrate_y = 250,200
; machine_max_feedrate_z = 250,12
; machine_max_jerk_e = 10,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 10,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0
; max_print_height = 450
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 10
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; optimize_island_extrusions = 1
; optimize_tool_order = 1
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 60
; perimeters = 3
; physical_printer_settings_id = Kossel
; post_process = 
; print_settings_id = Kossel
; printer_model = 
; printer_notes = 
; printer_settings_id = Kossel
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_skip_support_islands = 1
; retract_speed = 40
; retract_wipe_speed = 20
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_extra_loop_layers = 1
; skirt_extra_loops = 0
; skirt_height = 1
; skirt_speed = 40
; skirts = 2
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_length = 40
; small_perimeter_speed = 15
; solid_infill_acceleration = 0
; solid_infill_adjust_spacing = 1
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = 
; support_material = 0
; support_material_acceleration = 0
; support_material_additional_xy_spacing = 50%
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_expand_or_filter = -100%
; support_material_extruder = 1
; support_material_extrusion_width = 0.35
; support_material_interface_acceleration = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_interface_with_sheath = 0
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 225
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; threads = 32
; thumbnails = 160x160
; thumbnails_format = JPG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 15
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 1
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
