#!/bin/bash

# Add dsf user and group
systemd-sysusers duetsoftwareframework.conf

# Display config file note only on first installation
if [[ -z "$2" ]]; then
	echo "To modify config files consider adding yourself to the dsf groupd: # usermod -a -G dsf <username>"
fi

