<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<PackageLicenseExpression>LGPL-3.0</PackageLicenseExpression>
	</PropertyGroup>

	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DuetAPIClient\DuetAPIClient.csproj" />
		<ProjectReference Include="..\DuetAPI\DuetAPI.csproj" />
	</ItemGroup>
</Project>
