#!/bin/sh
# Create gpio group and add dsf to it
systemd-sysusers duetcontrolserver.conf

# Create /var/run/dsf now
systemd-tmpfiles --create duetcontrolserver.conf

# Trigger assignment of gpio group to the existing devices
udevadm trigger

chown dsf:dsf /opt/dsf/conf/config.json

# Update systemd services
systemctl -q daemon-reload

# Start DCS again if it is enabled via systemd
if (systemctl -q is-enabled duetcontrolserver); then
    systemctl -q start duetcontrolserver
fi

