#!/bin/bash

# Reload systemd services
systemctl -q daemon-reload

# Show group info only on package removal
if [[ "$1" == "remove" ]]; then
	echo "To delete \"gpio\" group run as root: groupdel gpio"
fi

