#!/bin/bash

# Reload systemd services
if [ -d /run/systemd/system ]; then
	systemctl -q --no-ask-password daemon-reload
fi

# Show group info only on package removal
if [[ "$1" == "remove" ]]; then
	echo "To delete \"gpio\" group run as root: groupdel gpio"
fi

