namespace DuetControlServer.SPI.Communication.LinuxRequests
{
    /// <summary>
    /// Request indices for SPI transfers from the Linux board to the RepRapFirmware controller
    /// </summary>
    public enum Request : ushort
    {
        /// <summary>
        /// Request state of the GCode buffers
        /// </summary>
        RequestState = 0,

        /// <summary>
        /// Perform an immediate emergency stop
        /// </summary>
        EmergencyStop = 1,
        
        /// <summary>
        /// Reset the controller
        /// </summary>
        Reset = 2,
        
        /// <summary>
        /// Request the execution of a G/M/T-code
        /// </summary>
        /// <seealso cref="CodeHeader"/>
        Code = 3,

        /// <summary>
        /// Lock movement and wait for standstill
        /// </summary>
        LockMovementAndWaitForStandstill = 4,

        /// <summary>
        /// Unlock everything again
        /// </summary>
        Unlock = 5,
        
        /// <summary>
        /// Request a part of the machine's object model
        /// </summary>
        /// <seealso cref="DuetControlServer.SPI.Communication.LinuxRequests.GetObjectModel"/>
        GetObjectModel = 6,
        
        /// <summary>
        /// Set a value in the machine's object model (reserved)
        /// </summary>
        /// <seealso cref="DuetControlServer.SPI.Communication.LinuxRequests.SetObjectModel"/>
        SetObjectModel = 7,
        
        /// <summary>
        /// Set information about the file being processed (primarily for PrintMonitor)
        /// </summary>
        /// <seealso cref="DuetControlServer.SPI.Communication.LinuxRequests.SetFilePrintInfo"/>
        SetFilePrintInfo = 8,
        
        /// <summary>
        /// Reset information about the file being processed indicating it has been cancelled or finished
        /// </summary>
        ResetFilePrintInfo = 9,
        
        /// <summary>
        /// Notify the firmware about the completion of a macro file
        /// </summary>
        /// <seealso cref="DuetControlServer.SPI.Communication.LinuxRequests.MacroCompleted"/>
        MacroCompleted = 10,
        
        /// <summary>
        /// Request the heightmap coordinates as generated by G29
        /// </summary>
        GetHeightMap = 11
    }
}