namespace DuetControlServer.SPI.Communication.LinuxRequests
{
    /// <summary>
    /// Request indices for SPI transfers from the Linux board to the RepRapFirmware controller
    /// </summary>
    public enum Request : ushort
    {
        /// <summary>
        /// Perform an immediate emergency stop
        /// </summary>
        EmergencyStop = 0,
        
        /// <summary>
        /// Reset the controller
        /// </summary>
        Reset = 1,
        
        /// <summary>
        /// Request the execution of a G/M/T-code
        /// </summary>
        /// <seealso cref="CodeHeader"/>
        Code = 2,
        
        /// <summary>
        /// Request a part of the machine's object model
        /// </summary>
        /// <seealso cref="DuetControlServer.SPI.Communication.LinuxRequests.GetObjectModel"/>
        GetObjectModel = 3,
        
        /// <summary>
        /// Set a value in the machine's object model (reserved)
        /// </summary>
        /// <seealso cref="DuetControlServer.SPI.Communication.LinuxRequests.SetObjectModel"/>
        SetObjectModel = 4,
        
        /// <summary>
        /// Set information about the file being processed (primarily for PrintMonitor)
        /// </summary>
        /// <seealso cref="DuetControlServer.SPI.Communication.LinuxRequests.SetFilePrintInfo"/>
        SetFilePrintInfo = 5,
        
        /// <summary>
        /// Reset information about the file being processed indicating it has been cancelled or finished
        /// </summary>
        ResetFilePrintInfo = 6,
        
        /// <summary>
        /// Notify the firmware about the completion of a macro file
        /// </summary>
        /// <seealso cref="DuetControlServer.SPI.Communication.LinuxRequests.MacroCompleted"/>
        MacroCompleted = 7,
        
        /// <summary>
        /// Request the height map coordinates as generated by G29
        /// </summary>
        GetHeightMap = 8,
        
        /// <summary>
        /// Resend a received packet (most likely because the checksum did not match)
        /// </summary>
        ResendPacket = 255
    }
}