using DuetAPI.Machine;
using NUnit.Framework;

namespace DuetUnitTest.Machine
{
    [TestFixture]
    public class Job
    {
        [Test]
        public void Clone()
        {
            MachineModel original = new MachineModel();

            original.Job.Duration = 123;
            original.Job.ExtrudedRaw.Add(123F);
            original.Job.ExtrudedRaw.Add(456F);
            original.Job.ExtrudedRaw.Add(789F);
            original.Job.File.Filament.Add(321F);
            original.Job.File.Filament.Add(654F);
            original.Job.File.Filament.Add(987F);
            original.Job.File.GeneratedBy = "Generated by";
            original.Job.File.Height = 57;
            original.Job.File.LayerHeight = 0.43F;
            original.Job.File.FileName = "0:/gcodes/somefile.g";
            original.Job.File.NumLayers = 467;
            original.Job.File.PrintTime = 4566;
            original.Job.File.SimulatedTime = 7964;
            original.Job.File.Size = 4645645;
            original.Job.FilePosition = 32423;
            original.Job.LastFileName = "0:/gcodes/lastfile.g";
            original.Job.LastFileSimulated = true;
            original.Job.Layer = 4;

            original.Job.Layers.Add(new Layer
            {
                Duration = 23,
                Filament = new float[] { 12F, 34F, 56F },
                FractionPrinted = 0.012F,
                Height = 0.33F
            });

            original.Job.LayerTime = 4.3F;
            original.Job.TimesLeft.Filament = 1234;
            original.Job.TimesLeft.File = 234;
            original.Job.TimesLeft.Layer = 345;
            original.Job.WarmUpDuration = 34;

            MachineModel clone = (MachineModel)original.Clone();

            Assert.AreEqual(original.Job.Duration, clone.Job.Duration);
            Assert.AreEqual(original.Job.ExtrudedRaw, clone.Job.ExtrudedRaw);
            Assert.AreEqual(original.Job.File.Filament, clone.Job.File.Filament);
            Assert.AreEqual(original.Job.File.GeneratedBy, clone.Job.File.GeneratedBy);
            Assert.AreEqual(original.Job.File.Height, clone.Job.File.Height);
            Assert.AreEqual(original.Job.File.LayerHeight, clone.Job.File.LayerHeight);
            Assert.AreEqual(original.Job.File.FileName, clone.Job.File.FileName);
            Assert.AreEqual(original.Job.File.NumLayers, clone.Job.File.NumLayers);
            Assert.AreEqual(original.Job.File.PrintTime, clone.Job.File.PrintTime);
            Assert.AreEqual(original.Job.File.SimulatedTime, clone.Job.File.SimulatedTime);
            Assert.AreEqual(original.Job.File.Size, clone.Job.File.Size);
            Assert.AreEqual(original.Job.FilePosition, clone.Job.FilePosition);
            Assert.AreEqual(original.Job.LastFileName, clone.Job.LastFileName);
            Assert.AreEqual(original.Job.LastFileSimulated, clone.Job.LastFileSimulated);
            Assert.AreEqual(original.Job.Layer, clone.Job.Layer);

            Assert.AreEqual(1, original.Job.Layers.Count);
            Assert.AreEqual(original.Job.Layers[0].Duration, clone.Job.Layers[0].Duration);
            Assert.AreEqual(original.Job.Layers[0].Filament, clone.Job.Layers[0].Filament);
            Assert.AreEqual(original.Job.Layers[0].FractionPrinted, clone.Job.Layers[0].FractionPrinted);
            Assert.AreEqual(original.Job.Layers[0].Height, clone.Job.Layers[0].Height);

            Assert.AreEqual(original.Job.LayerTime, clone.Job.LayerTime);
            Assert.AreEqual(original.Job.TimesLeft.Filament, clone.Job.TimesLeft.Filament);
            Assert.AreEqual(original.Job.TimesLeft.File, clone.Job.TimesLeft.File);
            Assert.AreEqual(original.Job.TimesLeft.Layer, clone.Job.TimesLeft.Layer);
            Assert.AreEqual(original.Job.WarmUpDuration, clone.Job.WarmUpDuration);

            Assert.AreNotSame(original.Job.Duration, clone.Job.Duration);
            Assert.AreNotSame(original.Job.ExtrudedRaw, clone.Job.ExtrudedRaw);
            Assert.AreNotSame(original.Job.File.Filament, clone.Job.File.Filament);
            Assert.AreNotSame(original.Job.File.GeneratedBy, clone.Job.File.GeneratedBy);
            Assert.AreNotSame(original.Job.File.Height, clone.Job.File.Height);
            Assert.AreNotSame(original.Job.File.LayerHeight, clone.Job.File.LayerHeight);
            Assert.AreNotSame(original.Job.File.FileName, clone.Job.File.FileName);
            Assert.AreNotSame(original.Job.File.NumLayers, clone.Job.File.NumLayers);
            Assert.AreNotSame(original.Job.File.PrintTime, clone.Job.File.PrintTime);
            Assert.AreNotSame(original.Job.File.SimulatedTime, clone.Job.File.SimulatedTime);
            Assert.AreNotSame(original.Job.File.Size, clone.Job.File.Size);
            Assert.AreNotSame(original.Job.FilePosition, clone.Job.FilePosition);
            Assert.AreNotSame(original.Job.LastFileName, clone.Job.LastFileName);
            Assert.AreNotSame(original.Job.LastFileSimulated, clone.Job.LastFileSimulated);
            Assert.AreNotSame(original.Job.Layer, clone.Job.Layer);

            Assert.AreNotSame(1, original.Job.Layers.Count);
            Assert.AreNotSame(original.Job.Layers[0].Duration, clone.Job.Layers[0].Duration);
            Assert.AreNotSame(original.Job.Layers[0].Filament, clone.Job.Layers[0].Filament);
            Assert.AreNotSame(original.Job.Layers[0].FractionPrinted, clone.Job.Layers[0].FractionPrinted);
            Assert.AreNotSame(original.Job.Layers[0].Height, clone.Job.Layers[0].Height);

            Assert.AreNotSame(original.Job.LayerTime, clone.Job.LayerTime);
            Assert.AreNotSame(original.Job.TimesLeft.Filament, clone.Job.TimesLeft.Filament);
            Assert.AreNotSame(original.Job.TimesLeft.File, clone.Job.TimesLeft.File);
            Assert.AreNotSame(original.Job.TimesLeft.Layer, clone.Job.TimesLeft.Layer);
            Assert.AreNotSame(original.Job.WarmUpDuration, clone.Job.WarmUpDuration);
        }

        [Test]
        public void Assign()
        {
            MachineModel original = new MachineModel();

            original.Job.Duration = 123;
            original.Job.ExtrudedRaw.Add(123F);
            original.Job.ExtrudedRaw.Add(456F);
            original.Job.ExtrudedRaw.Add(789F);
            original.Job.File.Filament.Add(321F);
            original.Job.File.Filament.Add(654F);
            original.Job.File.Filament.Add(987F);
            original.Job.File.GeneratedBy = "Generated by";
            original.Job.File.Height = 57;
            original.Job.File.LayerHeight = 0.43F;
            original.Job.File.FileName = "0:/gcodes/somefile.g";
            original.Job.File.NumLayers = 467;
            original.Job.File.PrintTime = 4566;
            original.Job.File.SimulatedTime = 7964;
            original.Job.File.Size = 4645645;
            original.Job.FilePosition = 32423;
            original.Job.LastFileName = "0:/gcodes/lastfile.g";
            original.Job.LastFileSimulated = true;
            original.Job.Layer = 4;

            original.Job.Layers.Add(new Layer
            {
                Duration = 23,
                Filament = new float[] { 12F, 34F, 56F },
                FractionPrinted = 0.012F,
                Height = 0.33F
            });

            original.Job.LayerTime = 4.3F;
            original.Job.TimesLeft.Filament = 1234;
            original.Job.TimesLeft.File = 234;
            original.Job.TimesLeft.Layer = 345;
            original.Job.WarmUpDuration = 34;

            MachineModel assigned = new MachineModel();
            assigned.Assign(original);

            Assert.AreEqual(original.Job.Duration, assigned.Job.Duration);
            Assert.AreEqual(original.Job.ExtrudedRaw, assigned.Job.ExtrudedRaw);
            Assert.AreEqual(original.Job.File.Filament, assigned.Job.File.Filament);
            Assert.AreEqual(original.Job.File.GeneratedBy, assigned.Job.File.GeneratedBy);
            Assert.AreEqual(original.Job.File.Height, assigned.Job.File.Height);
            Assert.AreEqual(original.Job.File.LayerHeight, assigned.Job.File.LayerHeight);
            Assert.AreEqual(original.Job.File.FileName, assigned.Job.File.FileName);
            Assert.AreEqual(original.Job.File.NumLayers, assigned.Job.File.NumLayers);
            Assert.AreEqual(original.Job.File.PrintTime, assigned.Job.File.PrintTime);
            Assert.AreEqual(original.Job.File.SimulatedTime, assigned.Job.File.SimulatedTime);
            Assert.AreEqual(original.Job.File.Size, assigned.Job.File.Size);
            Assert.AreEqual(original.Job.FilePosition, assigned.Job.FilePosition);
            Assert.AreEqual(original.Job.LastFileName, assigned.Job.LastFileName);
            Assert.AreEqual(original.Job.LastFileSimulated, assigned.Job.LastFileSimulated);
            Assert.AreEqual(original.Job.Layer, assigned.Job.Layer);

            Assert.AreEqual(1, original.Job.Layers.Count);
            Assert.AreEqual(original.Job.Layers[0].Duration, assigned.Job.Layers[0].Duration);
            Assert.AreEqual(original.Job.Layers[0].Filament, assigned.Job.Layers[0].Filament);
            Assert.AreEqual(original.Job.Layers[0].FractionPrinted, assigned.Job.Layers[0].FractionPrinted);
            Assert.AreEqual(original.Job.Layers[0].Height, assigned.Job.Layers[0].Height);

            Assert.AreEqual(original.Job.LayerTime, assigned.Job.LayerTime);
            Assert.AreEqual(original.Job.TimesLeft.Filament, assigned.Job.TimesLeft.Filament);
            Assert.AreEqual(original.Job.TimesLeft.File, assigned.Job.TimesLeft.File);
            Assert.AreEqual(original.Job.TimesLeft.Layer, assigned.Job.TimesLeft.Layer);
            Assert.AreEqual(original.Job.WarmUpDuration, assigned.Job.WarmUpDuration);

            Assert.AreNotSame(original.Job.Duration, assigned.Job.Duration);
            Assert.AreNotSame(original.Job.ExtrudedRaw, assigned.Job.ExtrudedRaw);
            Assert.AreNotSame(original.Job.File.Filament, assigned.Job.File.Filament);
            Assert.AreNotSame(original.Job.File.GeneratedBy, assigned.Job.File.GeneratedBy);
            Assert.AreNotSame(original.Job.File.Height, assigned.Job.File.Height);
            Assert.AreNotSame(original.Job.File.LayerHeight, assigned.Job.File.LayerHeight);
            Assert.AreNotSame(original.Job.File.FileName, assigned.Job.File.FileName);
            Assert.AreNotSame(original.Job.File.NumLayers, assigned.Job.File.NumLayers);
            Assert.AreNotSame(original.Job.File.PrintTime, assigned.Job.File.PrintTime);
            Assert.AreNotSame(original.Job.File.SimulatedTime, assigned.Job.File.SimulatedTime);
            Assert.AreNotSame(original.Job.File.Size, assigned.Job.File.Size);
            Assert.AreNotSame(original.Job.FilePosition, assigned.Job.FilePosition);
            Assert.AreNotSame(original.Job.LastFileName, assigned.Job.LastFileName);
            Assert.AreNotSame(original.Job.LastFileSimulated, assigned.Job.LastFileSimulated);
            Assert.AreNotSame(original.Job.Layer, assigned.Job.Layer);

            Assert.AreNotSame(1, original.Job.Layers.Count);
            Assert.AreNotSame(original.Job.Layers[0].Duration, assigned.Job.Layers[0].Duration);
            Assert.AreNotSame(original.Job.Layers[0].Filament, assigned.Job.Layers[0].Filament);
            Assert.AreNotSame(original.Job.Layers[0].FractionPrinted, assigned.Job.Layers[0].FractionPrinted);
            Assert.AreNotSame(original.Job.Layers[0].Height, assigned.Job.Layers[0].Height);

            Assert.AreNotSame(original.Job.LayerTime, assigned.Job.LayerTime);
            Assert.AreNotSame(original.Job.TimesLeft.Filament, assigned.Job.TimesLeft.Filament);
            Assert.AreNotSame(original.Job.TimesLeft.File, assigned.Job.TimesLeft.File);
            Assert.AreNotSame(original.Job.TimesLeft.Layer, assigned.Job.TimesLeft.Layer);
            Assert.AreNotSame(original.Job.WarmUpDuration, assigned.Job.WarmUpDuration);
        }
    }
}
