using System.Globalization;
using System.IO;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using DuetAPI.ObjectModel;
using NUnit.Framework;
using NUnit.Framework.Legacy;

namespace UnitTests.File
{
    [TestFixture]
    public class InfoParser
    {
        [Test]
        [TestCase("Cura.gcode")]
        [TestCase("PrusaSlicer.gcode")]
        [TestCase("Simplify3D.gcode")]
        [TestCase("Slic3r.gcode")]
        public async Task Test(string fileName)
        {
            string filePath = System.IO.Path.Combine(Directory.GetCurrentDirectory(), "../../../File/GCodes", fileName);
            GCodeFileInfo info = await DuetControlServer.Files.InfoParser.Parse(filePath, true);

            TestContext.Out.Write(JsonSerializer.Serialize(info, typeof(GCodeFileInfo), new JsonSerializerOptions { WriteIndented = true }));

            ClassicAssert.IsNotNull(info.FileName);
            ClassicAssert.AreNotEqual(0, info.Size);
            ClassicAssert.AreNotEqual(0, info.Height);
            ClassicAssert.AreNotEqual(0, info.LayerHeight);
            ClassicAssert.AreNotEqual(0, info.NumLayers);
            ClassicAssert.AreNotEqual(0, info.Filament.Count);
            ClassicAssert.IsNotEmpty(info.GeneratedBy);
            // ClassicAssert.AreNotEqual(0, info.PrintTime);
            // ClassicAssert.AreNotEqual(0, info.SimulatedTime);
        }

        [TestCase("Thumbnail.gcode", 2)]
        [TestCase("Thumbnail_JPG.gcode", 1)]
        [TestCase("Thumbnail_QOI.gcode", 2)]
        [TestCase("BenchyIcon.gcode", 1)]
        public async Task TestThumbnails(string fileName, int thumbnailCount)
        {
            string filePath = System.IO.Path.Combine(Directory.GetCurrentDirectory(), "../../../File/GCodes", fileName);
            GCodeFileInfo info = await DuetControlServer.Files.InfoParser.Parse(filePath, true);
            TestContext.Out.Write(JsonSerializer.Serialize(info, typeof(GCodeFileInfo), new JsonSerializerOptions { WriteIndented = true }));
            ClassicAssert.AreEqual(info.Thumbnails.Count, thumbnailCount);
        }

        [TestCase("Thumbnail.gcode")]
        public async Task TestThumbnailResponse(string fileName)
        {
            string filePath = System.IO.Path.Combine(Directory.GetCurrentDirectory(), "../../../File/GCodes", fileName);
            GCodeFileInfo info = await DuetControlServer.Files.InfoParser.Parse(filePath, true);

            string thumbnailResponse = await DuetControlServer.Files.InfoParser.ParseFileFragment(filePath, info.Thumbnails[0].Offset, true);
            ClassicAssert.IsTrue(thumbnailResponse.Contains(info.Thumbnails[0].Data![..1024]));

            TestContext.Out.Write(thumbnailResponse);
        }

        [Test]
        public async Task TestEmpty()
        {
            string filePath = System.IO.Path.Combine(Directory.GetCurrentDirectory(), "../../../File/GCodes/Circle.gcode");
            GCodeFileInfo info = await DuetControlServer.Files.InfoParser.Parse(filePath, true);

            TestContext.Out.Write(JsonSerializer.Serialize(info, typeof(GCodeFileInfo), new JsonSerializerOptions { WriteIndented = true }));

            ClassicAssert.IsNotNull(info.FileName);
            ClassicAssert.AreNotEqual(0, info.Size);
            ClassicAssert.AreEqual(0.5, info.Height);
            ClassicAssert.AreEqual(0, info.LayerHeight);
            ClassicAssert.AreEqual(0, info.Filament.Count);
            ClassicAssert.IsNull(info.GeneratedBy);
            ClassicAssert.IsNull(info.PrintTime);
            ClassicAssert.IsNull(info.SimulatedTime);
        }

        /// <summary>
        /// Write a synthetic job file with 100 layers of 0.2mm whose last layer is bigger than the footer read limit and ends without a Z move
        /// </summary>
        private static async Task<string> WriteSyntheticJobAsync(string name, string header, string footer)
        {
            StringBuilder builder = new(header);
            builder.Append("G90\nM83\nG28\n");
            for (int layer = 1; layer <= 100; layer++)
            {
                builder.Append(CultureInfo.InvariantCulture, $";LAYER_CHANGE\n;Z:{layer * 0.2:F2}\n;HEIGHT:0.2\nG1 Z{layer * 0.2:F2} F600\n");
                int numMoves = (layer < 100) ? 20 : 16384;
                for (int move = 0; move < numMoves; move++)
                {
                    builder.Append(CultureInfo.InvariantCulture, $"G1 X{move % 300}.123 Y{(move * 7) % 300}.456 E0.01234\n");
                }
            }
            builder.Append("M98 P\"0:/sys/print_end\"\n");
            builder.Append(footer);

            string filePath = System.IO.Path.Combine(System.IO.Path.GetTempPath(), name);
            await System.IO.File.WriteAllTextAsync(filePath, builder.ToString());
            return filePath;
        }

        [TestCase("OrcaSlicer", "; generated by OrcaSlicer 2.3.0 on 2026-09-04\n; max_z_height: 20.00\n; total layer number: 100\n; layer_height = 0.2\n; filament used [mm] = 1234.5\n")]
        [TestCase("Cura", ";FLAVOR:RepRap\n;Filament used: 1.2345m\n;Layer height: 0.2\n;MAXZ:20\n;Generated with Cura_SteamEngine 5.10.0\n;LAYER_COUNT:100\n")]
        [TestCase("Fusion360", ";Generated by Fusion 360\n;Height: 20mm\n;Layer height: 0.2\n;Filament used: 1.2345m\n;NUM_LAYERS: 100\n")]
        public async Task TestHeightFromHeaderComment(string slicer, string header)
        {
            string filePath = await WriteSyntheticJobAsync($"{slicer}_BigLastLayer.gcode", header, string.Empty);
            GCodeFileInfo info = await DuetControlServer.Files.InfoParser.Parse(filePath, false);

            Assert.That(info.Size, Is.GreaterThan(DuetControlServer.Settings.FileInfoReadLimitFooter));
            Assert.That(info.Height, Is.EqualTo(20).Within(0.001));
            Assert.That(info.LayerHeight, Is.EqualTo(0.2).Within(0.001));
            Assert.That(info.NumLayers, Is.EqualTo(100));
        }

        [Test]
        public async Task TestHeightFromFooterCommentOverridesLastZMove()
        {
            string filePath = await WriteSyntheticJobAsync("FooterHeightComment.gcode", "; generated by OrcaSlicer 2.3.0 on 2026-09-04\n; layer_height = 0.2\n; filament used [mm] = 1234.5\n", "; max_z_height: 20.00\nG1 Z25 F600\n");
            GCodeFileInfo info = await DuetControlServer.Files.InfoParser.Parse(filePath, false);

            Assert.That(info.Height, Is.EqualTo(20).Within(0.001));
            Assert.That(info.NumLayers, Is.EqualTo(100));
        }

        [Test]
        public async Task TestPerLayerHeightCommentsAreIgnored()
        {
            string filePath = await WriteSyntheticJobAsync("PrusaSlicer_LayerComments.gcode", "; generated by PrusaSlicer 2.9.0 on 2026-09-04\n; layer_height = 0.2\n; filament used [mm] = 1234.5\n", "G1 Z25 F600\n; max_layer_height = 0.25\n; max_print_height = 250\n");
            GCodeFileInfo info = await DuetControlServer.Files.InfoParser.Parse(filePath, false);

            Assert.That(info.Height, Is.EqualTo(25).Within(0.001));
        }
    }
}
