#!/bin/sh

# Instruct DuetControlServer to update the firmware.
# Do this only if GPIO and SPI devices are available
GPIOCHIP_DEVICES=ls /dev/gpiochip 2>/dev/null
SPI_DEVICES=ls /dev/spidev 2>/dev/null
[ ! -z $GPIPCHIP_DEVICES ] && [ ! -z $SPI_DEVICES ] && /opt/dsf/bin/DuetControlServer -u
exit 0
