// <auto-generated>
//     Generated by tools/CanMessageGenerator from Schema/can-messages.json.
//     Do not edit this file directly: edit the schema and re-run the generator, otherwise
//     these values will drift away from CANlib's CanId.h, which nothing else would catch.
// </auto-generated>

namespace DuetControlServer.Link.Protocol.Shared;

/// <summary>
/// CAN addresses and the layout of a CAN id, mirroring the CanId class in CANlib's CanId.h.
/// DCS builds no CAN ids itself — the native link does — but the addresses decide who a message
/// is for, and they were previously only written down in a doc comment.
/// </summary>
public static class CanId
{
    /// <summary>main boards (except ATE main boards) have address 0</summary>
    public const byte MasterAddress = 0;

    public const byte ATECMBoardFirstAddress = 90;

    public const byte ATEIOBoardFirstAddress = 95;

    public const byte ATECMBoardDefaultAddress = 118;

    public const byte ATEIOBoardDefaultAddress = 119;

    public const byte SZPDefaultAddress = 120;

    /// <summary>default address for tool boards</summary>
    public const byte ToolBoardDefaultAddress = 121;

    public const byte Exp1XDBoardDefaultAddress = 122;

    public const byte Exp1HCLBoardDefaultAddress = 123;

    public const byte SammyC21DefaultAddress = 124;

    /// <summary>the address of the ATE main board</summary>
    public const byte ATEMasterAddress = 125;

    /// <summary>special address we use for backup firmware update system (board ID switches set to zero on 3HC)</summary>
    public const byte Exp3HCFirmwareUpdateAddress = 126;

    /// <summary>maximum CAN address including the firmware update address</summary>
    public const byte MaxCanAddress = 126;

    public const byte BroadcastAddress = 127;

    public const byte NoAddress = 255;

    public const uint BoardAddressMask = 0x7F;

    public const uint DstAddressShift = 0;

    public const uint SrcAddressShift = 8;

    public const uint ResponseBit = 1u << 15;

    public const uint MessageTypeShift = 16;

    public const uint MessageTypeMask = 0x1FFF;
}
