// <auto-generated>
//     Generated by src/DuetCanMessage.SourceGenerators from Schema/can-messages.json.
//     Do not edit this file directly: edit the schema and re-run the generator, otherwise
//     these values will drift away from CANlib's CanId.h, which nothing else would catch.
// </auto-generated>

namespace DuetControlServer.Link.Protocol.Shared;

/// <summary>
/// Type of a CAN message, which identifies it in the CAN id.
/// Mirrors the CanMessageType enum in CANlib's CanId.h. A retired id is kept as a comment so that
/// it is never reused: an expansion board running older firmware would still act on it.
/// </summary>
public enum CanMessageType : ushort
{

    // High-priority requests sent by the main board
    EmergencyStop = 0,
    Startup = 10,
    ControlledStop = 20,
    TimeSync = 30,
    PowerFailing = 40,
    StopMovement = 45,
    InsertHiccup = 46,
    RevertPosition = 47,
    // UnusedWasMovement = 50,
    // UnusedWasMovementLinear = 51,
    MovementLinearShaped = 52,

    // High priority responses sent by expansion boards and Smart Tools
    // UnusedWasInputStateChangedV0 = 100,
    Event = 102,
    /// <summary>sent by the ATE to the main board</summary>
    EnterTestMode = 104,
    InputStateChangedV1 = 105,
    InputStateChangedV2 = 106,

    // Configuration messages sent by the main board
    SetAddressAndNormalTiming = 2010,
    SetFastTiming = 2011,
    Reset = 2012,

    // Medium priority messages sent by the main board
    WriteGpio = 4012,
    ReadInputsRequest = 4013,
    StartAccelerometer = 4014,
    StartClosedLoopDataCollection = 4015,

    // Configuration messages sent by the main board
    // UnusedWasM950 = 6010,
    // UnusedWasM308 = 6011,
    // UnusedWasUpdateHeaterModelV0 = 6012,

    // unused was setHeaterTemperatureV0 = 6013,
    // UnusedWasSetPressureAdvanceV0 = 6014,
    SetDateTime = 6015,
    UpdateDeltaParameters = 6016,
    // UnusedWasSetMotorCurrents = 6017,
    M569 = 6018,
    FanParameters = 6019,
    M915 = 6020,
    // UnusedWasSetMicrostepping = 6021,
    // UnusedWasSetStandstillCurrentFactor = 6022,
    SetDriverStates = 6023,
    ReturnInfo = 6024,
    UpdateFirmware = 6025,
    M950Heater = 6026,
    M950Fan = 6027,
    M950Gpio = 6028,
    SetFanSpeed = 6029,
    SetHeaterFaultDetection = 6030,
    M308V1 = 6031,
    HeaterTuningCommand = 6032,
    // UnusedWasHeaterFeedForward = 6033,
    AccelerometerConfig = 6034,
    M950Led = 6035,
    // UnusedWasCreateInputMonitorV0 = 6036,
    // UnusedWasChangeInputMonitorV0 = 6037,
    AcknowledgeAnnounce = 6038,
    SetHeaterMonitors = 6039,
    DiagnosticTest = 6040,
    M569P1 = 6041,
    SetStepsPerMmAndMicrostepping = 6042,
    SetMotorCurrents = 6043,
    SetPressureAdvanceV1 = 6044,
    SetStandstillCurrentFactor = 6045,
    CreateFilamentMonitor = 6046,
    DeleteFilamentMonitor = 6047,
    ConfigureFilamentMonitor = 6048,
    // UnusedWasUpdateHeaterModelV1 = 6049,
    M569P2 = 6050,
    M569P6 = 6051,
    M569P7 = 6052,
    // UnusedWasHeaterModelV2 = 6053,
    // UnusedWasSetInputShaping = 6054,
    WriteLedStrip = 6055,
    M569P4 = 6056,

    // In RRF 3.5.0rc3 the message sent to report an input monitor state change has changed.

    // To prevent users successfully configuring endstops on remote boards which then don't work, we have changed the IDs of createInputMonitorV1 and changeInputMonitorV1.

    // With luck this will abort any moves involving endstops with "Failed to enable endstops".
    // UnusedWasCreateInputMonitorV1 = 6057,
    // UnusedWasChangeInputMonitorV1 = 6058,
    TestReport = 6059,
    /// <summary>was 6057 before 3.5.0-rc.3</summary>
    CreateInputMonitorV1 = 6060,

    /// <summary>was 6058 before 3.5.0-rc.3</summary>
    ChangeInputMonitorV1 = 6061,
    SetInputShapingV1 = 6062,
    HeaterFeedForwardV1 = 6063,
    /// <summary>for M655, added in RRF 3.6</summary>
    M655 = 6064,
    EnableStallEndstop = 6065,
    M111 = 6066,
    /// <summary>added in RRF 3.7</summary>
    SetDefaultHeaterModel = 6067,

    /// <summary>added in RRF 3.7</summary>
    SetHeaterTemperatureV1 = 6068,

    /// <summary>added in RRF 3.7</summary>
    HeaterModelV3 = 6069,
    SetPressureAdvanceV2 = 6070,
    /// <summary>for M959, added in RRF 3.7</summary>
    SetConnectionTimeout = 6071,

    // Responses, broadcasts etc. sent by expansion boards
    StandardReply = 4510,
    BoardStatusReportV0 = 4511,
    /// <summary>announce message sent by firmware 3.4.0beta4 and earlier</summary>
    AnnounceV0 = 4512,

    // fanTachoReport = 4513,					// unused
    SensorTemperaturesReport = 4514,
    HeatersStatusReport = 4515,

    // unused_was_fansRpmReport = 4516,			// replaced by fansReport
    FansReport = 4517,
    ReadInputsReplyV0 = 4518,
    DriversStatusReport = 4519,
    // UnusedWasFilamentMonitorsStatusReportV0 = 4520,
    HeaterTuningReport = 4521,
    AccelerometerData = 4522,
    ClosedLoopData = 4523,
    LogMessage = 4524,
    /// <summary>announce message sent by firmware 3.4.0beta5 and later</summary>
    AnnounceV1 = 4525,
    DebugText = 4526,
    // UnusedWasFilamentMonitorsStatusReportV1 = 4527,
    FilamentMonitorsStatusReportV2 = 4528,
    ReadInputsReplyV1 = 4529,
    BoardStatusReportV1 = 4530,
    /// <summary>added in firmware 3.7</summary>
    HeaterModelReport = 4531,

    // Firmware updates
    FirmwareBlockRequest = 5000,
    FirmwareBlockResponse = 5001,
    UnusedMessageType = 0xFFFF,
    /// <summary>Alias used as the ReplyType of a CAN request when no reply is expected</summary>
    NoReply = UnusedMessageType,
}
