// <auto-generated>
//     Generated by src/DuetCanMessage.SourceGenerators from Schema/can-messages.json.
//     Do not edit this file directly: edit the schema and re-run the generator, otherwise
//     these values will drift away from CANlib's RRF3Common.h, which nothing else would catch.
// </auto-generated>

namespace DuetControlServer.Link.Protocol.Shared;

/// <summary>
/// What a heater is for, which decides the minimum temperature rise that does not count as a fault.
/// Mirrors HeaterFunction in CANlib's RRF3Common.h. The value travels on the wire as the 3-bit
/// heaterFunction of a set-default-heater-model request, so it has to keep CANlib's numbering.
/// </summary>
public enum HeaterFunction : byte
{
    /// <summary>a tool heater, which is expected to heat up quickly</summary>
    Tool = 0,

    /// <summary>a bed heater, which is allowed to heat up more slowly than a tool heater</summary>
    Bed = 1,

    /// <summary>a chamber heater, which is allowed to heat up more slowly still</summary>
    Chamber = 2,

    /// <summary>not a function, but how many there are</summary>
    NumValues = 3,
}
