// <auto-generated>
//     Generated by src/DuetCanMessage.SourceGenerators from Schema/can-messages.json.
//     Do not edit this file directly: edit the schema and re-run the generator, otherwise
//     these values will drift away from CANlib's RRF3Common.h, which nothing else would catch.
// </auto-generated>

namespace DuetControlServer.Link.Protocol.Shared;

/// <summary>
/// What a heater is doing, as reported by the board that owns it.
/// Mirrors HeaterMode in CANlib's RRF3Common.h. The value travels on the wire as the mode of a heater
/// report, so it has to keep CANlib's numbering. The order matters beyond the individual values:
/// the firmware tests mode &gt; suspended to decide whether a heater is active, mode &gt;= off to decide
/// whether it is active or suspended, and the tuning states must stay last.
/// </summary>
public enum HeaterMode : byte
{
    /// <summary>the heater has been shut down because a fault was detected</summary>
    Fault = 0,

    /// <summary>the board that owns the heater is not responding</summary>
    Offline = 1,

    /// <summary>the heater is configured but switched off</summary>
    Off = 2,

    /// <summary>the heater has been switched off temporarily, e.g. while a tool change or a filament change is in progress</summary>
    Suspended = 3,

    /// <summary>the first of the three modes the PID controller uses</summary>
    Cooling = 4,

    /// <summary>the temperature is within the allowed band around the setpoint</summary>
    Stable = 5,

    /// <summary>the temperature is below the allowed band around the setpoint</summary>
    Heating = 6,

    /// <summary>not a mode, but the lowest of the three modes the PID controller uses</summary>
    FirstPidMode = Cooling,

    /// <summary>not a mode, but the highest of the three modes the PID controller uses</summary>
    LastPidMode = Heating,

    /// <summary>waiting for the temperature to settle before tuning starts</summary>
    Tuning0Settling = 7,

    /// <summary>calibrating the heater itself, which only inductive heaters need</summary>
    Tuning0aCalibratingHeater = 8,

    /// <summary>heating up to the upper tuning temperature for the first time</summary>
    Tuning1HeatingUp = 9,

    /// <summary>heater off, measuring how fast the temperature falls</summary>
    Tuning2HeaterOff = 10,

    /// <summary>heater on, measuring how fast the temperature rises</summary>
    Tuning3HeaterOn = 11,

    /// <summary>not a mode, but the first of the tuning states</summary>
    FirstTuningMode = Tuning0Settling,

    /// <summary>not a mode, but the last of the tuning states</summary>
    LastTuningMode = Tuning3HeaterOn,
}
