// <auto-generated>
//     Generated by src/DuetCanMessage.SourceGenerators from Schema/can-messages.json.
//     Do not edit this file directly: edit the schema and re-run the generator, otherwise
//     these values will drift away from CANlib's RRF3Common.h, which nothing else would catch.
// </auto-generated>

namespace DuetControlServer.Link.Protocol.Shared;

/// <summary>
/// What a heater is doing, as reported by the board that owns it.
/// Mirrors HeaterMode in CANlib's RRF3Common.h. The value travels on the wire as the mode of a heater
/// report, so it has to keep CANlib's numbering. The order matters beyond the individual values:
/// the firmware tests mode &gt; suspended to decide whether a heater is active, mode &gt;= off to decide
/// whether it is active or suspended, and the tuning states must stay last.
/// </summary>
public enum HeaterMode : byte
{
    Fault = 0,
    Offline = 1,
    Off = 2,
    Suspended = 3,
    /// <summary>the first of the three modes the PID controller uses</summary>
    Cooling = 4,
    Stable = 5,
    Heating = 6,
    FirstPidMode = Cooling,
    LastPidMode = Heating,
    Tuning0Settling = 7,
    Tuning0aCalibratingHeater = 8,
    Tuning1HeatingUp = 9,
    Tuning2HeaterOff = 10,
    Tuning3HeaterOn = 11,
    FirstTuningMode = Tuning0Settling,
    LastTuningMode = Tuning3HeaterOn,
}
