// <auto-generated>
//     Generated by src/DuetCanMessage.SourceGenerators from Schema/can-messages.json.
//     Do not edit this file directly: edit the schema and re-run the generator, otherwise
//     these values will drift away from CANlib's RRF3Common.h, which nothing else would catch.
// </auto-generated>

namespace DuetControlServer.Link.Protocol.Shared;

/// <summary>
/// Why a heater was shut down, in the parameter of a heater_fault event.
/// Mirrors HeaterFaultType in CANlib's RRF3Common.h. The board that owns the heater decides the
/// value - see Duet3Expansion's LocalHeater - and sends it, so the ordinals have to match.
/// CANlib also carries the text for each of these, but nothing on a board renders it: the text
/// belongs with whoever reports the fault to the operator, which is DuetControlServer.
/// </summary>
public enum HeaterFaultType : byte
{
    /// <summary>the sensor could not be read; the sensor error follows</summary>
    FailedToReadSensor = 0,

    /// <summary>the heater did not heat up as the model said it would</summary>
    TemperatureRisingTooSlowly = 1,

    /// <summary>the temperature strayed further from the target than allowed</summary>
    ExceededAllowedExcursion = 2,

    /// <summary>a heater monitor fired</summary>
    MonitorTriggered = 3,

    /// <summary>the heater needed more power than the model said it should</summary>
    PwmTooHigh = 4,

    /// <summary>an inductive heater reported a load error; the board's message follows</summary>
    InductiveHeaterError = 5,

    /// <summary>not a fault type, but how many there are</summary>
    HeaterFaultTypeLimit = 6,
}
