// <auto-generated>
//     Generated by src/DuetCanMessage.SourceGenerators from Schema/can-messages.json.
//     Do not edit this file directly: edit the schema and re-run the generator, otherwise
//     these values will drift away from CANlib's RRF3Common.h, which nothing else would catch.
// </auto-generated>

namespace DuetControlServer.Link.Protocol.Shared;

/// <summary>
/// The driver status word a board reports, mirroring StandardDriverStatus in CANlib's RRF3Common.h.
/// The lowest 8 bits match the TMC2209 DRV_STATUS register; other drivers are translated to them.
/// Only the lowest 16 bits travel in a driver event message.
/// The bit meanings are here rather than in DuetControlServer because a board renders them too:
/// Duet3Expansion answers a status request with this same text, so one declaration has to serve
/// both or a driver fault reads differently depending on which of them reported it.
/// Each mask says which bits are of that severity; AppendText in CANlib picks by severity and joins
/// the meanings of what is set, or says "ok".
/// </summary>
public static class StandardDriverStatus
{
    /// <summary>over temperature warning</summary>
    public const uint OtpwBitPos = 0;

    /// <summary>over temperature shutdown</summary>
    public const uint OtBitPos = 1;

    /// <summary>first of the two short-to-ground bits</summary>
    public const uint S2gBitsPos = 2;

    /// <summary>first of the two short-to-Vin bits</summary>
    public const uint S2vsBitsPos = 4;

    /// <summary>first of the two open load bits</summary>
    public const uint OpenLoadBitsPos = 6;

    /// <summary>stall</summary>
    public const uint StallBitPos = 8;

    /// <summary>external driver signalled an error</summary>
    public const uint ExternDriverErrorBitPos = 9;

    /// <summary>standstill indicator</summary>
    public const uint StandstillBitPos = 16;

    /// <summary>first bit of the minimum stallguard result</summary>
    public const uint SgresultBitPos = 22;

    /// <summary>bits that usually correspond to errors</summary>
    public const uint ErrorMask = 0x4A3E;

    /// <summary>bits that correspond to warnings</summary>
    public const uint WarningMask = 0x24C1;

    /// <summary>bits that correspond to information</summary>
    public const uint InfoMask = 0x39100;

    /// <summary>bits that correspond to open load</summary>
    public const uint OpenLoadMask = 0xC0;

    /// <summary>What each bit means, in bit order. Rendered by DuetControlServer and by Duet3Expansion alike.</summary>
    public static readonly string[] BitMeanings =
    [
        "over temperature warning",
        "over temperature shutdown",
        "phase A short to ground",
        "phase B short to ground",
        "phase A short to Vin",
        "phase B short to Vin",
        "phase A may be disconnected",
        "phase B may be disconnected",
        "stalled",
        "external driver error",
        "position tolerance exceeded",
        "failed to maintain position",
        "not tuned/calibrated",
        "tuning/calibration failed",
        "move attempted when not tuned/calibrated",
        "unused bit",
        "standstill",
        "not present",
    ];
}
