using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using DuetAPI;
using DuetAPI.Commands;
using Code = DuetControlServer.Commands.Code;

namespace DuetControlServer.FileExecution
{
    /// <summary>
    /// Implementation of a macro file
    /// </summary>
    public class MacroFile : BaseFile
    {
        /// <summary>
        /// Default name of the config file
        /// </summary>
        public static readonly string ConfigFile = "config.g";

        /// <summary>
        /// Fallback file if the config file could not be found
        /// </summary>
        public static readonly string ConfigFileFallback = "config.g.bak";

        /// <summary>
        /// Config override as generated by M500
        /// </summary>
        public static readonly string ConfigOverrideFile = "config-override.g";

        /// <summary>
        /// List of macro files being executed
        /// </summary>
        private static List<MacroFile> _macroFiles = new List<MacroFile>();

        /// <summary>
        /// Abort files on the given channel (probably because the firmware requested this)
        /// </summary>
        /// <param name="channel">Channel on which macros are supposed to be cancelled</param>
        public static void AbortAllFiles(CodeChannel channel)
        {
            lock (_macroFiles)
            {
                foreach (MacroFile file in _macroFiles)
                {
                    if (file.Channel == channel)
                    {
                        file.Abort();
                    }
                }
            }
        }

        /// <summary>
        /// Abort the last file on the given channel
        /// </summary>
        /// <param name="channel">Channel of the running macro file</param>
        /// <returns>If an abortion could be requested</returns>
        public static bool AbortLastFile(CodeChannel channel)
        {
            lock (_macroFiles)
            {
                for (int i = _macroFiles.Count; i >= 0; i--)
                {
                    MacroFile file = _macroFiles[i];
                    if (file.Channel == channel)
                    {
                        file.Abort();
                        return true;
                    }
                }
            }
            return false;
        }

        private readonly bool _isConfig;
        private readonly bool _isConfigOverride;
        private readonly bool _isSystemMacro;
        private bool _sentPush, _sentPop;
        private int _sourceConnection;

        /// <summary>
        /// Create a new macro instance
        /// </summary>
        /// <param name="fileName">Filename of the macro</param>
        /// <param name="channel">Channel to send the codes to</param>
        /// <param name="isSystemMacro">Whether the macro file is requested from the firmware</param>
        /// <param name="sourceConnection">Source connection of this macro</param>
        public MacroFile(string fileName, CodeChannel channel, bool isSystemMacro, int sourceConnection) : base(fileName, channel)
        {
            string name = Path.GetFileName(fileName);
            _isConfig = (name == ConfigFile || name == ConfigFileFallback);
            _isConfigOverride = (name == ConfigOverrideFile);
            _isSystemMacro = isSystemMacro;
            _sourceConnection = sourceConnection;
            lock (_macroFiles)
            {
                _macroFiles.Add(this);
            }
        }

        /// <summary>
        /// Read another code from the file being executed
        /// </summary>
        /// <returns>Next available code or null if the file has ended</returns>
        public override async Task<Code> ReadCode()
        {
            // Push the stack unless the firmware requested this file
            if (!_sentPush && !_isSystemMacro)
            {
                _sentPush = true;
                return new Code
                {
                    Channel = Channel,
                    IsFromMacro = true,
                    SourceConnection = _sourceConnection,
                    Type = CodeType.MCode,
                    MajorNumber = 120
                };
            }

            // Read the next code from the file
            Code result = await base.ReadCode();
            if (result != null)
            {
                result.IsFromConfig = _isConfig;
                result.IsFromConfigOverride = _isConfigOverride;
                result.IsFromMacro = true;
                result.IsFromSystemMacro = _isSystemMacro;
                result.SourceConnection = _sourceConnection;
                return result;
            }

            // Pop the stack before completion
            if (_sentPop && !_isSystemMacro && !isAbortRequested)
            {
                _sentPop = true;
                return new Code
                {
                    Channel = Channel,
                    IsFromMacro = true,
                    SourceConnection = _sourceConnection,
                    Type = CodeType.MCode,
                    MajorNumber = 121
                };
            }

            // Remove reference to this file again
            lock (_macroFiles)
            {
                _macroFiles.Remove(this);
            }
            return null;
        }

        /// <summary>
        /// Execute the full macro file
        /// </summary>
        /// <returns>Results of the execution</returns>
        public async Task<CodeResult> RunMacro()
        {
            CodeResult fullResult = new CodeResult();
            for (Code code = await ReadCode(); code != null; code = await ReadCode())
            {
                CodeResult result = await code.Execute();
                fullResult.AddRange(result);
            }
            return fullResult;
        }
    }
}
