using System;
using System.IO;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using DuetAPI.Commands;
using Microsoft.Extensions.Options;

namespace DuetControlServer.Files;

/// <summary>
/// Class used to provide functions for file path resolution
/// </summary>
public partial class FilePathResolver(Model.ObjectModel model, IOptions<Settings> settings)
{
    /// <summary>
    /// Default name of the config file
    /// </summary>
    public const string ConfigFile = "config.g";

    /// <summary>
    /// Fallback file if the config file could not be found
    /// </summary>
    public const string ConfigFileFallback = "config.g.bak";

    /// <summary>
    /// Config override as generated by M500
    /// </summary>
    public const string ConfigOverrideFile = "config-override.g";

    /// <summary>
    /// Extra config file to be run when DCS + all third-party plugins have been started
    /// </summary>
    public const string DsfConfigFile = "dsf-config.g";

    /// <summary>
    /// File to run once after start if it exists, then deleted again
    /// </summary>
    public const string RunOnceFile = "runonce.g";

    /// <summary>
    /// Regex to obtain a drive number from a RRF-style path
    /// </summary>
    /// <returns></returns>
    [GeneratedRegex(@"^(\d+):/*(.*)")]
    private static partial Regex _generateDriveRegex();

    /// <summary>
    /// Regular expression to extract name and index from a filter item
    /// </summary>
    private static readonly Regex _driveRegex = _generateDriveRegex();

    /// <summary>
    /// Resolve a RepRapFirmware/FatFs-style file path to a physical file path.
    /// The first drive (0:/) is reserved for usage with the base directory as specified in the settings
    /// </summary>
    /// <param name="filePath">File path to resolve</param>
    /// <param name="directory">Directory containing filePath if it is not absolute is specified</param>
    /// <returns>Resolved file path</returns>
    public string ToPhysical(string filePath, FileDirectory directory)
    {
        filePath = filePath.Replace('\\', '/');

        Match match = _driveRegex.Match(filePath);
        if (match.Success && int.TryParse(match.Groups[1].Value, out int driveNumber))
        {
            if (driveNumber == 0)
            {
                return Path.Combine(Path.GetFullPath(settings.Value.BaseDirectory), match.Groups[2].Value);
            }

            using (model.AccessReadOnly())
            {
                if (driveNumber > 0 && driveNumber < model.Volumes.Count)
                {
                    string? path = model.Volumes[driveNumber].Path ?? throw new ArgumentException("Invalid drive index");
                    return Path.Combine(path, match.Groups[2].Value);
                }
            }

            throw new ArgumentException("Invalid drive index");
        }

        if (!filePath.StartsWith('/'))
        {
            string directoryPath;
            using (model.AccessReadOnly())
            {
                directoryPath = directory switch
                {
                    FileDirectory.Filaments => model.Directories.Filaments,
                    FileDirectory.Firmware => model.Directories.Firmware,
                    FileDirectory.GCodes => model.Directories.GCodes,
                    FileDirectory.Macros => model.Directories.Macros,
                    FileDirectory.Menu => model.Directories.Menu,
                    FileDirectory.System => model.Directories.System,
                    FileDirectory.Web => model.Directories.Web,
                    _ => model.Directories.System,
                };

                match = _driveRegex.Match(directoryPath);
                if (match.Success && int.TryParse(match.Groups[1].Value, out driveNumber))
                {
                    if (driveNumber == 0)
                    {
                        directoryPath = Path.Combine(Path.GetFullPath(settings.Value.BaseDirectory), match.Groups[2].Value);
                    }

                    if (driveNumber > 0 && driveNumber < model.Volumes.Count)
                    {
                        string? path = model.Volumes[driveNumber].Path ?? throw new ArgumentException("Invalid drive index");
                        directoryPath = Path.Combine(path, match.Groups[2].Value);
                    }
                }
            }
            return Path.Combine(Path.GetFullPath(settings.Value.BaseDirectory), directoryPath, filePath);
        }
        return Path.Combine(Path.GetFullPath(settings.Value.BaseDirectory), filePath.StartsWith('/') ? filePath[1..] : filePath);
    }

    /// <summary>
    /// Resolve a RepRapFirmware/FatFs-style file path to a physical file path asynchronously.
    /// The first drive (0:/) is reserved for usage with the base directory as specified in the settings
    /// </summary>
    /// <param name="filePath">File path to resolve</param>
    /// <param name="directory">Directory containing filePath if it is not absolute is specified</param>
    /// <param name="cancellationToken">Optional cancellation token</param>
    /// <returns>Resolved file path</returns>
    public async Task<string> ToPhysicalAsync(string filePath, FileDirectory directory, CancellationToken cancellationToken = default)
    {
        filePath = filePath.Replace('\\', '/');

        Match match = _driveRegex.Match(filePath);
        if (match.Success && int.TryParse(match.Groups[1].Value, out int driveNumber))
        {
            if (driveNumber == 0)
            {
                return Path.Combine(Path.GetFullPath(settings.Value.BaseDirectory), match.Groups[2].Value);
            }

            using (await model.AccessReadOnlyAsync(cancellationToken))
            {
                if (driveNumber > 0 && driveNumber < model.Volumes.Count)
                {
                    string? path = model.Volumes[driveNumber].Path ?? throw new ArgumentException("Invalid drive index");
                    return Path.Combine(path, match.Groups[2].Value);
                }
            }

            throw new ArgumentException("Invalid drive index");
        }

        if (!filePath.StartsWith('/'))
        {
            string directoryPath;
            using (await model.AccessReadOnlyAsync(cancellationToken))
            {
                directoryPath = directory switch
                {
                    FileDirectory.Filaments => model.Directories.Filaments,
                    FileDirectory.Firmware => model.Directories.Firmware,
                    FileDirectory.GCodes => model.Directories.GCodes,
                    FileDirectory.Macros => model.Directories.Macros,
                    FileDirectory.Menu => model.Directories.Menu,
                    FileDirectory.System => model.Directories.System,
                    FileDirectory.Web => model.Directories.Web,
                    _ => model.Directories.System,
                };

                match = _driveRegex.Match(directoryPath);
                if (match.Success && int.TryParse(match.Groups[1].Value, out driveNumber))
                {
                    if (driveNumber == 0)
                    {
                        directoryPath = Path.Combine(Path.GetFullPath(settings.Value.BaseDirectory), match.Groups[2].Value);
                    }

                    if (driveNumber > 0 && driveNumber < model.Volumes.Count)
                    {
                        string? path = model.Volumes[driveNumber].Path ?? throw new ArgumentException("Invalid drive index");
                        directoryPath = Path.Combine(path, match.Groups[2].Value);
                    }
                }
            }
            return Path.Combine(Path.GetFullPath(settings.Value.BaseDirectory), directoryPath, filePath);
        }
        return Path.Combine(Path.GetFullPath(settings.Value.BaseDirectory), filePath.StartsWith('/') ? filePath[1..] : filePath);
    }

    /// <summary>
    /// Resolve a RepRapFirmware/FatFs-style file path to a physical file path.
    /// The first drive (0:/) is reserved for usage with the base directory as specified in the settings.
    /// </summary>
    /// <param name="filePath">File path to resolve</param>
    /// <param name="directory">Directory containing filePath if it is not absolute is specified</param>
    /// <returns>Resolved file path</returns>
    public string ToPhysical(string filePath, string? directory = null)
    {
        filePath = filePath.Replace('\\', '/');

        Match match = _driveRegex.Match(filePath);
        if (match.Success && int.TryParse(match.Groups[1].Value, out int driveNumber))
        {
            if (driveNumber == 0)
            {
                return Path.Combine(Path.GetFullPath(settings.Value.BaseDirectory), match.Groups[2].Value);
            }

            using (model.AccessReadOnly())
            {
                if (driveNumber > 0 && driveNumber < model.Volumes.Count)
                {
                    string? path = model.Volumes[driveNumber].Path ?? throw new ArgumentException("Invalid drive index");
                    return Path.Combine(path, match.Groups[2].Value);
                }
            }

            throw new ArgumentException("Invalid drive index");
        }

        if (directory is not null && !filePath.StartsWith('/'))
        {
            match = _driveRegex.Match(directory);
            if (match.Success && int.TryParse(match.Groups[1].Value, out driveNumber))
            {
                if (driveNumber == 0)
                {
                    directory = Path.Combine(Path.GetFullPath(settings.Value.BaseDirectory), match.Groups[2].Value);
                }

                using (model.AccessReadOnly())
                {
                    if (driveNumber > 0 && driveNumber < model.Volumes.Count)
                    {
                        string? path = model.Volumes[driveNumber].Path ?? throw new ArgumentException("Invalid drive index");
                        directory = Path.Combine(path, match.Groups[2].Value);
                    }
                }
            }

            return Path.Combine(Path.GetFullPath(settings.Value.BaseDirectory), directory, filePath);
        }
        return Path.Combine(Path.GetFullPath(settings.Value.BaseDirectory), filePath.StartsWith('/') ? filePath[1..] : filePath);
    }

    /// <summary>
    /// Resolve a RepRapFirmware/FatFs-style file path to a physical file path asynchronously.
    /// The first drive (0:/) is reserved for usage with the base directory as specified in the settings.
    /// </summary>
    /// <param name="filePath">File path to resolve</param>
    /// <param name="directory">Directory containing filePath if it is not absolute is specified</param>
    /// <param name="cancellationToken">Optional cancellation token</param>
    /// <returns>Resolved file path</returns>
    public async Task<string> ToPhysicalAsync(string filePath, string? directory = null, CancellationToken cancellationToken = default)
    {
        filePath = filePath.Replace('\\', '/');

        Match match = _driveRegex.Match(filePath);
        if (match.Success && int.TryParse(match.Groups[1].Value, out int driveNumber))
        {
            if (driveNumber == 0)
            {
                return Path.Combine(Path.GetFullPath(settings.Value.BaseDirectory), match.Groups[2].Value);
            }

            using (await model.AccessReadOnlyAsync(cancellationToken))
            {
                if (driveNumber > 0 && driveNumber < model.Volumes.Count)
                {
                    string? path = model.Volumes[driveNumber].Path ?? throw new ArgumentException("Invalid drive index");
                    return Path.Combine(path, match.Groups[2].Value);
                }
            }

            throw new ArgumentException("Invalid drive index");
        }

        if (directory is not null && !filePath.StartsWith('/'))
        {
            match = _driveRegex.Match(directory);
            if (match.Success && int.TryParse(match.Groups[1].Value, out driveNumber))
            {
                if (driveNumber == 0)
                {
                    directory = Path.Combine(Path.GetFullPath(settings.Value.BaseDirectory), match.Groups[2].Value);
                }

                using (await model.AccessReadOnlyAsync(cancellationToken))
                {
                    if (driveNumber > 0 && driveNumber < model.Volumes.Count)
                    {
                        string? path = model.Volumes[driveNumber].Path ?? throw new ArgumentException("Invalid drive index");
                        directory = Path.Combine(path, match.Groups[2].Value);
                    }
                }
            }

            return Path.Combine(Path.GetFullPath(settings.Value.BaseDirectory), directory, filePath);
        }
        return Path.Combine(Path.GetFullPath(settings.Value.BaseDirectory), filePath.StartsWith('/') ? filePath[1..] : filePath);
    }

    /// <summary>
    /// Convert a physical ile path to a RRF-style file path.
    /// The first drive (0:/) is reserved for usage with the base directory as specified in the settings.
    /// </summary>
    /// <param name="filePath">File path to convert</param>
    /// <returns>Resolved file path</returns>
    public string ToVirtual(string filePath)
    {
        if (filePath.StartsWith(settings.Value.BaseDirectory))
        {
            filePath = filePath[(settings.Value.BaseDirectory.EndsWith('/') ? settings.Value.BaseDirectory.Length : (settings.Value.BaseDirectory.Length + 1))..];
            return Path.Combine("0:/", filePath);
        }

        using (model.AccessReadOnly())
        {
            for (int i = 1; i < model.Volumes.Count; i++)
            {
                string? path = model.Volumes[i].Path;
                if (path is not null && filePath.StartsWith(path))
                {
                    return Path.Combine($"{i}:/", filePath[path.Length..]);
                }
            }
        }

        // Use default first volume as fallback
        return Path.Combine("0:/", filePath);
    }

    /// <summary>
    /// Convert a physical ile path to a RRF-style file path asynchronously.
    /// The first drive (0:/) is reserved for usage with the base directory as specified in the settings.
    /// </summary>
    /// <param name="filePath">File path to convert</param>
    /// <param name="cancellationToken">Optional cancellation token</param>
    /// <returns>Resolved file path</returns>
    public async Task<string> ToVirtualAsync(string filePath, CancellationToken cancellationToken = default)
    {
        if (filePath.StartsWith(settings.Value.BaseDirectory))
        {
            filePath = filePath[(settings.Value.BaseDirectory.EndsWith('/') ? settings.Value.BaseDirectory.Length : (settings.Value.BaseDirectory.Length + 1))..];
            return Path.Combine("0:/", filePath);
        }

        using (await model.AccessReadOnlyAsync(cancellationToken))
        {
            for (int i = 1; i < model.Volumes.Count; i++)
            {
                string? path = model.Volumes[i].Path;
                if (path is not null && filePath.StartsWith(path))
                {
                    return Path.Combine($"{i}:/", filePath[path.Length..]);
                }
            }
        }

        // Use default first volume as fallback
        return Path.Combine("0:/", filePath);
    }
}
