using System;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using DuetAPI.Commands;
using Microsoft.Extensions.Options;

namespace DuetControlServer.Files;

/// <summary>
/// Class used to provide functions for file path resolution
/// </summary>
public partial class FilePathResolver(Model.ObjectModel model, IOptions<Settings> settings)
{
    /// <summary>
    /// Default name of the config file
    /// </summary>
    public const string ConfigFile = "config.g";

    /// <summary>
    /// Fallback file if the config file could not be found
    /// </summary>
    public const string ConfigFileFallback = "config.g.bak";

    /// <summary>
    /// Config override as generated by M500
    /// </summary>
    public const string ConfigOverrideFile = "config-override.g";

    /// <summary>
    /// Extra config file to be run when DCS + all third-party plugins have been started
    /// </summary>
    public const string DsfConfigFile = "dsf-config.g";

    /// <summary>
    /// File to run once after start if it exists, then deleted again
    /// </summary>
    public const string RunOnceFile = "runonce.g";

    /// <summary>
    /// Regex to obtain a drive number from a RRF-style path
    /// </summary>
    /// <returns></returns>
    [GeneratedRegex(@"^(\d+):/*(.*)")]
    private static partial Regex _generateDriveRegex();

    /// <summary>
    /// Regular expression to extract name and index from a filter item
    /// </summary>
    private static readonly Regex _driveRegex = _generateDriveRegex();

    /// <summary>
    /// Combine a drive root with the given path segments and normalize the result. Leading slashes of the segments
    /// are stripped so that absolute-looking inputs are treated as drive-relative, and the normalized result must
    /// not escape the root (e.g. via ..)
    /// </summary>
    /// <param name="root">Physical root directory the result must remain in</param>
    /// <param name="segments">Path segments to combine</param>
    /// <returns>Normalized physical path</returns>
    /// <exception cref="ArgumentException">Resulting path escapes the root directory</exception>
    private static string CombineContained(string root, params string[] segments)
    {
        string fullRoot = Path.GetFullPath(root);
        string result = Path.GetFullPath(Path.Combine([fullRoot, .. segments.Select(segment => segment.TrimStart('/'))]));
        if (result != fullRoot && !result.StartsWith(fullRoot.EndsWith('/') ? fullRoot : fullRoot + '/', StringComparison.Ordinal))
        {
            throw new ArgumentException($"Path {string.Join('/', segments)} escapes the volume root directory");
        }
        return result;
    }

    /// <summary>
    /// Get the physical root directory of the given drive number
    /// </summary>
    /// <param name="driveNumber">Drive number</param>
    /// <returns>Physical root directory</returns>
    /// <exception cref="ArgumentException">Invalid drive index</exception>
    private string GetDrivePath(int driveNumber)
    {
        if (driveNumber == 0)
        {
            return Path.GetFullPath(settings.Value.BaseDirectory);
        }

        using (model.AccessReadOnly())
        {
            if (driveNumber > 0 && driveNumber < model.Volumes.Count)
            {
                return model.Volumes[driveNumber].Path ?? throw new ArgumentException("Invalid drive index");
            }
        }
        throw new ArgumentException("Invalid drive index");
    }

    /// <summary>
    /// Get the physical root directory of the given drive number asynchronously
    /// </summary>
    /// <param name="driveNumber">Drive number</param>
    /// <param name="cancellationToken">Optional cancellation token</param>
    /// <returns>Physical root directory</returns>
    /// <exception cref="ArgumentException">Invalid drive index</exception>
    private async Task<string> GetDrivePathAsync(int driveNumber, CancellationToken cancellationToken = default)
    {
        if (driveNumber == 0)
        {
            return Path.GetFullPath(settings.Value.BaseDirectory);
        }

        using (await model.AccessReadOnlyAsync(cancellationToken))
        {
            if (driveNumber > 0 && driveNumber < model.Volumes.Count)
            {
                return model.Volumes[driveNumber].Path ?? throw new ArgumentException("Invalid drive index");
            }
        }
        throw new ArgumentException("Invalid drive index");
    }

    /// <summary>
    /// Get the virtual directory path for the given well-known directory
    /// </summary>
    /// <param name="directory">Well-known directory</param>
    /// <returns>Virtual directory path</returns>
    private string GetDirectoryPath(FileDirectory directory)
    {
        using (model.AccessReadOnly())
        {
            return directory switch
            {
                FileDirectory.Filaments => model.Directories.Filaments,
                FileDirectory.Firmware => model.Directories.Firmware,
                FileDirectory.GCodes => model.Directories.GCodes,
                FileDirectory.Macros => model.Directories.Macros,
                FileDirectory.Menu => model.Directories.Menu,
                FileDirectory.System => model.Directories.System,
                FileDirectory.Web => model.Directories.Web,
                _ => model.Directories.System,
            };
        }
    }

    /// <summary>
    /// Get the virtual directory path for the given well-known directory asynchronously
    /// </summary>
    /// <param name="directory">Well-known directory</param>
    /// <param name="cancellationToken">Optional cancellation token</param>
    /// <returns>Virtual directory path</returns>
    private async Task<string> GetDirectoryPathAsync(FileDirectory directory, CancellationToken cancellationToken = default)
    {
        using (await model.AccessReadOnlyAsync(cancellationToken))
        {
            return directory switch
            {
                FileDirectory.Filaments => model.Directories.Filaments,
                FileDirectory.Firmware => model.Directories.Firmware,
                FileDirectory.GCodes => model.Directories.GCodes,
                FileDirectory.Macros => model.Directories.Macros,
                FileDirectory.Menu => model.Directories.Menu,
                FileDirectory.System => model.Directories.System,
                FileDirectory.Web => model.Directories.Web,
                _ => model.Directories.System,
            };
        }
    }

    /// <summary>
    /// Resolve a RepRapFirmware/FatFs-style file path to a physical file path.
    /// The first drive (0:/) is reserved for usage with the base directory as specified in the settings
    /// </summary>
    /// <param name="filePath">File path to resolve</param>
    /// <param name="directory">Directory containing filePath if it is not absolute is specified</param>
    /// <returns>Resolved file path</returns>
    public string ToPhysical(string filePath, FileDirectory directory) => ToPhysical(filePath, GetDirectoryPath(directory));

    /// <summary>
    /// Resolve a RepRapFirmware/FatFs-style file path to a physical file path asynchronously.
    /// The first drive (0:/) is reserved for usage with the base directory as specified in the settings
    /// </summary>
    /// <param name="filePath">File path to resolve</param>
    /// <param name="directory">Directory containing filePath if it is not absolute is specified</param>
    /// <param name="cancellationToken">Optional cancellation token</param>
    /// <returns>Resolved file path</returns>
    public async Task<string> ToPhysicalAsync(string filePath, FileDirectory directory, CancellationToken cancellationToken = default)
    {
        return await ToPhysicalAsync(filePath, await GetDirectoryPathAsync(directory, cancellationToken), cancellationToken);
    }

    /// <summary>
    /// Resolve a RepRapFirmware/FatFs-style file path to a physical file path.
    /// The first drive (0:/) is reserved for usage with the base directory as specified in the settings.
    /// </summary>
    /// <param name="filePath">File path to resolve</param>
    /// <param name="directory">Directory containing filePath if it is not absolute is specified</param>
    /// <returns>Resolved file path</returns>
    public string ToPhysical(string filePath, string? directory = null)
    {
        filePath = filePath.Replace('\\', '/');

        Match match = _driveRegex.Match(filePath);
        if (match.Success && int.TryParse(match.Groups[1].Value, out int driveNumber))
        {
            return CombineContained(GetDrivePath(driveNumber), match.Groups[2].Value);
        }

        if (directory is not null && !filePath.StartsWith('/'))
        {
            match = _driveRegex.Match(directory);
            if (match.Success && int.TryParse(match.Groups[1].Value, out driveNumber))
            {
                return CombineContained(GetDrivePath(driveNumber), match.Groups[2].Value, filePath);
            }
            return CombineContained(settings.Value.BaseDirectory, directory, filePath);
        }
        return CombineContained(settings.Value.BaseDirectory, filePath);
    }

    /// <summary>
    /// Resolve a RepRapFirmware/FatFs-style file path to a physical file path asynchronously.
    /// The first drive (0:/) is reserved for usage with the base directory as specified in the settings.
    /// </summary>
    /// <param name="filePath">File path to resolve</param>
    /// <param name="directory">Directory containing filePath if it is not absolute is specified</param>
    /// <param name="cancellationToken">Optional cancellation token</param>
    /// <returns>Resolved file path</returns>
    public async Task<string> ToPhysicalAsync(string filePath, string? directory = null, CancellationToken cancellationToken = default)
    {
        filePath = filePath.Replace('\\', '/');

        Match match = _driveRegex.Match(filePath);
        if (match.Success && int.TryParse(match.Groups[1].Value, out int driveNumber))
        {
            return CombineContained(await GetDrivePathAsync(driveNumber, cancellationToken), match.Groups[2].Value);
        }

        if (directory is not null && !filePath.StartsWith('/'))
        {
            match = _driveRegex.Match(directory);
            if (match.Success && int.TryParse(match.Groups[1].Value, out driveNumber))
            {
                return CombineContained(await GetDrivePathAsync(driveNumber, cancellationToken), match.Groups[2].Value, filePath);
            }
            return CombineContained(settings.Value.BaseDirectory, directory, filePath);
        }
        return CombineContained(settings.Value.BaseDirectory, filePath);
    }

    /// <summary>
    /// Check if the given physical path is located inside the given volume directory and compute the relative path if so
    /// </summary>
    /// <param name="filePath">Physical path to check</param>
    /// <param name="volumePath">Physical volume root directory</param>
    /// <param name="relativePath">Path relative to the volume root</param>
    /// <returns>True if the path is located inside the volume</returns>
    private static bool TryGetRelativeToVolume(string filePath, string volumePath, out string relativePath)
    {
        string fullVolume = Path.GetFullPath(volumePath);
        if (filePath == fullVolume)
        {
            relativePath = string.Empty;
            return true;
        }

        string prefix = fullVolume.EndsWith('/') ? fullVolume : fullVolume + '/';
        if (filePath.StartsWith(prefix, StringComparison.Ordinal))
        {
            relativePath = filePath[prefix.Length..];
            return true;
        }

        relativePath = string.Empty;
        return false;
    }

    /// <summary>
    /// Convert a physical file path to a RRF-style file path.
    /// The first drive (0:/) is reserved for usage with the base directory as specified in the settings.
    /// </summary>
    /// <param name="filePath">File path to convert</param>
    /// <returns>Resolved file path</returns>
    public string ToVirtual(string filePath)
    {
        if (TryGetRelativeToVolume(filePath, settings.Value.BaseDirectory, out string relativePath))
        {
            return "0:/" + relativePath;
        }

        using (model.AccessReadOnly())
        {
            for (int i = 1; i < model.Volumes.Count; i++)
            {
                string? path = model.Volumes[i].Path;
                if (path is not null && TryGetRelativeToVolume(filePath, path, out relativePath))
                {
                    return $"{i}:/" + relativePath;
                }
            }
        }

        // Use default first volume as fallback
        return Path.Combine("0:/", filePath);
    }

    /// <summary>
    /// Convert a physical file path to a RRF-style file path asynchronously.
    /// The first drive (0:/) is reserved for usage with the base directory as specified in the settings.
    /// </summary>
    /// <param name="filePath">File path to convert</param>
    /// <param name="cancellationToken">Optional cancellation token</param>
    /// <returns>Resolved file path</returns>
    public async Task<string> ToVirtualAsync(string filePath, CancellationToken cancellationToken = default)
    {
        if (TryGetRelativeToVolume(filePath, settings.Value.BaseDirectory, out string relativePath))
        {
            return "0:/" + relativePath;
        }

        using (await model.AccessReadOnlyAsync(cancellationToken))
        {
            for (int i = 1; i < model.Volumes.Count; i++)
            {
                string? path = model.Volumes[i].Path;
                if (path is not null && TryGetRelativeToVolume(filePath, path, out relativePath))
                {
                    return $"{i}:/" + relativePath;
                }
            }
        }

        // Use default first volume as fallback
        return Path.Combine("0:/", filePath);
    }
}
