using DuetSharedLibrary;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Text;
using System.Threading.Tasks;

namespace DuetPiManagementPlugin
{
    /// <summary>
    /// Static class to provide functions for invoking commands
    /// </summary>
    public static class Command
    {
        /// <summary>
        /// Execute a process, wait for it to exit, and return the stdout/stderr output
        /// </summary>
        /// <param name="fileName">File to execute</param>
        /// <param name="arguments">Command-line arguments</param>
        /// <returns>Command output</returns>
        public static async Task<string> ExecuteAsync(string fileName, string arguments)
        {
            ProcessStartInfo startInfo = new()
            {
                FileName = fileName,
                Arguments = arguments,
                RedirectStandardError = true,
                RedirectStandardOutput = true
            };

            using Process? process = Process.Start(startInfo);
            if (process is not null)
            {
                await process.WaitForExitAsync(Program.CancellationToken);

                string output;
                output  = await process.StandardOutput.ReadToEndAsync();
                output += await process.StandardError.ReadToEndAsync();
                return output.Replace("\u001b[2K", string.Empty).Trim();        // Escape sequence generated by nmcli
            }
            return string.Empty;
        }

        /// <summary>
        /// Execute an APT process that reports its progress on stderr and wait for it to exit
        /// </summary>
        /// <param name="unit">Name of the transient unit to run the process in</param>
        /// <param name="fileName">File to execute</param>
        /// <param name="arguments">Command-line arguments</param>
        /// <param name="reporter">Reporter to notify about the progress</param>
        /// <returns>Exit code and command output</returns>
        /// <remarks>
        /// APT only writes machine-readable status lines when it is told which file descriptor to use for them.
        /// Since the status descriptor cannot be assigned freely from .NET, stderr is used for it,
        /// so status lines have to be filtered out of the regular error output again
        /// </remarks>
        public static async Task<(int ExitCode, string Output)> ExecuteAptAsync(string unit, string fileName, string arguments, UpgradeReporter reporter)
        {
            using Process process = TransientUnit.Start(unit, fileName, arguments, true, new Dictionary<string, string>
            {
                ["LC_ALL"] = "C",
                ["DEBIAN_FRONTEND"] = "noninteractive"
            });

            StringBuilder output = new();
            Task<string> stdoutTask = process.StandardOutput.ReadToEndAsync(Program.CancellationToken);
            while (await process.StandardError.ReadLineAsync(Program.CancellationToken) is string line)
            {
                if (TryParseAptStatus(line, out bool installing, out string message, out float? progress))
                {
                    await reporter.ReportAsync(installing, message, progress);
                }
                else
                {
                    output.AppendLine(line);
                }
            }

            await process.WaitForExitAsync(Program.CancellationToken);
            return (process.ExitCode, (await stdoutTask + output.ToString()).Trim());
        }

        /// <summary>
        /// Try to parse a machine-readable APT status line
        /// </summary>
        /// <param name="line">Line to parse</param>
        /// <param name="installing">Whether packages are being installed rather than downloaded</param>
        /// <param name="message">Description of the current step</param>
        /// <param name="progress">Progress of the current step (0..1)</param>
        /// <returns>Whether the line was a status line</returns>
        private static bool TryParseAptStatus(string line, out bool installing, out string message, out float? progress)
        {
            installing = line.StartsWith("pmstatus:");
            message = string.Empty;
            progress = null;

            // Status lines are of the form <type>:<item>:<percentage>:<description>
            if (!installing && !line.StartsWith("dlstatus:"))
            {
                return false;
            }

            string[] fields = line.Split(':', 4);
            if (fields.Length < 4)
            {
                return false;
            }

            message = fields[3].Trim();
            if (float.TryParse(fields[2], NumberStyles.Float, CultureInfo.InvariantCulture, out float percentage))
            {
                progress = Math.Clamp(percentage / 100f, 0f, 1f);
            }
            return true;
        }

        /// <summary>
        /// Execute a process to check if a condition is true or false
        /// </summary>
        /// <param name="fileName">File to execute</param>
        /// <param name="arguments">Command-line arguments</param>
        /// <returns>Query result</returns>
        public static async Task<bool> ExecQueryAsync(string fileName, string arguments)
        {
            using Process process = Process.Start(fileName, arguments);
            await process.WaitForExitAsync(Program.CancellationToken);
            return process.ExitCode == 0;
        }
    }
}
