#!/bin/sh

# Set ownership and permissions
chown dsf:dsf /opt/dsf/plugins/DuetPiManagementPlugin.json
chmod 440 /opt/dsf/plugins/DuetPiManagementPlugin.json

chown -R dsf:dsf /opt/dsf/plugins/DuetPiManagementPlugin
chmod 755 /opt/dsf/plugins/DuetPiManagementPlugin

# Reload the plugin manifest
if [ -f /opt/dsf/plugins/DuetPiManagementPlugin/.start ]; then
        rm /opt/dsf/plugins/DuetPiManagementPlugin/.start
        if (systemctl is-active -q duetcontrolserver && systemctl is-active -q duetpluginservice && systemctl is-active -q duetpluginservice-root); then
				# Don't wait for the plugin manager to complete because it could result in a deadlock in case the installation was kicked off from DPS-root
                /opt/dsf/bin/PluginManager -q reload DuetPiManagementPlugin && /opt/dsf/bin/PluginManager -q start DuetPiManagementPlugin &
        else
                echo "DuetPiManagementPlugin" >> /opt/dsf/conf/plugins.txt
        fi
fi

# Don't block the configuration of other packages if DPS failed to start
exit 0

