#!/bin/sh

# Set ownership and permissions
chown dsf:dsf /opt/dsf/plugins/DuetPiManagementPlugin.json
chmod 440 /opt/dsf/plugins/DuetPiManagementPlugin.json

chown -R dsf:dsf /opt/dsf/plugins/DuetPiManagementPlugin
chmod 755 /opt/dsf/plugins/DuetPiManagementPlugin

# Reload the plugin manifest
if (systemctl is-active -q duetcontrolserver && systemctl is-active -q duetpluginservice && systemctl is-active -q duetpluginservice-root); then
	/opt/dsf/bin/PluginManager -q reload DuetPiManagementPlugin
	if [[ -f /opt/dsf/plugins/DuetPiManagementPlugin/.start ]]; then
		rm /opt/dsf/plugins/DuetPiManagementPlugin/.start
		/opt/dsf/bin/PluginManager -q start DuetPiManagementPlugin
	fi
fi

# Don't block the configuration of other packages if DPS failed to start
exit 0
