#!/bin/bash

# Stop the plugin first
if (systemctl is-active -q duetcontrolserver && /opt/dsf/bin/PluginManager -q is-started DuetPiManagementPlugin); then
	/opt/dsf/bin/PluginManager -q stop DuetPiManagementPlugin
	if [[ "$1" == "upgrade" ]]; then
		# Restart it again when the upgrade is complete
		touch /opt/dsf/plugins/DuetPiManagementPlugin/.start
	fi
elif ([[ -e /opt/dsf/conf/plugins.txt ]] && grep -q -e "^DuetPiManagementPlugin$" /opt/dsf/conf/plugins.txt ); then
	sed -e '/^DuetPiManagementPlugin$/d' -i /opt/dsf/conf/plugins.txt
	if [[ "$1" == "upgrade" ]]; then
		# Restart it again when the upgrade is complete
		touch /opt/dsf/plugins/DuetPiManagementPlugin/.start
	fi
fi

# Make manifest writable again
chmod 660 /opt/dsf/plugins/DuetPiManagementPlugin.json

