<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<PackageLicenseExpression>GPL-3.0</PackageLicenseExpression>
		<PublishAot Condition="'$(AotPublish)' == 'true'">true</PublishAot>
		<EnableAotAnalyzer>true</EnableAotAnalyzer>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\DuetAPIClient\DuetAPIClient.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="System.CommandLine" Version="2.0.8" />
	</ItemGroup>
</Project>
