using System.Text;
using CanMessageGenerator.Model;

namespace CanMessageGenerator.Emit;

/// <summary>
/// One checkable fact about a struct's layout.
/// </summary>
/// <param name="Struct">Schema name of the struct.</param>
/// <param name="CppName">How the struct is spelled in C++ (nested and template types differ).</param>
/// <param name="Size">Expected size in bytes.</param>
/// <param name="FieldOffsets">Expected byte offset of each public non-bitfield member.</param>
/// <param name="BitPatterns">
/// For each bitfield, the bytes of an otherwise-zeroed struct after that field alone has been set to all ones.
/// Comparing these patterns pins down the exact bit position and width of every bitfield.
/// </param>
public sealed record LayoutFacts(
    string Struct,
    string CppName,
    int Size,
    List<(string Name, int Offset)> FieldOffsets,
    List<(string Name, int Width, bool Signed, bool Bool, byte[] Pattern)> BitPatterns);

/// <summary>
/// Emits the conformance harnesses that verify the generated layouts.
/// </summary>
/// <remarks>
/// The generator computes the expected layout of every struct from the schema. The same expectations are
/// then asserted in two places: a C++ probe that can be compiled against either the original hand-written
/// CanMessageFormats.h or the generated one, and an NUnit test over the generated C# structs. If all three
/// agree, the C++ and C# definitions are byte-for-byte identical to the original CANlib layout.
/// </remarks>
public sealed class ConformanceEmitter(CanSchema schema)
{
    public List<LayoutFacts> Collect()
    {
        List<LayoutFacts> facts = [];
        foreach (StructDef s in schema.Structs)
        {
            if (s.TemplateParam is not null || (!s.IsGenerated(Language.Cpp) && !s.IsGenerated(Language.CSharp)))
            {
                continue;                                       // templates are covered by their expansions
            }
            if (s.Size == 0 && s.Members.Count == 0)
            {
                continue;                                       // an empty message has nothing to pin down beyond its size
            }

            string cppName = s.NestedIn is not null ? $"{s.NestedIn}::{s.Name}"
                : s.TemplateOf is not null ? $"{s.TemplateOf}<{Types.Cpp(schema, s.TemplateArg!)}>"
                : s.Name;

            List<(string, int)> offsets = [.. s.FlatMembers
                .Where(m => m.Kind is MemberKind.Field or MemberKind.Array && !m.CppPrivate)
                .Select(m => (CppPath(m.CppAccessPath, m.Name), m.Offset))];

            List<(string, int, bool, bool, byte[])> patterns = [];
            foreach (BitFieldDef f in s.AllBitFields)
            {
                byte[] pattern = new byte[Math.Max(s.Size, 1)];
                for (int bit = f.BitOffset; bit < f.BitOffset + f.Width; bit++)
                {
                    pattern[bit / 8] |= (byte)(1 << (bit % 8));
                }
                patterns.Add((CppPath(f.CppAccessPath, f.Name), f.Width, f.Signed, f.Bool, pattern));
            }

            facts.Add(new LayoutFacts(s.Name, cppName, Math.Max(s.Size, 1), offsets, patterns));
        }
        return facts;
    }

    /// <summary>
    /// Emit a C++ probe that checks the expected layout against whichever CanMessageFormats.h is on the
    /// include path. Compiling it against the original header proves that the schema describes CANlib
    /// faithfully; compiling it against the generated header proves the generated header is equivalent.
    /// </summary>
    public string EmitCppProbe(List<LayoutFacts> facts)
    {
        CodeWriter w = new();
        w.Line("/*");
        w.Line(" * CanMessageLayoutProbe.cpp");
        w.Line(" *");
        w.Line(" * <auto-generated>");
        w.Line(" *     Generated by tools/CanMessageGenerator from Schema/can-messages.json.");
        w.Line(" *");
        w.Line(" *     Verifies that the CanMessageFormats.h on the include path has exactly the layout that");
        w.Line(" *     the schema describes. Compile it against CANlib's hand-written header to check that the");
        w.Line(" *     schema is faithful, and against the generated header to check that they are equivalent.");
        w.Line(" * </auto-generated>");
        w.Line(" */");
        w.Line();
        w.Line("#include <CanMessageFormats.h>");
        w.Line();
        w.Line("#include <cstddef>");
        w.Line("#include <cstdio>");
        w.Line("#include <cstring>");
        w.Line();
        w.Line("static int failures = 0;");
        w.Line("static int checks = 0;");
        w.Line();
        using (w.Block("static void CheckSize(const char *name, size_t actual, size_t expected)", "}"))
        {
            w.Outdent(); w.Line("{"); w.Indent();
            w.Line("++checks;");
            using (w.Block("if (actual != expected)", "}"))
            {
                w.Outdent(); w.Line("{"); w.Indent();
                w.Line("printf(\"FAIL sizeof(%s): expected %zu, got %zu\\n\", name, expected, actual);");
                w.Line("++failures;");
            }
        }
        w.Line();
        using (w.Block("static void CheckOffset(const char *structName, const char *field, size_t actual, size_t expected)", "}"))
        {
            w.Outdent(); w.Line("{"); w.Indent();
            w.Line("++checks;");
            using (w.Block("if (actual != expected)", "}"))
            {
                w.Outdent(); w.Line("{"); w.Indent();
                w.Line("printf(\"FAIL offsetof(%s, %s): expected %zu, got %zu\\n\", structName, field, expected, actual);");
                w.Line("++failures;");
            }
        }
        w.Line();
        using (w.Block("static void CheckPattern(const char *structName, const char *field, const unsigned char *actual, const unsigned char *expected, size_t length)", "}"))
        {
            w.Outdent(); w.Line("{"); w.Indent();
            w.Line("++checks;");
            using (w.Block("if (memcmp(actual, expected, length) != 0)", "}"))
            {
                w.Outdent(); w.Line("{"); w.Indent();
                w.Line("printf(\"FAIL bit layout of %s.%s\\n  expected \", structName, field);");
                w.Line("for (size_t i = 0; i < length; ++i) printf(\"%02x\", expected[i]);");
                w.Line("printf(\"\\n  actual   \");");
                w.Line("for (size_t i = 0; i < length; ++i) printf(\"%02x\", actual[i]);");
                w.Line("printf(\"\\n\");");
                w.Line("++failures;");
            }
        }
        w.Line();
        w.Line("#define CHECK_BITFIELD(TYPE, NAME, FIELD, ...) \\");
        w.Line("\tdo { \\");
        w.Line("\t\tTYPE probe; \\");
        w.Line("\t\tmemset(&probe, 0, sizeof(probe)); \\");
        w.Line("\t\tprobe.FIELD = ~0; \\");
        w.Line("\t\tstatic const unsigned char expected[] = { __VA_ARGS__ }; \\");
        w.Line("\t\tCheckPattern(NAME, #FIELD, (const unsigned char *)&probe, expected, sizeof(probe)); \\");
        w.Line("\t} while (false)");
        w.Line();

        using (w.Block("int main()", "}"))
        {
            w.Outdent(); w.Line("{"); w.Indent();
            foreach (LayoutFacts f in facts)
            {
                w.Line($"// {f.Struct}");
                w.Line($"CheckSize(\"{f.CppName}\", sizeof({f.CppName}), {f.Size});");
                foreach ((string name, int offset) in f.FieldOffsets)
                {
                    w.Line($"CheckOffset(\"{f.CppName}\", \"{name}\", offsetof({f.CppName}, {name}), {offset});");
                }
                foreach ((string name, _, _, _, byte[] pattern) in f.BitPatterns)
                {
                    w.Line($"CHECK_BITFIELD({f.CppName}, \"{f.CppName}\", {name}, {CppBytes(pattern)});");
                }
                w.Line();
            }
            w.Line("printf(\"%d layout checks, %d failures\\n\", checks, failures);");
            w.Line("return failures == 0 ? 0 : 1;");
        }
        return w.ToString();
    }

    /// <summary>
    /// Emit a C++ probe over the generic message parameter tables. Like the layout probe it is compiled
    /// against both headers: against CANlib's tables it proves the schema describes them faithfully, and
    /// against the generated tables it proves the two are the same. The entries are checked field by field
    /// because all three fields matter — the letter identifies the parameter, the type decides how the
    /// value is packed, and the array length bounds it.
    /// </summary>
    public string EmitCppTablesProbe()
    {
        CodeWriter w = new();
        w.Line("/*");
        w.Line(" * CanMessageGenericTablesProbe.cpp");
        w.Line(" *");
        w.Line(" * <auto-generated>");
        w.Line(" *     Generated by tools/CanMessageGenerator from Schema/can-messages.json.");
        w.Line(" *");
        w.Line(" *     Verifies that the CanMessageGenericTables.h on the include path holds exactly the");
        w.Line(" *     parameter tables that the schema describes. Compile it against CANlib's hand-written");
        w.Line(" *     tables to check that the schema is faithful, and against the generated ones to check");
        w.Line(" *     that they are equivalent.");
        w.Line(" * </auto-generated>");
        w.Line(" */");
        w.Line();
        w.Line("#include <CanMessageGenericTables.h>");
        w.Line();
        w.Line("#include <cstddef>");
        w.Line("#include <cstdio>");
        w.Line();
        w.Line("static int failures = 0;");
        w.Line("static int checks = 0;");
        w.Line();
        using (w.Block("static void CheckEntry(const char *table, unsigned int index, const ParamDescriptor& actual, char letter, unsigned int type, unsigned int maxArrayLength)", "}"))
        {
            w.Outdent(); w.Line("{"); w.Indent();
            w.Line("++checks;");
            using (w.Block("if (actual.letter != letter || (unsigned int)actual.type != type || actual.maxArrayLength != maxArrayLength)", "}"))
            {
                w.Outdent(); w.Line("{"); w.Indent();
                w.Line("printf(\"FAIL %s[%u]: expected {'%c', 0x%02x, %u}, got {'%c', 0x%02x, %u}\\n\",");
                w.Line("       table, index, letter, type, maxArrayLength,");
                w.Line("       actual.letter, (unsigned int)actual.type, actual.maxArrayLength);");
                w.Line("++failures;");
            }
        }
        w.Line();
        // The table length is pinned by requiring the terminator at exactly the expected index, which is
        // what stops an extra entry from slipping in unnoticed
        using (w.Block("static void CheckLength(const char *table, const ParamDescriptor *entries, unsigned int expected)", "}"))
        {
            w.Outdent(); w.Line("{"); w.Indent();
            w.Line("++checks;");
            w.Line("unsigned int length = 0;");
            w.Line("while (entries[length].letter != 0) { ++length; }");
            using (w.Block("if (length != expected)", "}"))
            {
                w.Outdent(); w.Line("{"); w.Indent();
                w.Line("printf(\"FAIL %s: expected %u entries, got %u\\n\", table, expected, length);");
                w.Line("++failures;");
            }
        }
        w.Line();

        using (w.Block("int main()", "}"))
        {
            w.Outdent(); w.Line("{"); w.Indent();
            foreach (GenericTableDef table in schema.GenericTables)
            {
                w.Line($"// {table.Name}");
                w.Line($"CheckLength(\"{table.Name}\", {table.Name}, {table.Params.Count});");
                for (int i = 0; i < table.Params.Count; i++)
                {
                    GenericParamDef p = table.Params[i];
                    w.Line($"CheckEntry(\"{table.Name}\", {i}, {table.Name}[{i}], '{p.Letter}', 0x{p.Type.Value:x2}, {p.MaxLength});");
                }
                w.Line();
            }
            w.Line("printf(\"%d generic table checks, %d failures\\n\", checks, failures);");
            w.Line("return failures == 0 ? 0 : 1;");
        }
        return w.ToString();
    }

    /// <summary>Strip the C++ access path from a member name, leaving the flat schema name.</summary>
    private static string Flat(string name) => name.Contains('.') ? name[(name.LastIndexOf('.') + 1)..] : name;

    /// <summary>Qualify a member name with the sub-struct that CANlib's own declaration nests it in.</summary>
    private static string CppPath(string? accessPath, string name) => accessPath is null ? name : $"{accessPath}.{name}";

    private static string CppBytes(byte[] bytes) => string.Join(", ", bytes.Select(b => $"0x{b:x2}"));

    /// <summary>
    /// Emit an NUnit fixture that checks the generated C# structs against the same expectations.
    /// </summary>
    public string EmitCSharpTests(List<LayoutFacts> facts, string testNamespace)
    {
        CodeWriter w = new("    ");
        w.Line("// <auto-generated>");
        w.Line("//     Generated by tools/CanMessageGenerator from Schema/can-messages.json.");
        w.Line("//");
        w.Line("//     Checks that the generated C# structs have exactly the layout that the schema describes,");
        w.Line("//     which is the same layout the C++ probe checks against CANlib's CanMessageFormats.h.");
        w.Line("// </auto-generated>");
        w.Line();
        w.Line("using System;");
        w.Line("using System.Runtime.CompilerServices;");
        w.Line("using System.Runtime.InteropServices;");
        w.Line("using NUnit.Framework;");
        w.Line($"using {schema.CSharpNamespace};");
        w.Line();
        w.Line($"namespace {testNamespace};");
        w.Line();
        w.Line("[TestFixture]");
        using (w.Block("public class CanMessageLayout", "}"))
        {
            w.Outdent(); w.Line("{"); w.Indent();

            foreach (LayoutFacts f in facts)
            {
                StructDef s = schema.ByName[f.Struct];
                if (!s.IsGenerated(Language.CSharp))
                {
                    continue;
                }

                w.Line("[Test]");
                using (w.Block($"public void {f.Struct}_Layout()", "}"))
                {
                    w.Outdent(); w.Line("{"); w.Indent();
                    w.Line($"Assert.That(Unsafe.SizeOf<{f.Struct}>(), Is.EqualTo({f.Size}), \"size of {f.Struct}\");");

                    foreach ((string name, int offset) in f.FieldOffsets)
                    {
                        w.Line($"Assert.That(Marshal.OffsetOf<{f.Struct}>(\"{Naming.Pascal(Flat(name))}\").ToInt32(), Is.EqualTo({offset}), \"offset of {f.Struct}.{Naming.Pascal(name)}\");");
                    }

                    foreach ((string name, int width, bool signed, bool isBool, byte[] pattern) in f.BitPatterns)
                    {
                        string property = Naming.Pascal(Flat(name));
                        string allOnes = isBool ? "true"
                            : signed ? "-1"
                            : width switch
                            {
                                <= 8 => $"(byte)0x{(1UL << width) - 1:X}",
                                <= 16 => $"(ushort)0x{(1UL << width) - 1:X}",
                                <= 32 => $"0x{(1UL << width) - 1:X}U",
                                _ => $"0x{(width >= 64 ? ulong.MaxValue : (1UL << width) - 1):X}UL"
                            };
                        w.Line("{");
                        w.Indent();
                        w.Line($"{f.Struct} probe = default;");
                        w.Line($"probe.{property} = {allOnes};");
                        w.Line($"Assert.That(Raw(ref probe), Is.EqualTo(new byte[] {{ {string.Join(", ", pattern.Select(b => $"0x{b:X2}"))} }}), \"bit layout of {f.Struct}.{property}\");");
                        w.Outdent();
                        w.Line("}");
                    }
                }
                w.Line();
            }

            w.Line("private static byte[] Raw<T>(ref T value) where T : struct =>");
            w.Line("    MemoryMarshal.AsBytes(new Span<T>(ref value)).ToArray();");
        }
        return w.ToString();
    }
}
