using CanMessageGenerator.Expressions;
using CanMessageGenerator.Model;

namespace CanMessageGenerator.Emit;

/// <summary>
/// Emits the C++ side of the CAN message formats: a drop-in replacement for CANlib's CanMessageFormats.h.
/// </summary>
public sealed class CppEmitter(CanSchema schema)
{
    private readonly CodeWriter _writer = new();
    private readonly List<string> _deferredAsserts = [];

    public string Emit()
    {
        _writer.Line("/*");
        _writer.Line(" * CanMessageFormats.h");
        _writer.Line(" *");
        _writer.Line(" * <auto-generated>");
        _writer.Line(" *     Generated by tools/CanMessageGenerator from Schema/can-messages.json.");
        _writer.Line(" *     Do not edit this file directly: edit the schema and re-run the generator, otherwise");
        _writer.Line(" *     the C++ and C# definitions of these messages will drift apart.");
        _writer.Line(" * </auto-generated>");
        _writer.Line(" */");
        _writer.Line();
        _writer.Line($"#ifndef {schema.CppHeaderGuard}");
        _writer.Line($"#define {schema.CppHeaderGuard}");
        _writer.Line();
        foreach (string include in schema.CppIncludes)
        {
            _writer.Line($"#include {include}");
        }
        _writer.Line();
        _writer.Line("size_t CanAdjustedLength(size_t rawLength) noexcept;");
        _writer.Line();
        _writer.Line("// CAN message formats");
        _writer.Line("// Some messages end in strings. For such messages, it is safe to compute the message length without allowing for a null terminator,");
        _writer.Line("// because when our sending functions round the message length up to a supported CAN size the additional data is set to zeros.");
        _writer.Line("// All fields named 'zero' are spare and must be set to 0 for compatibility with future uses.");
        _writer.Line("// Message formats that take a request ID have a SetRequestId method that sets the request ID and clears the zero fields.");
        _writer.Line("// Message formats that don't take a request ID have a ClearReservedFields method that clears the zero fields.");
        _writer.Line();
        _writer.Line("struct ParamDescriptor;");
        _writer.Line();

        foreach (StructDef s in schema.Structs.Where(s => s.IsGenerated(Language.Cpp) && s.NestedIn is null))
        {
            EmitStruct(s);
        }

        if (_deferredAsserts.Count > 0)
        {
            _writer.Line("// Template instantiations are asserted here rather than next to the template itself,");
            _writer.Line("// because their argument types are declared further down the file.");
            foreach (string assertion in _deferredAsserts)
            {
                _writer.Line(assertion);
            }
            _writer.Line();
        }

        EmitUnion();

        _writer.Line($"#endif /* {schema.CppHeaderGuard} */");
        return _writer.ToString();
    }

    private void EmitStruct(StructDef s)
    {
        _writer.Doc(s.Doc, "// ");

        string keyword = s.IsUnion ? "union" : "struct";
        string packed = s.Packed && !s.IsUnion ? " __attribute__((packed))" : s.Packed ? " __attribute__((packed))" : "";
        string final = s.CppFinal ? " final" : "";
        if (s.TemplateParam is not null)
        {
            _writer.Line($"template<class {s.TemplateParam}> {keyword}{packed} {s.Name}{final}");
        }
        else
        {
            _writer.Line($"{keyword}{packed} {s.Name}{final}");
        }

        using (_writer.Block("{", "};"))
        {
            if (s.MessageType is not null)
            {
                _writer.Line($"static constexpr CanMessageType messageType = CanMessageType::{s.MessageType};");
                _writer.Line();
            }

            foreach (StructDef nested in schema.Structs.Where(n => n.NestedIn == s.Name && n.IsGenerated(Language.Cpp)))
            {
                EmitNested(nested);
            }

            bool anyPrivate = false;
            foreach (MemberDef m in s.Members)
            {
                if (m.CppPrivate && !anyPrivate)
                {
                    _writer.Outdent();
                    _writer.Line("private:                                    // unaligned members are private so that they are only accessed through the helpers");
                    _writer.Indent();
                    anyPrivate = true;
                }
                EmitMember(s, m);
            }
            if (anyPrivate)
            {
                _writer.Outdent();
                _writer.Line("public:");
                _writer.Indent();
            }

            if (s.Constants.Count > 0)
            {
                _writer.Line();
                foreach (ConstantDef c in s.Constants)
                {
                    _writer.Doc(c.Doc, "// ");
                    _writer.Line($"static constexpr {Types.Cpp(schema, c.Type)} {c.Name} = {RenderConstant(s, c.Value)};");
                }
            }

            EmitMethods(s);
        }

        EmitSizeAssert(s);
        foreach (string assertion in s.CppStaticAsserts)
        {
            _writer.Line($"static_assert({assertion});");
        }

        foreach (StructDef nested in schema.Structs.Where(n => n.NestedIn == s.Name && n.IsGenerated(Language.Cpp)))
        {
            EmitSizeAssert(nested, $"{s.Name}::{nested.Name}");
        }
        _writer.Line();
    }

    private void EmitSizeAssert(StructDef s, string? qualifiedName = null)
    {
        if (s.TemplateParam is not null)
        {
            // A template's size depends on its argument, so assert each instantiation instead
            foreach (InstantiationDef inst in s.Instantiations)
            {
                StructDef? expanded = schema.Find(s.Name + inst.Suffix);
                if (expanded is not null)
                {
                    _deferredAsserts.Add($"static_assert(sizeof({s.Name}<{Types.Cpp(schema, inst.Arg)}>) == {expanded.Size});");
                }
            }
            return;
        }
        _writer.Line($"static_assert(sizeof({qualifiedName ?? s.Name}) == {Math.Max(s.Size, 1)});");
    }

    private void EmitNested(StructDef nested)
    {
        _writer.Doc(nested.Doc, "// ");
        string keyword = nested.IsUnion ? "union" : "struct";
        string packed = nested.Packed ? " __attribute__((packed))" : "";
        _writer.Line($"{keyword}{packed} {nested.Name}");
        using (_writer.Block("{", "};"))
        {
            foreach (MemberDef m in nested.Members)
            {
                EmitMember(nested, m);
            }
            EmitMethods(nested);
        }
        _writer.Line();
    }

    private void EmitMember(StructDef s, MemberDef m)
    {
        switch (m.Kind)
        {
            case MemberKind.Field:
                _writer.Doc(m.Doc, "// ");
                _writer.Line($"{Types.Cpp(schema, m.Type)} {m.Name};");
                break;

            case MemberKind.Array:
                _writer.Doc(m.Doc, "// ");
                _writer.Line($"{Types.Cpp(schema, m.Type)} {m.Name}[{m.Length}];");
                break;

            case MemberKind.Bitfield:
            {
                string storage = Types.Cpp(schema, m.Storage);
                for (int i = 0; i < m.Fields.Count; i++)
                {
                    BitFieldDef f = m.Fields[i];
                    string prefix = i == 0 ? $"{storage} " : new string(' ', storage.Length + 1);
                    string terminator = i == m.Fields.Count - 1 ? ";" : ",";
                    string comment = f.Doc is null ? "" : $"\t\t// {f.Doc.Replace('\n', ' ')}";
                    _writer.Line($"{prefix}{f.Name} : {f.Width}{terminator}{comment}");
                }
                break;
            }

            case MemberKind.Union:
                _writer.Doc(m.Doc, "// ");
                using (_writer.Block("union", "};"))
                {
                    _writer.Outdent();
                    _writer.Line("{");
                    _writer.Indent();
                    foreach (MemberDef alt in m.Alternatives)
                    {
                        EmitMember(s, alt);
                    }
                }
                break;
        }
    }

    private void EmitMethods(StructDef s)
    {
        List<MethodDef> methods = [.. s.Methods.Where(x => x.Emit.Contains(Language.Cpp))];
        MethodDef? synthesised = Synthesise.RequestIdOrClear(schema, s);
        if (synthesised is not null)
        {
            methods.Add(synthesised);
        }
        if (methods.Count == 0)
        {
            return;
        }

        _writer.Line();
        foreach (MethodDef m in methods)
        {
            _writer.Doc(m.Doc, "// ");
            if (m.CppSignature is not null)
            {
                _writer.Line(m.CppSignature + ";");
                continue;
            }

            string returnType = m.ReturnType == "void" ? "void" : Types.Cpp(schema, m.ReturnType);
            string parameters = string.Join(", ", m.Params.Select(p => $"{Types.Cpp(schema, p.Type)} {p.Name}"));
            // CANlib marks every one of these noexcept, static ones included
            string qualifiers = m.Const && !m.Static ? " const noexcept" : " noexcept";
            string prefix = m.Static ? "static constexpr " : "";

            if (m.DeclarationOnly)
            {
                _writer.Line($"{prefix}{returnType} {m.Name}({parameters}){qualifiers};");
                continue;
            }

            EmitContext context = new(schema, s, Language.Cpp, [.. m.Params.Select(p => p.Name)]);
            List<Stmt> body = ExprParser.ParseBody(m.Body);
            if (body.Count == 1 && body[0] is ReturnStmt or AssignStmt && m.Params.Count <= 3)
            {
                // Keep the short one-liners that CANlib favours on a single line
                string single = new CppStatementEmitter(context).Render(body[0]);
                _writer.Line($"{prefix}{returnType} {m.Name}({parameters}){qualifiers} {{ {single} }}");
                continue;
            }

            using (_writer.Block($"{prefix}{returnType} {m.Name}({parameters}){qualifiers}", "}"))
            {
                _writer.Outdent();
                _writer.Line("{");
                _writer.Indent();
                new CppStatementEmitter(context).Write(_writer, body);
            }
        }
    }

    private void EmitUnion()
    {
        UnionDef? union = schema.MessageUnion;
        if (union is null)
        {
            return;
        }

        _writer.Doc(union.Doc, "// ");
        _writer.Line($"union {union.Name}");
        using (_writer.Block("{", "};"))
        {
            _writer.Line($"{union.Name}() noexcept {{ }}");
            _writer.Line();
            foreach (UnionMemberDef m in union.Members)
            {
                string type = Types.IsPrimitive(m.Type) ? Types.Primitive(m.Type).Cpp : m.Type;
                _writer.Line(m.Length is null ? $"{type} {m.Name};" : $"{type} {m.Name}[{m.Length}];");
            }
        }
        _writer.Line($"static_assert(sizeof({union.Name}) <= {union.MaxSize}, \"CAN message too big\");");
        _writer.Line();
    }

    private string RenderConstant(StructDef s, string value)
    {
        EmitContext context = new(schema, s, Language.Cpp, []);
        return new CppExprEmitter(context).Render(ExprParser.Parse(value));
    }
}
