using CanMessageGenerator.Model;

namespace CanMessageGenerator.Emit;

/// <summary>
/// Emits the C# side of the generic message parameter tables.
/// </summary>
/// <remarks>
/// The table is the contract between the two ends of the link: the sender packs the parameters it is
/// sending in table order and sets the matching bit of the message's paramMap, and the receiver walks the
/// same table to work out where each value is. So the C# tables have to agree with CANlib's entry for
/// entry, which is what the generated conformance fixture checks.
/// </remarks>
public sealed class CSharpTablesEmitter(CanSchema schema)
{
    public string Emit()
    {
        CodeWriter writer = new("    ");
        writer.Line("// <auto-generated>");
        writer.Line("//     Generated by tools/CanMessageGenerator from Schema/can-messages.json.");
        writer.Line("//     Do not edit this file directly: edit the schema and re-run the generator, otherwise");
        writer.Line("//     the C# and C++ parameter tables will drift apart.");
        writer.Line("// </auto-generated>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("using System;");
        writer.Line("using System.Collections.Immutable;");
        foreach (string u in schema.CSharpUsings)
        {
            writer.Line($"using {u};");
        }
        writer.Line();
        writer.Line($"namespace {schema.CSharpNamespace};");
        writer.Line();

        EmitParamType(writer);
        EmitParamDescriptor(writer);
        EmitTables(writer);
        return writer.ToString();
    }

    /// <summary>
    /// Emit one builder per table, giving each parameter a method of the right type. The letter-keyed
    /// <c>CanGenericWriter</c> underneath can only report a wrong letter or type by throwing at run time;
    /// going through a builder moves both to compile time.
    /// </summary>
    public string EmitBuilders()
    {
        CodeWriter writer = new("    ");
        writer.Line("// <auto-generated>");
        writer.Line("//     Generated by tools/CanMessageGenerator from Schema/can-messages.json.");
        writer.Line("//     Do not edit this file directly: edit the schema and re-run the generator.");
        writer.Line("// </auto-generated>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("using System;");
        writer.Line("using System.Collections.Immutable;");
        writer.Line("using System.Runtime.InteropServices;");
        foreach (string u in schema.CSharpUsings)
        {
            writer.Line($"using {u};");
        }
        writer.Line();
        writer.Line($"namespace {schema.CSharpNamespace};");
        writer.Line();

        foreach (GenericTableDef table in schema.GenericTables.Where(t => t.IsGenerated(Language.CSharp)))
        {
            EmitMessage(writer, table);
            EmitBuilder(writer, table);
        }
        return writer.ToString();
    }

    /// <summary>
    /// Emit the message type for a table: a <c>CanMessageGeneric</c> that knows which message type it is
    /// sent under, so it can go through the ordinary typed send path like any other message.
    /// </summary>
    /// <remarks>
    /// It wraps <c>CanMessageGeneric</c> in a single field at offset 0 rather than restating its fields, so
    /// the wire format is inherited and cannot drift — these are the same 64 bytes the expansion board
    /// already reads, only the C# type differs.
    /// </remarks>
    private void EmitMessage(CodeWriter writer, GenericTableDef table)
    {
        string name = MessageName(table);
        string doc = table.Doc is null ? $"The {table.BaseName} generic message." : CodeWriter.Escape(table.Doc);
        string identity = $"Sent as <see cref=\"CanMessageType.{Naming.MessageTypeMember(table.MessageType!)}\" />.";
        writer.XmlDocRaw($"""
            {doc}

            {identity}
            Carries a <see cref="CanMessageGeneric" /> body: the parameters of
            <see cref="CanGenericTables.{table.Name}" /> that are being sent, packed in table order, plus a
            bitmap saying which those are. Build one with <see cref="{table.BaseName}Builder" />.
            """);
        // Deriving the layout from the wrapped message rather than restating it is what keeps this type from
        // ever disagreeing with the format the expansion board reads
        writer.Line("[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 64)]");
        using (writer.Block($"public struct {name} : ICanMessage<{name}>", "}"))
        {
            writer.Outdent();
            writer.Line("{");
            writer.Indent();

            writer.XmlDocRaw("The generic message body, in the format the expansion board reads");
            writer.Line("[FieldOffset(0)] public CanMessageGeneric Generic;");
            writer.Line();

            writer.Line("/// <inheritdoc cref=\"ICanMessage{TSelf}.MessageType\" />");
            writer.Line($"public static CanMessageType MessageType => CanMessageType.{Naming.MessageTypeMember(table.MessageType!)};");
            writer.Line();

            writer.XmlDocRaw($"The parameter table this message is built against");
            writer.Line($"public static ImmutableArray<CanParamDescriptor> ParamTable => CanGenericTables.{table.Name};");
            writer.Line();

            // Without this the interface default would report sizeof (64) and every message would go out
            // padded to the full data area
            writer.XmlDocRaw("""
                Number of payload bytes this message occupies: the parameters actually present, plus the
                request ID and parameter map.

                The parameter map and the table are enough to work this out, because each present parameter's
                size follows from its table entry and, for the variable-length ones, from the data itself.
                """);
            using (writer.Block("public readonly uint GetActualDataLength()", "}"))
            {
                writer.Outdent();
                writer.Line("{");
                writer.Indent();
                writer.Line($"int dataLength = CanGenericLayout.DataLength(Generic.Data, Generic.ParamMap, CanGenericTables.{table.Name});");
                writer.Line("return CanMessageGeneric.GetActualDataLength((uint)dataLength);");
            }
        }
        writer.Line();
    }

    /// <summary>The name of the generated message type for a table.</summary>
    private static string MessageName(GenericTableDef table) => $"CanMessage{table.BaseName}";

    private void EmitBuilder(CodeWriter writer, GenericTableDef table)
    {
        string name = $"{table.BaseName}Builder";
        string doc = table.Doc is null ? $"Builds the {table.BaseName} generic message." : CodeWriter.Escape(table.Doc);
        writer.XmlDocRaw($"""
            {doc}

            Every parameter is optional: only the ones set are sent, and the receiver is told which by the
            message's parameter map. Parameters may be set in any order.
            """);
        using (writer.Block($"public sealed class {name}", "}"))
        {
            writer.Outdent();
            writer.Line("{");
            writer.Indent();
            writer.Line($"private readonly CanGenericWriter _writer = new(CanGenericTables.{table.Name});");
            writer.Line();

            writer.XmlDocRaw("The message type this message is sent under");
            writer.Line($"public static CanMessageType MessageType => CanMessageType.{Naming.MessageTypeMember(table.MessageType!)};");
            writer.Line();

            writer.XmlDocRaw($"""
                The message as built so far, ready to hand to the CAN send path.
                """);
            using (writer.Block($"public {MessageName(table)} Message", "}"))
            {
                writer.Outdent();
                writer.Line("{");
                writer.Indent();
                writer.Line("get");
                writer.Line("{");
                writer.Indent();
                writer.Line($"{MessageName(table)} message = default;");
                writer.Line("message.Generic = _writer.Message;");
                writer.Line("return message;");
                writer.Outdent();
                writer.Line("}");
            }
            writer.Line();
            writer.XmlDocRaw("The generic message body on its own, without the type that identifies it");
            writer.Line("public CanMessageGeneric Body => _writer.Message;");
            writer.Line();
            writer.XmlDocRaw("Number of payload bytes to transmit, i.e. the parameters plus the request ID and parameter map");
            writer.Line("public uint ActualDataLength => _writer.ActualDataLength;");

            foreach (GenericParamDef param in table.Params)
            {
                writer.Line();
                string summary = param.Doc is null
                    ? $"Set the '{param.Letter}' parameter."
                    : $"Set the '{param.Letter}' parameter: {CodeWriter.Escape(param.Doc)}";
                writer.XmlDocRaw(summary);
                writer.Line("/// <returns>This builder, so that calls can be chained.</returns>");
                if (!param.CanComeFromGCode)
                {
                    // The method keeps the lowercase name on purpose: the letter is the parameter's identity
                    // on the wire, and an uppercase alias would suggest it maps to that G-code letter, which
                    // is the very thing CANlib moved it out of A..Z to prevent
                    writer.Line("/// <remarks>Outside A..Z, so a G-code command can never supply this parameter; the caller has to.</remarks>");
                }
                writer.Line($"public {name} {param.Letter}({Signature(param)}) {{ {Call(param)}; return this; }}");
            }
        }
        writer.Line();
    }

    /// <summary>The parameter list of a builder method, i.e. the narrowest C# type that the entry accepts.</summary>
    private static string Signature(GenericParamDef param) => param.Type.Id switch
    {
        "uint64" => "ulong value",
        "uint32" => "uint value",
        "uint16" or "pwmFreq" => "ushort value",
        "uint8" => "byte value",
        "int32" => "int value",
        "int16" => "short value",
        "int8" => "sbyte value",
        "float" or "float16" => "float value",
        "char" => "char value",
        "string" or "reducedString" => "string value",
        "localDriver" => "byte localDriver",
        "uint8Array" or "uint16Array" or "uint32Array" => "params ReadOnlySpan<uint> values",
        "floatArray" => "params ReadOnlySpan<float> values",
        _ => throw new InvalidOperationException($"no C# signature for parameter type '{param.Type.Id}'")
    };

    /// <summary>The call the builder method makes into the letter-keyed writer.</summary>
    private static string Call(GenericParamDef param) => param.Type.Id switch
    {
        "uint64" => $"_writer.AddUInt64('{param.Letter}', value)",
        "uint32" or "uint16" or "pwmFreq" or "uint8" => $"_writer.AddUInt('{param.Letter}', value)",
        "int32" or "int16" or "int8" => $"_writer.AddInt('{param.Letter}', value)",
        "float" or "float16" => $"_writer.AddFloat('{param.Letter}', value)",
        "char" => $"_writer.AddChar('{param.Letter}', value)",
        "string" or "reducedString" => $"_writer.AddString('{param.Letter}', value)",
        "localDriver" => $"_writer.AddDriverId('{param.Letter}', localDriver)",
        "uint8Array" or "uint16Array" or "uint32Array" => $"_writer.AddUIntArray('{param.Letter}', values)",
        "floatArray" => $"_writer.AddFloatArray('{param.Letter}', values)",
        _ => throw new InvalidOperationException($"no writer call for parameter type '{param.Type.Id}'")
    };

    private static void EmitParamType(CodeWriter writer)
    {
        writer.XmlDocRaw("""
            Type of a parameter in a generic message's parameter table.

            Mirrors <c>ParamDescriptor::ParamType</c> in CANlib's <c>CanMessageGenericTableFormat.h</c>. The
            value never appears on the wire, but its low nibble is the element size in bytes, which is what
            decides how much room the parameter takes in the packed data, so these have to keep CANlib's
            numbering for both sides to pack a message identically.
            """);
        using (writer.Block("public enum CanParamType : byte", "}"))
        {
            writer.Outdent();
            writer.Line("{");
            writer.Indent();
            writer.XmlDocRaw("Absent, and the terminator of a parameter table");
            writer.Line("None = 0x00,");
            foreach (ParamType type in ParamTypes.Ordered)
            {
                writer.Line();
                writer.XmlDocRaw($"CANlib's <c>ParamDescriptor::{type.CppEnumerator}</c>"
                    + (type.IsArray
                        ? ", a length byte followed by that many elements"
                        : type.ItemSize == 0 ? ", a null-terminated string" : $", {type.ItemSize} byte(s)"));
                writer.Line($"{type.CSharpName} = 0x{type.Value:X2},");
            }
        }
        writer.Line();
    }

    private static void EmitParamDescriptor(CodeWriter writer)
    {
        writer.XmlDocRaw("""
            One possible parameter of a generic message, identified by its G-code letter.
            """);
        writer.Line("/// <param name=\"Letter\">G-code letter that identifies the parameter. A letter outside A..Z marks a retired table entry: the position is still reserved so that the entries after it do not shift, but the parameter is never sent.</param>");
        writer.Line("/// <param name=\"Type\">How the value is packed into the message data.</param>");
        writer.Line("/// <param name=\"MaxArrayLength\">Number of elements, for the array types only.</param>");
        using (writer.Block("public readonly record struct CanParamDescriptor(char Letter, CanParamType Type, byte MaxArrayLength)", "}"))
        {
            writer.Outdent();
            writer.Line("{");
            writer.Indent();
            writer.XmlDocRaw("Size of one element in bytes, or 0 for the string types, which are null-terminated");
            writer.Line("public int ItemSize => (int)Type & 0x0F;");
            writer.Line();
            writer.XmlDocRaw("True if the value is a length byte followed by that many elements");
            writer.Line("public bool IsArray => ((int)Type & 0x80) != 0;");
            writer.Line();
            writer.XmlDocRaw("""
                True if a G-code command may supply this parameter, i.e. its letter is in A..Z.

                CANlib puts a parameter outside A..Z to keep it away from G-code while holding its table
                position, so that the parameters after it stay on the bits the receiver expects. Some of
                those are retired entries that are never sent at all (M569.1's <c>h</c>); others carry a
                value the sender fills in itself, such as the driver number in M915's <c>d</c>. The two
                cannot be told apart from the table, so the rule is only about where a value may come from:
                never from a command, always available to a caller that knows what it is doing.
                """);
            writer.Line("public bool CanComeFromGCode => Letter is >= 'A' and <= 'Z';");
        }
        writer.Line();
    }

    private void EmitTables(CodeWriter writer)
    {
        writer.XmlDocRaw("""
            The parameter tables of the generic CAN messages, mirroring CANlib's <c>CanMessageGenericTables.h</c>.

            For backwards compatibility a new parameter must be added at the end of its table: the paramMap
            bit and the packing order both follow the position in the table, so inserting one anywhere else
            would silently change the meaning of every message built from it.
            """);
        using (writer.Block("public static class CanGenericTables", "}"))
        {
            writer.Outdent();
            writer.Line("{");
            writer.Indent();

            bool first = true;
            foreach (GenericTableDef table in schema.GenericTables.Where(t => t.IsGenerated(Language.CSharp)))
            {
                if (!first)
                {
                    writer.Line();
                }
                first = false;

                // The schema's own prose has to be escaped; the sentence added below is markup on purpose
                string doc = table.Doc is null ? $"Parameters of {table.BaseName}" : CodeWriter.Escape(table.Doc);
                doc += $"\nSent as <see cref=\"CanMessageType.{Naming.MessageTypeMember(table.MessageType!)}\" />.";
                writer.XmlDocRaw(doc);
                using (writer.Block($"public static ImmutableArray<CanParamDescriptor> {table.Name} {{ get; }} =", "];"))
                {
                    writer.Outdent();
                    writer.Line("[");
                    writer.Indent();
                    foreach (GenericParamDef param in table.Params)
                    {
                        string entry = $"new('{param.Letter}', CanParamType.{param.Type.CSharpName}, {param.MaxLength}),";
                        writer.Line(param.Doc is null ? entry : $"{entry,-64} // {param.Doc}");
                    }
                }
            }
        }
        writer.Line();
    }
}
