using CanMessageGenerator.Model;

namespace CanMessageGenerator.Emit;

/// <summary>
/// Emits the C# <c>CanMessageType</c> enum.
/// </summary>
/// <remarks>
/// This is the id that identifies a message on the bus, so it is the one thing that has to agree with CANlib
/// even more surely than the layouts: a message with the wrong type is not misread, it is delivered to the
/// wrong handler. It used to be transcribed by hand next to a TODO asking for exactly this.
/// <para>
/// Retired ids are emitted as comments rather than dropped. The comment is the record that the number is
/// spent — reusing one would have an expansion board on older firmware act on a message that now means
/// something else.
/// </para>
/// </remarks>
public sealed class CSharpEnumEmitter(CanSchema schema)
{
    public string Emit()
    {
        MessageTypeEnumDef definition = schema.MessageTypes
            ?? throw new InvalidDataException("the schema declares no messageTypes");

        CodeWriter writer = new("    ");
        writer.Line("// <auto-generated>");
        writer.Line("//     Generated by tools/CanMessageGenerator from Schema/can-messages.json.");
        writer.Line("//     Do not edit this file directly: edit the schema and re-run the generator, otherwise");
        writer.Line("//     these ids will drift away from CANlib's CanId.h and messages will be misrouted.");
        writer.Line("// </auto-generated>");
        writer.Line();
        writer.Line($"namespace {schema.CSharpSharedNamespace};");
        writer.Line();

        writer.XmlDoc(definition.Doc);
        using (writer.Block($"public enum {definition.Name} : ushort", "}"))
        {
            writer.Outdent();
            writer.Line("{");
            writer.Indent();

            bool needsBlank = false;
            foreach (MessageTypeDef entry in definition.Values)
            {
                if (entry.Section is not null)
                {
                    writer.Line();
                    writer.Line($"// {entry.Section}");
                    needsBlank = false;
                    continue;
                }
                if (!entry.IsGenerated(Language.CSharp))
                {
                    continue;
                }

                string name = Naming.MessageTypeMember(entry.Name);
                if (entry.Retired)
                {
                    // Kept as a comment so the id is visibly spent rather than free to reuse
                    writer.Line($"// {name} = {entry.Value},{Trailing(entry.Doc)}");
                    needsBlank = false;
                    continue;
                }

                if (entry.Doc is not null)
                {
                    if (needsBlank)
                    {
                        writer.Line();
                    }
                    writer.XmlDoc(entry.Doc);
                }
                string value = entry.IsAlias ? Naming.MessageTypeMember(entry.Value) : entry.Value;
                writer.Line($"{name} = {value},");
                needsBlank = entry.Doc is not null;
            }
        }
        return writer.ToString();
    }

    private static string Trailing(string? doc) => doc is null ? "" : $" // {doc}";
}
