using CanMessageGenerator.Model;

namespace CanMessageGenerator.Emit;

/// <summary>
/// Emits the C# side of the generic message parameter tables.
/// </summary>
/// <remarks>
/// The table is the contract between the two ends of the link: the sender packs the parameters it is
/// sending in table order and sets the matching bit of the message's paramMap, and the receiver walks the
/// same table to work out where each value is. So the C# tables have to agree with CANlib's entry for
/// entry, which is what the generated conformance fixture checks.
/// </remarks>
public sealed class CSharpTablesEmitter(CanSchema schema)
{
    public string Emit()
    {
        CodeWriter writer = new("    ");
        writer.Line("// <auto-generated>");
        writer.Line("//     Generated by tools/CanMessageGenerator from Schema/can-messages.json.");
        writer.Line("//     Do not edit this file directly: edit the schema and re-run the generator, otherwise");
        writer.Line("//     the C# and C++ parameter tables will drift apart.");
        writer.Line("// </auto-generated>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("using System;");
        writer.Line("using System.Collections.Immutable;");
        foreach (string u in schema.CSharpUsings)
        {
            writer.Line($"using {u};");
        }
        writer.Line();
        writer.Line($"namespace {schema.CSharpNamespace};");
        writer.Line();

        EmitParamType(writer);
        EmitParamDescriptor(writer);
        EmitTables(writer);
        return writer.ToString();
    }

    private static void EmitParamType(CodeWriter writer)
    {
        writer.XmlDocRaw("""
            Type of a parameter in a generic message's parameter table.

            Mirrors <c>ParamDescriptor::ParamType</c> in CANlib's <c>CanMessageGenericTableFormat.h</c>. The
            value never appears on the wire, but its low nibble is the element size in bytes, which is what
            decides how much room the parameter takes in the packed data, so these have to keep CANlib's
            numbering for both sides to pack a message identically.
            """);
        using (writer.Block("public enum CanParamType : byte", "}"))
        {
            writer.Outdent();
            writer.Line("{");
            writer.Indent();
            writer.XmlDocRaw("Absent, and the terminator of a parameter table");
            writer.Line("None = 0x00,");
            foreach (ParamType type in ParamTypes.Ordered)
            {
                writer.Line();
                writer.XmlDocRaw($"CANlib's <c>ParamDescriptor::{type.CppEnumerator}</c>"
                    + (type.IsArray
                        ? ", a length byte followed by that many elements"
                        : type.ItemSize == 0 ? ", a null-terminated string" : $", {type.ItemSize} byte(s)"));
                writer.Line($"{type.CSharpName} = 0x{type.Value:X2},");
            }
        }
        writer.Line();
    }

    private static void EmitParamDescriptor(CodeWriter writer)
    {
        writer.XmlDocRaw("""
            One possible parameter of a generic message, identified by its G-code letter.
            """);
        writer.Line("/// <param name=\"Letter\">G-code letter that identifies the parameter. A letter outside A..Z marks a retired table entry: the position is still reserved so that the entries after it do not shift, but the parameter is never sent.</param>");
        writer.Line("/// <param name=\"Type\">How the value is packed into the message data.</param>");
        writer.Line("/// <param name=\"MaxArrayLength\">Number of elements, for the array types only.</param>");
        using (writer.Block("public readonly record struct CanParamDescriptor(char Letter, CanParamType Type, byte MaxArrayLength)", "}"))
        {
            writer.Outdent();
            writer.Line("{");
            writer.Indent();
            writer.XmlDocRaw("Size of one element in bytes, or 0 for the string types, which are null-terminated");
            writer.Line("public int ItemSize => (int)Type & 0x0F;");
            writer.Line();
            writer.XmlDocRaw("True if the value is a length byte followed by that many elements");
            writer.Line("public bool IsArray => ((int)Type & 0x80) != 0;");
            writer.Line();
            writer.XmlDocRaw("True if this entry only reserves a table position and can never be sent");
            writer.Line("public bool IsRetired => Letter is < 'A' or > 'Z';");
        }
        writer.Line();
    }

    private void EmitTables(CodeWriter writer)
    {
        writer.XmlDocRaw("""
            The parameter tables of the generic CAN messages, mirroring CANlib's <c>CanMessageGenericTables.h</c>.

            For backwards compatibility a new parameter must be added at the end of its table: the paramMap
            bit and the packing order both follow the position in the table, so inserting one anywhere else
            would silently change the meaning of every message built from it.
            """);
        using (writer.Block("public static class CanGenericTables", "}"))
        {
            writer.Outdent();
            writer.Line("{");
            writer.Indent();

            bool first = true;
            foreach (GenericTableDef table in schema.GenericTables)
            {
                if (!first)
                {
                    writer.Line();
                }
                first = false;

                // The schema's own prose has to be escaped; the sentence added below is markup on purpose
                string doc = table.Doc is null ? $"Parameters of {table.BaseName}" : CodeWriter.Escape(table.Doc);
                if (table.MessageType is not null)
                {
                    doc += $"\nSent as <see cref=\"CanMessageType.{Naming.MessageTypeMember(table.MessageType)}\" />.";
                }
                writer.XmlDocRaw(doc);
                using (writer.Block($"public static ImmutableArray<CanParamDescriptor> {table.Name} {{ get; }} =", "];"))
                {
                    writer.Outdent();
                    writer.Line("[");
                    writer.Indent();
                    foreach (GenericParamDef param in table.Params)
                    {
                        string entry = $"new('{param.Letter}', CanParamType.{param.Type.CSharpName}, {param.MaxLength}),";
                        writer.Line(param.Doc is null ? entry : $"{entry,-64} // {param.Doc}");
                    }
                }
            }
        }
        writer.Line();
    }
}
