namespace DuetControlServer.SPI.Communication.LinuxRequests
{
    /// <summary>
    /// Request indices for SPI transfers from the Linux board to the RepRapFirmware controller
    /// </summary>
    public enum Request : ushort
    {
        /// <summary>
        /// Perform an immediate emergency stop
        /// </summary>
        EmergencyStop = 0,
        
        /// <summary>
        /// Reset the controller
        /// </summary>
        Reset = 1,
        
        /// <summary>
        /// Request the execution of a G/M/T-code
        /// </summary>
        /// <seealso cref="CodeHeader"/>
        Code = 2,

        /// <summary>
        /// Request a part of the machine's object model
        /// </summary>
        /// <seealso cref="SharedRequests.ObjectModel"/>
        GetObjectModel = 3,
        
        /// <summary>
        /// Set a value in the machine's object model (reserved)
        /// </summary>
        /// <seealso cref="LinuxRequests.SetObjectModel"/>
        SetObjectModel = 4,
        
        /// <summary>
        /// Tell the firmware a print has started and set information about the file being processed
        /// </summary>
        /// <seealso cref="LinuxRequests.PrintStarted"/>
        PrintStarted = 5,
        
        /// <summary>
        /// Tell the firmware a print has been stopped and reset information about the file being processed
        /// </summary>
        /// <seealso cref="LinuxRequests.PrintStopped"/>
        PrintStopped = 6,
        
        /// <summary>
        /// Notify the firmware about the completion of a macro file
        /// </summary>
        /// <seealso cref="LinuxRequests.MacroCompleted"/>
        MacroCompleted = 7,

        /// <summary>
        /// Request the heightmap coordinates as generated by G29 S0
        /// </summary>
        GetHeightMap = 8,

        /// <summary>
        /// Set the heightmap coordinates via G29 S1
        /// </summary>
        SetHeightMap = 9,

        /// <summary>
        /// Lock movement and wait for standstill
        /// </summary>
        LockMovementAndWaitForStandstill = 10,

        /// <summary>
        /// Unlock everything again
        /// </summary>
        Unlock = 11
    }
}