// <auto-generated>
//     Generated by tools/CanMessageGenerator from Schema/can-messages.json.
//
//     Checks that the generated C# parameter tables hold exactly the entries the schema
//     describes, which is what the C++ probe checks against CANlib's own tables.
// </auto-generated>

using System.Collections.Immutable;
using NUnit.Framework;
using DuetControlServer.Link.Protocol.CanMessages;

namespace UnitTests.Link;

[TestFixture]
public class CanGenericTableLayout
{
    [Test]
    public void ParamTypeValuesMatchCanLib()
    {
        Assert.That((byte)CanParamType.None, Is.EqualTo(0x00), "value of CanParamType.None");
        Assert.That((byte)CanParamType.UInt64, Is.EqualTo(0x08), "value of CanParamType.UInt64");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt64, 0).ItemSize, Is.EqualTo(8), "item size of CanParamType.UInt64");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt64, 0).IsArray, Is.False, "CanParamType.UInt64 array flag");
        Assert.That((byte)CanParamType.UInt32, Is.EqualTo(0x04), "value of CanParamType.UInt32");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt32, 0).ItemSize, Is.EqualTo(4), "item size of CanParamType.UInt32");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt32, 0).IsArray, Is.False, "CanParamType.UInt32 array flag");
        Assert.That((byte)CanParamType.UInt16, Is.EqualTo(0x02), "value of CanParamType.UInt16");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt16, 0).ItemSize, Is.EqualTo(2), "item size of CanParamType.UInt16");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt16, 0).IsArray, Is.False, "CanParamType.UInt16 array flag");
        Assert.That((byte)CanParamType.UInt8, Is.EqualTo(0x01), "value of CanParamType.UInt8");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt8, 0).ItemSize, Is.EqualTo(1), "item size of CanParamType.UInt8");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt8, 0).IsArray, Is.False, "CanParamType.UInt8 array flag");
        Assert.That((byte)CanParamType.Int32, Is.EqualTo(0x14), "value of CanParamType.Int32");
        Assert.That(new CanParamDescriptor('A', CanParamType.Int32, 0).ItemSize, Is.EqualTo(4), "item size of CanParamType.Int32");
        Assert.That(new CanParamDescriptor('A', CanParamType.Int32, 0).IsArray, Is.False, "CanParamType.Int32 array flag");
        Assert.That((byte)CanParamType.Int16, Is.EqualTo(0x12), "value of CanParamType.Int16");
        Assert.That(new CanParamDescriptor('A', CanParamType.Int16, 0).ItemSize, Is.EqualTo(2), "item size of CanParamType.Int16");
        Assert.That(new CanParamDescriptor('A', CanParamType.Int16, 0).IsArray, Is.False, "CanParamType.Int16 array flag");
        Assert.That((byte)CanParamType.Int8, Is.EqualTo(0x11), "value of CanParamType.Int8");
        Assert.That(new CanParamDescriptor('A', CanParamType.Int8, 0).ItemSize, Is.EqualTo(1), "item size of CanParamType.Int8");
        Assert.That(new CanParamDescriptor('A', CanParamType.Int8, 0).IsArray, Is.False, "CanParamType.Int8 array flag");
        Assert.That((byte)CanParamType.String, Is.EqualTo(0x10), "value of CanParamType.String");
        Assert.That(new CanParamDescriptor('A', CanParamType.String, 0).ItemSize, Is.EqualTo(0), "item size of CanParamType.String");
        Assert.That(new CanParamDescriptor('A', CanParamType.String, 0).IsArray, Is.False, "CanParamType.String array flag");
        Assert.That((byte)CanParamType.Float, Is.EqualTo(0x24), "value of CanParamType.Float");
        Assert.That(new CanParamDescriptor('A', CanParamType.Float, 0).ItemSize, Is.EqualTo(4), "item size of CanParamType.Float");
        Assert.That(new CanParamDescriptor('A', CanParamType.Float, 0).IsArray, Is.False, "CanParamType.Float array flag");
        Assert.That((byte)CanParamType.PwmFreq, Is.EqualTo(0x22), "value of CanParamType.PwmFreq");
        Assert.That(new CanParamDescriptor('A', CanParamType.PwmFreq, 0).ItemSize, Is.EqualTo(2), "item size of CanParamType.PwmFreq");
        Assert.That(new CanParamDescriptor('A', CanParamType.PwmFreq, 0).IsArray, Is.False, "CanParamType.PwmFreq array flag");
        Assert.That((byte)CanParamType.Char, Is.EqualTo(0x21), "value of CanParamType.Char");
        Assert.That(new CanParamDescriptor('A', CanParamType.Char, 0).ItemSize, Is.EqualTo(1), "item size of CanParamType.Char");
        Assert.That(new CanParamDescriptor('A', CanParamType.Char, 0).IsArray, Is.False, "CanParamType.Char array flag");
        Assert.That((byte)CanParamType.ReducedString, Is.EqualTo(0x20), "value of CanParamType.ReducedString");
        Assert.That(new CanParamDescriptor('A', CanParamType.ReducedString, 0).ItemSize, Is.EqualTo(0), "item size of CanParamType.ReducedString");
        Assert.That(new CanParamDescriptor('A', CanParamType.ReducedString, 0).IsArray, Is.False, "CanParamType.ReducedString array flag");
        Assert.That((byte)CanParamType.LocalDriver, Is.EqualTo(0x41), "value of CanParamType.LocalDriver");
        Assert.That(new CanParamDescriptor('A', CanParamType.LocalDriver, 0).ItemSize, Is.EqualTo(1), "item size of CanParamType.LocalDriver");
        Assert.That(new CanParamDescriptor('A', CanParamType.LocalDriver, 0).IsArray, Is.False, "CanParamType.LocalDriver array flag");
        Assert.That((byte)CanParamType.Float16, Is.EqualTo(0x42), "value of CanParamType.Float16");
        Assert.That(new CanParamDescriptor('A', CanParamType.Float16, 0).ItemSize, Is.EqualTo(2), "item size of CanParamType.Float16");
        Assert.That(new CanParamDescriptor('A', CanParamType.Float16, 0).IsArray, Is.False, "CanParamType.Float16 array flag");
        Assert.That((byte)CanParamType.UInt32Array, Is.EqualTo(0x84), "value of CanParamType.UInt32Array");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt32Array, 0).ItemSize, Is.EqualTo(4), "item size of CanParamType.UInt32Array");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt32Array, 0).IsArray, Is.True, "CanParamType.UInt32Array array flag");
        Assert.That((byte)CanParamType.UInt16Array, Is.EqualTo(0x82), "value of CanParamType.UInt16Array");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt16Array, 0).ItemSize, Is.EqualTo(2), "item size of CanParamType.UInt16Array");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt16Array, 0).IsArray, Is.True, "CanParamType.UInt16Array array flag");
        Assert.That((byte)CanParamType.UInt8Array, Is.EqualTo(0x81), "value of CanParamType.UInt8Array");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt8Array, 0).ItemSize, Is.EqualTo(1), "item size of CanParamType.UInt8Array");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt8Array, 0).IsArray, Is.True, "CanParamType.UInt8Array array flag");
        Assert.That((byte)CanParamType.FloatArray, Is.EqualTo(0xA4), "value of CanParamType.FloatArray");
        Assert.That(new CanParamDescriptor('A', CanParamType.FloatArray, 0).ItemSize, Is.EqualTo(4), "item size of CanParamType.FloatArray");
        Assert.That(new CanParamDescriptor('A', CanParamType.FloatArray, 0).IsArray, Is.True, "CanParamType.FloatArray array flag");
    }

    [Test]
    public void M42Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M42Params;
        Assert.That(table.Length, Is.EqualTo(2), "number of entries in M42Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.UInt16, 0)), "M42Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('S', CanParamType.Float, 0)), "M42Params[1]");
    }

    [Test]
    public void M150Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M150Params;
        Assert.That(table.Length, Is.EqualTo(9), "number of entries in M150Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('E', CanParamType.UInt16, 0)), "M150Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt16, 0)), "M150Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('R', CanParamType.UInt8, 0)), "M150Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('U', CanParamType.UInt8, 0)), "M150Params[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('B', CanParamType.UInt8, 0)), "M150Params[4]");
        Assert.That(table[5], Is.EqualTo(new CanParamDescriptor('W', CanParamType.UInt8, 0)), "M150Params[5]");
        Assert.That(table[6], Is.EqualTo(new CanParamDescriptor('P', CanParamType.UInt8, 0)), "M150Params[6]");
        Assert.That(table[7], Is.EqualTo(new CanParamDescriptor('Y', CanParamType.UInt8, 0)), "M150Params[7]");
        Assert.That(table[8], Is.EqualTo(new CanParamDescriptor('F', CanParamType.UInt8, 0)), "M150Params[8]");
    }

    [Test]
    public void M280Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M280Params;
        Assert.That(table.Length, Is.EqualTo(2), "number of entries in M280Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.UInt16, 0)), "M280Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt16, 0)), "M280Params[1]");
    }

    [Test]
    public void M308V1Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M308V1Params;
        Assert.That(table.Length, Is.EqualTo(14), "number of entries in M308V1Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('T', CanParamType.Float, 0)), "M308V1Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('B', CanParamType.Float, 0)), "M308V1Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('C', CanParamType.Float, 0)), "M308V1Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('R', CanParamType.Float, 0)), "M308V1Params[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('L', CanParamType.Int16, 0)), "M308V1Params[4]");
        Assert.That(table[5], Is.EqualTo(new CanParamDescriptor('H', CanParamType.Int16, 0)), "M308V1Params[5]");
        Assert.That(table[6], Is.EqualTo(new CanParamDescriptor('F', CanParamType.UInt8, 0)), "M308V1Params[6]");
        Assert.That(table[7], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt8, 0)), "M308V1Params[7]");
        Assert.That(table[8], Is.EqualTo(new CanParamDescriptor('W', CanParamType.UInt8, 0)), "M308V1Params[8]");
        Assert.That(table[9], Is.EqualTo(new CanParamDescriptor('K', CanParamType.Char, 0)), "M308V1Params[9]");
        Assert.That(table[10], Is.EqualTo(new CanParamDescriptor('Y', CanParamType.ReducedString, 0)), "M308V1Params[10]");
        Assert.That(table[11], Is.EqualTo(new CanParamDescriptor('P', CanParamType.ReducedString, 0)), "M308V1Params[11]");
        Assert.That(table[12], Is.EqualTo(new CanParamDescriptor('U', CanParamType.Float16, 0)), "M308V1Params[12]");
        Assert.That(table[13], Is.EqualTo(new CanParamDescriptor('V', CanParamType.Float16, 0)), "M308V1Params[13]");
    }

    [Test]
    public void M569Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M569Params;
        Assert.That(table.Length, Is.EqualTo(11), "number of entries in M569Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.LocalDriver, 0)), "M569Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt8, 0)), "M569Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('R', CanParamType.Int8, 0)), "M569Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('D', CanParamType.UInt8, 0)), "M569Params[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('F', CanParamType.UInt8, 0)), "M569Params[4]");
        Assert.That(table[5], Is.EqualTo(new CanParamDescriptor('B', CanParamType.UInt8, 0)), "M569Params[5]");
        Assert.That(table[6], Is.EqualTo(new CanParamDescriptor('H', CanParamType.UInt16, 0)), "M569Params[6]");
        Assert.That(table[7], Is.EqualTo(new CanParamDescriptor('V', CanParamType.UInt16, 0)), "M569Params[7]");
        Assert.That(table[8], Is.EqualTo(new CanParamDescriptor('Y', CanParamType.UInt8Array, 3)), "M569Params[8]");
        Assert.That(table[9], Is.EqualTo(new CanParamDescriptor('T', CanParamType.FloatArray, 4)), "M569Params[9]");
        Assert.That(table[10], Is.EqualTo(new CanParamDescriptor('U', CanParamType.Int8, 0)), "M569Params[10]");
    }

    [Test]
    public void M569Point1Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M569Point1Params;
        Assert.That(table.Length, Is.EqualTo(13), "number of entries in M569Point1Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.LocalDriver, 0)), "M569Point1Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('T', CanParamType.UInt8, 0)), "M569Point1Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('E', CanParamType.FloatArray, 2)), "M569Point1Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('C', CanParamType.Float, 0)), "M569Point1Params[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('R', CanParamType.Float, 0)), "M569Point1Params[4]");
        Assert.That(table[5], Is.EqualTo(new CanParamDescriptor('I', CanParamType.Float, 0)), "M569Point1Params[5]");
        Assert.That(table[6], Is.EqualTo(new CanParamDescriptor('D', CanParamType.Float, 0)), "M569Point1Params[6]");
        Assert.That(table[7], Is.EqualTo(new CanParamDescriptor('h', CanParamType.Float, 0)), "M569Point1Params[7]");
        Assert.That(table[8], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt16, 0)), "M569Point1Params[8]");
        Assert.That(table[9], Is.EqualTo(new CanParamDescriptor('V', CanParamType.Float, 0)), "M569Point1Params[9]");
        Assert.That(table[10], Is.EqualTo(new CanParamDescriptor('A', CanParamType.Float, 0)), "M569Point1Params[10]");
        Assert.That(table[11], Is.EqualTo(new CanParamDescriptor('Q', CanParamType.Float, 0)), "M569Point1Params[11]");
        Assert.That(table[12], Is.EqualTo(new CanParamDescriptor('Y', CanParamType.ReducedString, 0)), "M569Point1Params[12]");
    }

    [Test]
    public void M569Point2Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M569Point2Params;
        Assert.That(table.Length, Is.EqualTo(3), "number of entries in M569Point2Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.LocalDriver, 0)), "M569Point2Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('R', CanParamType.UInt8, 0)), "M569Point2Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('V', CanParamType.UInt32, 0)), "M569Point2Params[2]");
    }

    [Test]
    public void M569Point4Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M569Point4Params;
        Assert.That(table.Length, Is.EqualTo(3), "number of entries in M569Point4Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.LocalDriver, 0)), "M569Point4Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('T', CanParamType.Float, 0)), "M569Point4Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('V', CanParamType.Float, 0)), "M569Point4Params[2]");
    }

    [Test]
    public void M569Point6Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M569Point6Params;
        Assert.That(table.Length, Is.EqualTo(4), "number of entries in M569Point6Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.LocalDriver, 0)), "M569Point6Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('V', CanParamType.UInt8, 0)), "M569Point6Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('S', CanParamType.Float, 0)), "M569Point6Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('A', CanParamType.Float, 0)), "M569Point6Params[3]");
    }

    [Test]
    public void M569Point6Params_StatusOnly_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M569Point6Params_StatusOnly;
        Assert.That(table.Length, Is.EqualTo(2), "number of entries in M569Point6Params_StatusOnly");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.LocalDriver, 0)), "M569Point6Params_StatusOnly[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('v', CanParamType.UInt8, 0)), "M569Point6Params_StatusOnly[1]");
    }

    [Test]
    public void M569Point7Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M569Point7Params;
        Assert.That(table.Length, Is.EqualTo(4), "number of entries in M569Point7Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.LocalDriver, 0)), "M569Point7Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('C', CanParamType.ReducedString, 0)), "M569Point7Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('V', CanParamType.Float, 0)), "M569Point7Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt16, 0)), "M569Point7Params[3]");
    }

    [Test]
    public void M915Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M915Params;
        Assert.That(table.Length, Is.EqualTo(6), "number of entries in M915Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('d', CanParamType.UInt16, 0)), "M915Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('S', CanParamType.Int8, 0)), "M915Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('F', CanParamType.UInt8, 0)), "M915Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('H', CanParamType.UInt16, 0)), "M915Params[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('T', CanParamType.UInt16, 0)), "M915Params[4]");
        Assert.That(table[5], Is.EqualTo(new CanParamDescriptor('R', CanParamType.UInt8, 0)), "M915Params[5]");
    }

    [Test]
    public void M950HeaterParams_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M950HeaterParams;
        Assert.That(table.Length, Is.EqualTo(5), "number of entries in M950HeaterParams");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('H', CanParamType.UInt16, 0)), "M950HeaterParams[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('Q', CanParamType.PwmFreq, 0)), "M950HeaterParams[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('T', CanParamType.UInt16, 0)), "M950HeaterParams[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('C', CanParamType.ReducedString, 0)), "M950HeaterParams[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('B', CanParamType.Int16, 0)), "M950HeaterParams[4]");
    }

    [Test]
    public void M950FanParams_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M950FanParams;
        Assert.That(table.Length, Is.EqualTo(4), "number of entries in M950FanParams");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('F', CanParamType.UInt16, 0)), "M950FanParams[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('Q', CanParamType.PwmFreq, 0)), "M950FanParams[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('C', CanParamType.ReducedString, 0)), "M950FanParams[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('K', CanParamType.Float, 0)), "M950FanParams[3]");
    }

    [Test]
    public void M950GpioParams_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M950GpioParams;
        Assert.That(table.Length, Is.EqualTo(4), "number of entries in M950GpioParams");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.UInt16, 0)), "M950GpioParams[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('Q', CanParamType.PwmFreq, 0)), "M950GpioParams[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt8, 0)), "M950GpioParams[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('C', CanParamType.ReducedString, 0)), "M950GpioParams[3]");
    }

    [Test]
    public void M950LedParams_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M950LedParams;
        Assert.That(table.Length, Is.EqualTo(7), "number of entries in M950LedParams");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('E', CanParamType.UInt16, 0)), "M950LedParams[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('U', CanParamType.UInt16, 0)), "M950LedParams[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('Q', CanParamType.UInt32, 0)), "M950LedParams[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('T', CanParamType.UInt8, 0)), "M950LedParams[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('C', CanParamType.ReducedString, 0)), "M950LedParams[4]");
        Assert.That(table[5], Is.EqualTo(new CanParamDescriptor('L', CanParamType.UInt16Array, 4)), "M950LedParams[5]");
        Assert.That(table[6], Is.EqualTo(new CanParamDescriptor('K', CanParamType.UInt8, 0)), "M950LedParams[6]");
    }

    [Test]
    public void ConfigureFilamentMonitorParams_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.ConfigureFilamentMonitorParams;
        Assert.That(table.Length, Is.EqualTo(7), "number of entries in ConfigureFilamentMonitorParams");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('d', CanParamType.UInt8, 0)), "ConfigureFilamentMonitorParams[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt8, 0)), "ConfigureFilamentMonitorParams[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('A', CanParamType.UInt8, 0)), "ConfigureFilamentMonitorParams[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('L', CanParamType.Float, 0)), "ConfigureFilamentMonitorParams[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('E', CanParamType.Float, 0)), "ConfigureFilamentMonitorParams[4]");
        Assert.That(table[5], Is.EqualTo(new CanParamDescriptor('R', CanParamType.UInt16Array, 2)), "ConfigureFilamentMonitorParams[5]");
        Assert.That(table[6], Is.EqualTo(new CanParamDescriptor('C', CanParamType.ReducedString, 0)), "ConfigureFilamentMonitorParams[6]");
    }

    [Test]
    public void M955Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M955Params;
        Assert.That(table.Length, Is.EqualTo(4), "number of entries in M955Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.LocalDriver, 0)), "M955Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('I', CanParamType.UInt8, 0)), "M955Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('R', CanParamType.UInt8, 0)), "M955Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt16, 0)), "M955Params[3]");
    }

    [Test]
    public void M122P1Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M122P1Params;
        Assert.That(table.Length, Is.EqualTo(5), "number of entries in M122P1Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('T', CanParamType.FloatArray, 2)), "M122P1Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('V', CanParamType.FloatArray, 2)), "M122P1Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('W', CanParamType.FloatArray, 2)), "M122P1Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('U', CanParamType.FloatArray, 2)), "M122P1Params[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('F', CanParamType.FloatArray, 2)), "M122P1Params[4]");
    }

    [Test]
    public void M655Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M655Params;
        Assert.That(table.Length, Is.EqualTo(7), "number of entries in M655Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('E', CanParamType.Float, 0)), "M655Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('F', CanParamType.Float, 0)), "M655Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('R', CanParamType.Int32, 0)), "M655Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('S', CanParamType.Int32, 0)), "M655Params[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('P', CanParamType.UInt16, 0)), "M655Params[4]");
        Assert.That(table[5], Is.EqualTo(new CanParamDescriptor('C', CanParamType.ReducedString, 0)), "M655Params[5]");
        Assert.That(table[6], Is.EqualTo(new CanParamDescriptor('A', CanParamType.String, 0)), "M655Params[6]");
    }

    [Test]
    public void M111Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M111Params;
        Assert.That(table.Length, Is.EqualTo(4), "number of entries in M111Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('D', CanParamType.UInt32, 0)), "M111Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('F', CanParamType.UInt16, 0)), "M111Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('P', CanParamType.UInt8, 0)), "M111Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt8, 0)), "M111Params[3]");
    }

    [Test]
    public void M959Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M959Params;
        Assert.That(table.Length, Is.EqualTo(1), "number of entries in M959Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('T', CanParamType.UInt16, 0)), "M959Params[0]");
    }

}
