// <auto-generated>
//     Generated by src/DuetCanMessage.SourceGenerators from Schema/can-messages.json.
//
//     Checks that the generated C# parameter tables hold exactly the entries the schema
//     describes, which is what the C++ probe checks against CANlib's own tables.
// </auto-generated>

using System.Collections.Immutable;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using NUnit.Framework;
using DuetControlServer.Link.Protocol.CanMessages;
using DuetControlServer.Link.Protocol.Shared;

namespace UnitTests.Link;

[TestFixture]
public class CanGenericTableLayout
{
    [Test]
    public void ParamTypeValuesMatchCanLib()
    {
        Assert.That((byte)CanParamType.None, Is.EqualTo(0x00), "value of CanParamType.None");
        Assert.That((byte)CanParamType.UInt64, Is.EqualTo(0x08), "value of CanParamType.UInt64");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt64, 0).ItemSize, Is.EqualTo(8), "item size of CanParamType.UInt64");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt64, 0).IsArray, Is.False, "CanParamType.UInt64 array flag");
        Assert.That((byte)CanParamType.UInt32, Is.EqualTo(0x04), "value of CanParamType.UInt32");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt32, 0).ItemSize, Is.EqualTo(4), "item size of CanParamType.UInt32");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt32, 0).IsArray, Is.False, "CanParamType.UInt32 array flag");
        Assert.That((byte)CanParamType.UInt16, Is.EqualTo(0x02), "value of CanParamType.UInt16");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt16, 0).ItemSize, Is.EqualTo(2), "item size of CanParamType.UInt16");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt16, 0).IsArray, Is.False, "CanParamType.UInt16 array flag");
        Assert.That((byte)CanParamType.UInt8, Is.EqualTo(0x01), "value of CanParamType.UInt8");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt8, 0).ItemSize, Is.EqualTo(1), "item size of CanParamType.UInt8");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt8, 0).IsArray, Is.False, "CanParamType.UInt8 array flag");
        Assert.That((byte)CanParamType.Int32, Is.EqualTo(0x14), "value of CanParamType.Int32");
        Assert.That(new CanParamDescriptor('A', CanParamType.Int32, 0).ItemSize, Is.EqualTo(4), "item size of CanParamType.Int32");
        Assert.That(new CanParamDescriptor('A', CanParamType.Int32, 0).IsArray, Is.False, "CanParamType.Int32 array flag");
        Assert.That((byte)CanParamType.Int16, Is.EqualTo(0x12), "value of CanParamType.Int16");
        Assert.That(new CanParamDescriptor('A', CanParamType.Int16, 0).ItemSize, Is.EqualTo(2), "item size of CanParamType.Int16");
        Assert.That(new CanParamDescriptor('A', CanParamType.Int16, 0).IsArray, Is.False, "CanParamType.Int16 array flag");
        Assert.That((byte)CanParamType.Int8, Is.EqualTo(0x11), "value of CanParamType.Int8");
        Assert.That(new CanParamDescriptor('A', CanParamType.Int8, 0).ItemSize, Is.EqualTo(1), "item size of CanParamType.Int8");
        Assert.That(new CanParamDescriptor('A', CanParamType.Int8, 0).IsArray, Is.False, "CanParamType.Int8 array flag");
        Assert.That((byte)CanParamType.String, Is.EqualTo(0x10), "value of CanParamType.String");
        Assert.That(new CanParamDescriptor('A', CanParamType.String, 0).ItemSize, Is.EqualTo(0), "item size of CanParamType.String");
        Assert.That(new CanParamDescriptor('A', CanParamType.String, 0).IsArray, Is.False, "CanParamType.String array flag");
        Assert.That((byte)CanParamType.Float, Is.EqualTo(0x24), "value of CanParamType.Float");
        Assert.That(new CanParamDescriptor('A', CanParamType.Float, 0).ItemSize, Is.EqualTo(4), "item size of CanParamType.Float");
        Assert.That(new CanParamDescriptor('A', CanParamType.Float, 0).IsArray, Is.False, "CanParamType.Float array flag");
        Assert.That((byte)CanParamType.PwmFreq, Is.EqualTo(0x22), "value of CanParamType.PwmFreq");
        Assert.That(new CanParamDescriptor('A', CanParamType.PwmFreq, 0).ItemSize, Is.EqualTo(2), "item size of CanParamType.PwmFreq");
        Assert.That(new CanParamDescriptor('A', CanParamType.PwmFreq, 0).IsArray, Is.False, "CanParamType.PwmFreq array flag");
        Assert.That((byte)CanParamType.Char, Is.EqualTo(0x21), "value of CanParamType.Char");
        Assert.That(new CanParamDescriptor('A', CanParamType.Char, 0).ItemSize, Is.EqualTo(1), "item size of CanParamType.Char");
        Assert.That(new CanParamDescriptor('A', CanParamType.Char, 0).IsArray, Is.False, "CanParamType.Char array flag");
        Assert.That((byte)CanParamType.ReducedString, Is.EqualTo(0x20), "value of CanParamType.ReducedString");
        Assert.That(new CanParamDescriptor('A', CanParamType.ReducedString, 0).ItemSize, Is.EqualTo(0), "item size of CanParamType.ReducedString");
        Assert.That(new CanParamDescriptor('A', CanParamType.ReducedString, 0).IsArray, Is.False, "CanParamType.ReducedString array flag");
        Assert.That((byte)CanParamType.LocalDriver, Is.EqualTo(0x41), "value of CanParamType.LocalDriver");
        Assert.That(new CanParamDescriptor('A', CanParamType.LocalDriver, 0).ItemSize, Is.EqualTo(1), "item size of CanParamType.LocalDriver");
        Assert.That(new CanParamDescriptor('A', CanParamType.LocalDriver, 0).IsArray, Is.False, "CanParamType.LocalDriver array flag");
        Assert.That((byte)CanParamType.Float16, Is.EqualTo(0x42), "value of CanParamType.Float16");
        Assert.That(new CanParamDescriptor('A', CanParamType.Float16, 0).ItemSize, Is.EqualTo(2), "item size of CanParamType.Float16");
        Assert.That(new CanParamDescriptor('A', CanParamType.Float16, 0).IsArray, Is.False, "CanParamType.Float16 array flag");
        Assert.That((byte)CanParamType.UInt32Array, Is.EqualTo(0x84), "value of CanParamType.UInt32Array");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt32Array, 0).ItemSize, Is.EqualTo(4), "item size of CanParamType.UInt32Array");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt32Array, 0).IsArray, Is.True, "CanParamType.UInt32Array array flag");
        Assert.That((byte)CanParamType.UInt16Array, Is.EqualTo(0x82), "value of CanParamType.UInt16Array");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt16Array, 0).ItemSize, Is.EqualTo(2), "item size of CanParamType.UInt16Array");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt16Array, 0).IsArray, Is.True, "CanParamType.UInt16Array array flag");
        Assert.That((byte)CanParamType.UInt8Array, Is.EqualTo(0x81), "value of CanParamType.UInt8Array");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt8Array, 0).ItemSize, Is.EqualTo(1), "item size of CanParamType.UInt8Array");
        Assert.That(new CanParamDescriptor('A', CanParamType.UInt8Array, 0).IsArray, Is.True, "CanParamType.UInt8Array array flag");
        Assert.That((byte)CanParamType.FloatArray, Is.EqualTo(0xA4), "value of CanParamType.FloatArray");
        Assert.That(new CanParamDescriptor('A', CanParamType.FloatArray, 0).ItemSize, Is.EqualTo(4), "item size of CanParamType.FloatArray");
        Assert.That(new CanParamDescriptor('A', CanParamType.FloatArray, 0).IsArray, Is.True, "CanParamType.FloatArray array flag");
    }

    [Test]
    public void GenericMessagesHaveTheLayoutOfCanMessageGeneric()
    {
        Assert.That(Unsafe.SizeOf<CanMessageM150>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM150");
        Assert.That(Marshal.OffsetOf<CanMessageM150>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM150.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM308V1>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM308V1");
        Assert.That(Marshal.OffsetOf<CanMessageM308V1>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM308V1.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM569>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM569");
        Assert.That(Marshal.OffsetOf<CanMessageM569>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM569.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM569Point1>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM569Point1");
        Assert.That(Marshal.OffsetOf<CanMessageM569Point1>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM569Point1.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM569Point2>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM569Point2");
        Assert.That(Marshal.OffsetOf<CanMessageM569Point2>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM569Point2.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM569Point4>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM569Point4");
        Assert.That(Marshal.OffsetOf<CanMessageM569Point4>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM569Point4.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM569Point6>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM569Point6");
        Assert.That(Marshal.OffsetOf<CanMessageM569Point6>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM569Point6.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM569Point6StatusOnly>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM569Point6StatusOnly");
        Assert.That(Marshal.OffsetOf<CanMessageM569Point6StatusOnly>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM569Point6StatusOnly.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM569Point7>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM569Point7");
        Assert.That(Marshal.OffsetOf<CanMessageM569Point7>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM569Point7.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM915>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM915");
        Assert.That(Marshal.OffsetOf<CanMessageM915>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM915.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM950Heater>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM950Heater");
        Assert.That(Marshal.OffsetOf<CanMessageM950Heater>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM950Heater.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM950Fan>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM950Fan");
        Assert.That(Marshal.OffsetOf<CanMessageM950Fan>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM950Fan.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM950Gpio>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM950Gpio");
        Assert.That(Marshal.OffsetOf<CanMessageM950Gpio>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM950Gpio.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM950Led>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM950Led");
        Assert.That(Marshal.OffsetOf<CanMessageM950Led>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM950Led.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageConfigureFilamentMonitor>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageConfigureFilamentMonitor");
        Assert.That(Marshal.OffsetOf<CanMessageConfigureFilamentMonitor>("Generic").ToInt32(), Is.Zero, "offset of CanMessageConfigureFilamentMonitor.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM955>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM955");
        Assert.That(Marshal.OffsetOf<CanMessageM955>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM955.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM122P1>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM122P1");
        Assert.That(Marshal.OffsetOf<CanMessageM122P1>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM122P1.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM655>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM655");
        Assert.That(Marshal.OffsetOf<CanMessageM655>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM655.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM111>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM111");
        Assert.That(Marshal.OffsetOf<CanMessageM111>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM111.Generic");
        Assert.That(Unsafe.SizeOf<CanMessageM959>(), Is.EqualTo(Unsafe.SizeOf<CanMessageGeneric>()), "size of CanMessageM959");
        Assert.That(Marshal.OffsetOf<CanMessageM959>("Generic").ToInt32(), Is.Zero, "offset of CanMessageM959.Generic");
    }

    [Test]
    public void GenericMessagesCarryTheMessageTypeOfTheirTable()
    {
        Assert.That(CanMessageM150.MessageType, Is.EqualTo(CanMessageType.WriteLedStrip), "message type of CanMessageM150");
        Assert.That(CanMessageM150.ParamTable, Is.EqualTo(CanGenericTables.M150Params), "parameter table of CanMessageM150");
        Assert.That(CanMessageM308V1.MessageType, Is.EqualTo(CanMessageType.M308V1), "message type of CanMessageM308V1");
        Assert.That(CanMessageM308V1.ParamTable, Is.EqualTo(CanGenericTables.M308V1Params), "parameter table of CanMessageM308V1");
        Assert.That(CanMessageM569.MessageType, Is.EqualTo(CanMessageType.M569), "message type of CanMessageM569");
        Assert.That(CanMessageM569.ParamTable, Is.EqualTo(CanGenericTables.M569Params), "parameter table of CanMessageM569");
        Assert.That(CanMessageM569Point1.MessageType, Is.EqualTo(CanMessageType.M569P1), "message type of CanMessageM569Point1");
        Assert.That(CanMessageM569Point1.ParamTable, Is.EqualTo(CanGenericTables.M569Point1Params), "parameter table of CanMessageM569Point1");
        Assert.That(CanMessageM569Point2.MessageType, Is.EqualTo(CanMessageType.M569P2), "message type of CanMessageM569Point2");
        Assert.That(CanMessageM569Point2.ParamTable, Is.EqualTo(CanGenericTables.M569Point2Params), "parameter table of CanMessageM569Point2");
        Assert.That(CanMessageM569Point4.MessageType, Is.EqualTo(CanMessageType.M569P4), "message type of CanMessageM569Point4");
        Assert.That(CanMessageM569Point4.ParamTable, Is.EqualTo(CanGenericTables.M569Point4Params), "parameter table of CanMessageM569Point4");
        Assert.That(CanMessageM569Point6.MessageType, Is.EqualTo(CanMessageType.M569P6), "message type of CanMessageM569Point6");
        Assert.That(CanMessageM569Point6.ParamTable, Is.EqualTo(CanGenericTables.M569Point6Params), "parameter table of CanMessageM569Point6");
        Assert.That(CanMessageM569Point6StatusOnly.MessageType, Is.EqualTo(CanMessageType.M569P6), "message type of CanMessageM569Point6StatusOnly");
        Assert.That(CanMessageM569Point6StatusOnly.ParamTable, Is.EqualTo(CanGenericTables.M569Point6Params_StatusOnly), "parameter table of CanMessageM569Point6StatusOnly");
        Assert.That(CanMessageM569Point7.MessageType, Is.EqualTo(CanMessageType.M569P7), "message type of CanMessageM569Point7");
        Assert.That(CanMessageM569Point7.ParamTable, Is.EqualTo(CanGenericTables.M569Point7Params), "parameter table of CanMessageM569Point7");
        Assert.That(CanMessageM915.MessageType, Is.EqualTo(CanMessageType.M915), "message type of CanMessageM915");
        Assert.That(CanMessageM915.ParamTable, Is.EqualTo(CanGenericTables.M915Params), "parameter table of CanMessageM915");
        Assert.That(CanMessageM950Heater.MessageType, Is.EqualTo(CanMessageType.M950Heater), "message type of CanMessageM950Heater");
        Assert.That(CanMessageM950Heater.ParamTable, Is.EqualTo(CanGenericTables.M950HeaterParams), "parameter table of CanMessageM950Heater");
        Assert.That(CanMessageM950Fan.MessageType, Is.EqualTo(CanMessageType.M950Fan), "message type of CanMessageM950Fan");
        Assert.That(CanMessageM950Fan.ParamTable, Is.EqualTo(CanGenericTables.M950FanParams), "parameter table of CanMessageM950Fan");
        Assert.That(CanMessageM950Gpio.MessageType, Is.EqualTo(CanMessageType.M950Gpio), "message type of CanMessageM950Gpio");
        Assert.That(CanMessageM950Gpio.ParamTable, Is.EqualTo(CanGenericTables.M950GpioParams), "parameter table of CanMessageM950Gpio");
        Assert.That(CanMessageM950Led.MessageType, Is.EqualTo(CanMessageType.M950Led), "message type of CanMessageM950Led");
        Assert.That(CanMessageM950Led.ParamTable, Is.EqualTo(CanGenericTables.M950LedParams), "parameter table of CanMessageM950Led");
        Assert.That(CanMessageConfigureFilamentMonitor.MessageType, Is.EqualTo(CanMessageType.ConfigureFilamentMonitor), "message type of CanMessageConfigureFilamentMonitor");
        Assert.That(CanMessageConfigureFilamentMonitor.ParamTable, Is.EqualTo(CanGenericTables.ConfigureFilamentMonitorParams), "parameter table of CanMessageConfigureFilamentMonitor");
        Assert.That(CanMessageM955.MessageType, Is.EqualTo(CanMessageType.AccelerometerConfig), "message type of CanMessageM955");
        Assert.That(CanMessageM955.ParamTable, Is.EqualTo(CanGenericTables.M955Params), "parameter table of CanMessageM955");
        Assert.That(CanMessageM122P1.MessageType, Is.EqualTo(CanMessageType.TestReport), "message type of CanMessageM122P1");
        Assert.That(CanMessageM122P1.ParamTable, Is.EqualTo(CanGenericTables.M122P1Params), "parameter table of CanMessageM122P1");
        Assert.That(CanMessageM655.MessageType, Is.EqualTo(CanMessageType.M655), "message type of CanMessageM655");
        Assert.That(CanMessageM655.ParamTable, Is.EqualTo(CanGenericTables.M655Params), "parameter table of CanMessageM655");
        Assert.That(CanMessageM111.MessageType, Is.EqualTo(CanMessageType.M111), "message type of CanMessageM111");
        Assert.That(CanMessageM111.ParamTable, Is.EqualTo(CanGenericTables.M111Params), "parameter table of CanMessageM111");
        Assert.That(CanMessageM959.MessageType, Is.EqualTo(CanMessageType.SetConnectionTimeout), "message type of CanMessageM959");
        Assert.That(CanMessageM959.ParamTable, Is.EqualTo(CanGenericTables.M959Params), "parameter table of CanMessageM959");
    }

    [Test]
    public void M150Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M150Params;
        Assert.That(table.Length, Is.EqualTo(9), "number of entries in M150Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('E', CanParamType.UInt16, 0)), "M150Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt16, 0)), "M150Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('R', CanParamType.UInt8, 0)), "M150Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('U', CanParamType.UInt8, 0)), "M150Params[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('B', CanParamType.UInt8, 0)), "M150Params[4]");
        Assert.That(table[5], Is.EqualTo(new CanParamDescriptor('W', CanParamType.UInt8, 0)), "M150Params[5]");
        Assert.That(table[6], Is.EqualTo(new CanParamDescriptor('P', CanParamType.UInt8, 0)), "M150Params[6]");
        Assert.That(table[7], Is.EqualTo(new CanParamDescriptor('Y', CanParamType.UInt8, 0)), "M150Params[7]");
        Assert.That(table[8], Is.EqualTo(new CanParamDescriptor('F', CanParamType.UInt8, 0)), "M150Params[8]");
    }

    [Test]
    public void M308V1Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M308V1Params;
        Assert.That(table.Length, Is.EqualTo(14), "number of entries in M308V1Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('T', CanParamType.Float, 0)), "M308V1Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('B', CanParamType.Float, 0)), "M308V1Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('C', CanParamType.Float, 0)), "M308V1Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('R', CanParamType.Float, 0)), "M308V1Params[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('L', CanParamType.Int16, 0)), "M308V1Params[4]");
        Assert.That(table[5], Is.EqualTo(new CanParamDescriptor('H', CanParamType.Int16, 0)), "M308V1Params[5]");
        Assert.That(table[6], Is.EqualTo(new CanParamDescriptor('F', CanParamType.UInt8, 0)), "M308V1Params[6]");
        Assert.That(table[7], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt8, 0)), "M308V1Params[7]");
        Assert.That(table[8], Is.EqualTo(new CanParamDescriptor('W', CanParamType.UInt8, 0)), "M308V1Params[8]");
        Assert.That(table[9], Is.EqualTo(new CanParamDescriptor('K', CanParamType.Char, 0)), "M308V1Params[9]");
        Assert.That(table[10], Is.EqualTo(new CanParamDescriptor('Y', CanParamType.ReducedString, 0)), "M308V1Params[10]");
        Assert.That(table[11], Is.EqualTo(new CanParamDescriptor('P', CanParamType.ReducedString, 0)), "M308V1Params[11]");
        Assert.That(table[12], Is.EqualTo(new CanParamDescriptor('U', CanParamType.Float16, 0)), "M308V1Params[12]");
        Assert.That(table[13], Is.EqualTo(new CanParamDescriptor('V', CanParamType.Float16, 0)), "M308V1Params[13]");
    }

    [Test]
    public void M569Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M569Params;
        Assert.That(table.Length, Is.EqualTo(11), "number of entries in M569Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.LocalDriver, 0)), "M569Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt8, 0)), "M569Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('R', CanParamType.Int8, 0)), "M569Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('D', CanParamType.UInt8, 0)), "M569Params[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('F', CanParamType.UInt8, 0)), "M569Params[4]");
        Assert.That(table[5], Is.EqualTo(new CanParamDescriptor('B', CanParamType.UInt8, 0)), "M569Params[5]");
        Assert.That(table[6], Is.EqualTo(new CanParamDescriptor('H', CanParamType.UInt16, 0)), "M569Params[6]");
        Assert.That(table[7], Is.EqualTo(new CanParamDescriptor('V', CanParamType.UInt16, 0)), "M569Params[7]");
        Assert.That(table[8], Is.EqualTo(new CanParamDescriptor('Y', CanParamType.UInt8Array, 3)), "M569Params[8]");
        Assert.That(table[9], Is.EqualTo(new CanParamDescriptor('T', CanParamType.FloatArray, 4)), "M569Params[9]");
        Assert.That(table[10], Is.EqualTo(new CanParamDescriptor('U', CanParamType.Int8, 0)), "M569Params[10]");
    }

    [Test]
    public void M569Point1Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M569Point1Params;
        Assert.That(table.Length, Is.EqualTo(13), "number of entries in M569Point1Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.LocalDriver, 0)), "M569Point1Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('T', CanParamType.UInt8, 0)), "M569Point1Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('E', CanParamType.FloatArray, 2)), "M569Point1Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('C', CanParamType.Float, 0)), "M569Point1Params[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('R', CanParamType.Float, 0)), "M569Point1Params[4]");
        Assert.That(table[5], Is.EqualTo(new CanParamDescriptor('I', CanParamType.Float, 0)), "M569Point1Params[5]");
        Assert.That(table[6], Is.EqualTo(new CanParamDescriptor('D', CanParamType.Float, 0)), "M569Point1Params[6]");
        Assert.That(table[7], Is.EqualTo(new CanParamDescriptor('h', CanParamType.Float, 0)), "M569Point1Params[7]");
        Assert.That(table[8], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt16, 0)), "M569Point1Params[8]");
        Assert.That(table[9], Is.EqualTo(new CanParamDescriptor('V', CanParamType.Float, 0)), "M569Point1Params[9]");
        Assert.That(table[10], Is.EqualTo(new CanParamDescriptor('A', CanParamType.Float, 0)), "M569Point1Params[10]");
        Assert.That(table[11], Is.EqualTo(new CanParamDescriptor('Q', CanParamType.Float, 0)), "M569Point1Params[11]");
        Assert.That(table[12], Is.EqualTo(new CanParamDescriptor('Y', CanParamType.ReducedString, 0)), "M569Point1Params[12]");
    }

    [Test]
    public void M569Point2Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M569Point2Params;
        Assert.That(table.Length, Is.EqualTo(3), "number of entries in M569Point2Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.LocalDriver, 0)), "M569Point2Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('R', CanParamType.UInt8, 0)), "M569Point2Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('V', CanParamType.UInt32, 0)), "M569Point2Params[2]");
    }

    [Test]
    public void M569Point4Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M569Point4Params;
        Assert.That(table.Length, Is.EqualTo(3), "number of entries in M569Point4Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.LocalDriver, 0)), "M569Point4Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('T', CanParamType.Float, 0)), "M569Point4Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('V', CanParamType.Float, 0)), "M569Point4Params[2]");
    }

    [Test]
    public void M569Point6Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M569Point6Params;
        Assert.That(table.Length, Is.EqualTo(4), "number of entries in M569Point6Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.LocalDriver, 0)), "M569Point6Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('V', CanParamType.UInt8, 0)), "M569Point6Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('S', CanParamType.Float, 0)), "M569Point6Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('A', CanParamType.Float, 0)), "M569Point6Params[3]");
    }

    [Test]
    public void M569Point6Params_StatusOnly_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M569Point6Params_StatusOnly;
        Assert.That(table.Length, Is.EqualTo(2), "number of entries in M569Point6Params_StatusOnly");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.LocalDriver, 0)), "M569Point6Params_StatusOnly[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('v', CanParamType.UInt8, 0)), "M569Point6Params_StatusOnly[1]");
    }

    [Test]
    public void M569Point7Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M569Point7Params;
        Assert.That(table.Length, Is.EqualTo(4), "number of entries in M569Point7Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.LocalDriver, 0)), "M569Point7Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('C', CanParamType.ReducedString, 0)), "M569Point7Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('V', CanParamType.Float, 0)), "M569Point7Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt16, 0)), "M569Point7Params[3]");
    }

    [Test]
    public void M915Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M915Params;
        Assert.That(table.Length, Is.EqualTo(6), "number of entries in M915Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('d', CanParamType.UInt16, 0)), "M915Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('S', CanParamType.Int8, 0)), "M915Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('F', CanParamType.UInt8, 0)), "M915Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('H', CanParamType.UInt16, 0)), "M915Params[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('T', CanParamType.UInt16, 0)), "M915Params[4]");
        Assert.That(table[5], Is.EqualTo(new CanParamDescriptor('R', CanParamType.UInt8, 0)), "M915Params[5]");
    }

    [Test]
    public void M950HeaterParams_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M950HeaterParams;
        Assert.That(table.Length, Is.EqualTo(5), "number of entries in M950HeaterParams");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('H', CanParamType.UInt16, 0)), "M950HeaterParams[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('Q', CanParamType.PwmFreq, 0)), "M950HeaterParams[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('T', CanParamType.UInt16, 0)), "M950HeaterParams[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('C', CanParamType.ReducedString, 0)), "M950HeaterParams[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('B', CanParamType.Int16, 0)), "M950HeaterParams[4]");
    }

    [Test]
    public void M950FanParams_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M950FanParams;
        Assert.That(table.Length, Is.EqualTo(4), "number of entries in M950FanParams");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('F', CanParamType.UInt16, 0)), "M950FanParams[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('Q', CanParamType.PwmFreq, 0)), "M950FanParams[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('C', CanParamType.ReducedString, 0)), "M950FanParams[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('K', CanParamType.Float, 0)), "M950FanParams[3]");
    }

    [Test]
    public void M950GpioParams_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M950GpioParams;
        Assert.That(table.Length, Is.EqualTo(4), "number of entries in M950GpioParams");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.UInt16, 0)), "M950GpioParams[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('Q', CanParamType.PwmFreq, 0)), "M950GpioParams[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt8, 0)), "M950GpioParams[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('C', CanParamType.ReducedString, 0)), "M950GpioParams[3]");
    }

    [Test]
    public void M950LedParams_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M950LedParams;
        Assert.That(table.Length, Is.EqualTo(7), "number of entries in M950LedParams");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('E', CanParamType.UInt16, 0)), "M950LedParams[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('U', CanParamType.UInt16, 0)), "M950LedParams[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('Q', CanParamType.UInt32, 0)), "M950LedParams[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('T', CanParamType.UInt8, 0)), "M950LedParams[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('C', CanParamType.ReducedString, 0)), "M950LedParams[4]");
        Assert.That(table[5], Is.EqualTo(new CanParamDescriptor('L', CanParamType.UInt16Array, 4)), "M950LedParams[5]");
        Assert.That(table[6], Is.EqualTo(new CanParamDescriptor('K', CanParamType.UInt8, 0)), "M950LedParams[6]");
    }

    [Test]
    public void ConfigureFilamentMonitorParams_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.ConfigureFilamentMonitorParams;
        Assert.That(table.Length, Is.EqualTo(7), "number of entries in ConfigureFilamentMonitorParams");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('d', CanParamType.UInt8, 0)), "ConfigureFilamentMonitorParams[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt8, 0)), "ConfigureFilamentMonitorParams[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('A', CanParamType.UInt8, 0)), "ConfigureFilamentMonitorParams[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('L', CanParamType.Float, 0)), "ConfigureFilamentMonitorParams[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('E', CanParamType.Float, 0)), "ConfigureFilamentMonitorParams[4]");
        Assert.That(table[5], Is.EqualTo(new CanParamDescriptor('R', CanParamType.UInt16Array, 2)), "ConfigureFilamentMonitorParams[5]");
        Assert.That(table[6], Is.EqualTo(new CanParamDescriptor('C', CanParamType.ReducedString, 0)), "ConfigureFilamentMonitorParams[6]");
    }

    [Test]
    public void M955Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M955Params;
        Assert.That(table.Length, Is.EqualTo(4), "number of entries in M955Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('P', CanParamType.LocalDriver, 0)), "M955Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('I', CanParamType.UInt8, 0)), "M955Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('R', CanParamType.UInt8, 0)), "M955Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt16, 0)), "M955Params[3]");
    }

    [Test]
    public void M122P1Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M122P1Params;
        Assert.That(table.Length, Is.EqualTo(5), "number of entries in M122P1Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('T', CanParamType.FloatArray, 2)), "M122P1Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('V', CanParamType.FloatArray, 2)), "M122P1Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('W', CanParamType.FloatArray, 2)), "M122P1Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('U', CanParamType.FloatArray, 2)), "M122P1Params[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('F', CanParamType.FloatArray, 2)), "M122P1Params[4]");
    }

    [Test]
    public void M655Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M655Params;
        Assert.That(table.Length, Is.EqualTo(7), "number of entries in M655Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('E', CanParamType.Float, 0)), "M655Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('F', CanParamType.Float, 0)), "M655Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('R', CanParamType.Int32, 0)), "M655Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('S', CanParamType.Int32, 0)), "M655Params[3]");
        Assert.That(table[4], Is.EqualTo(new CanParamDescriptor('P', CanParamType.UInt16, 0)), "M655Params[4]");
        Assert.That(table[5], Is.EqualTo(new CanParamDescriptor('C', CanParamType.ReducedString, 0)), "M655Params[5]");
        Assert.That(table[6], Is.EqualTo(new CanParamDescriptor('A', CanParamType.String, 0)), "M655Params[6]");
    }

    [Test]
    public void M111Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M111Params;
        Assert.That(table.Length, Is.EqualTo(4), "number of entries in M111Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('D', CanParamType.UInt32, 0)), "M111Params[0]");
        Assert.That(table[1], Is.EqualTo(new CanParamDescriptor('F', CanParamType.UInt16, 0)), "M111Params[1]");
        Assert.That(table[2], Is.EqualTo(new CanParamDescriptor('P', CanParamType.UInt8, 0)), "M111Params[2]");
        Assert.That(table[3], Is.EqualTo(new CanParamDescriptor('S', CanParamType.UInt8, 0)), "M111Params[3]");
    }

    [Test]
    public void M959Params_Entries()
    {
        ImmutableArray<CanParamDescriptor> table = CanGenericTables.M959Params;
        Assert.That(table.Length, Is.EqualTo(1), "number of entries in M959Params");
        Assert.That(table[0], Is.EqualTo(new CanParamDescriptor('T', CanParamType.UInt16, 0)), "M959Params[0]");
    }

}
