using System.Collections.Immutable;
using System.Runtime.CompilerServices;
using DuetAPI.Commands;
using DuetControlServer.Link.Protocol.Shared;

namespace DuetControlServer.Link.Protocol.CanMessages;

/// <summary>
/// Common interface implemented by all CAN message body structs that mirror the
/// definitions in CANlib's <c>CanMessageFormats.h</c>.
/// </summary>
/// <remarks>
/// These structs are generated by <c>src/DuetCanMessage.SourceGenerators</c> from the neutral schema in
/// <c>src/DuetCanMessage.SourceGenerators/Schema/can-messages.json</c>, which generates the C++ side from the
/// same description. The layout conventions are:
/// <c>[StructLayout(LayoutKind.Explicit, Pack = 1)]</c> with generator-computed field offsets to match
/// <c>__attribute__((packed))</c>, bitfields emulated via properties over a private backing integer
/// (the lowest declared C++ field occupies the least-significant bits, matching little-endian targets),
/// and fixed C arrays represented as blittable
/// <see cref="System.Runtime.CompilerServices.InlineArrayAttribute"/> buffers so they can be
/// (de)serialized with <c>MemoryMarshal</c>.
/// <para>
/// Almost every message names the type it is sent under and so implements <see cref="ICanMessage{TSelf}"/>.
/// This interface is for the two bodies that are never sent under a name of their own:
/// <c>CanMessageGeneric</c>, whose type belongs to the parameter table of whichever generic message wraps
/// it, and <c>CanMessageMultipleDrivesRequestUint16</c>, a retired form that survives only as an arm of
/// CANlib's message union. Both are marked <c>bodyOnly</c> in the schema, which is what lets the generator
/// tell them apart from a message whose type was simply forgotten.
/// </para>
/// </remarks>
public interface ICanMessageBody<TSelf> where TSelf : struct, ICanMessageBody<TSelf>
{
    /// <summary>
    /// Number of payload bytes this message actually occupies. Variable-length messages override this.
    /// </summary>
    virtual uint GetActualDataLength() => (uint)Unsafe.SizeOf<TSelf>();
}

/// <summary>
/// A CAN message body that identifies itself, i.e. one that CANlib declares a <c>messageType</c> for.
/// </summary>
/// <remarks>
/// The message type is <c>static abstract</c> on purpose. Supplying a default here would let a body whose
/// schema entry is missing its <c>messageType</c> compile and then go out on the bus under
/// <see cref="CanMessageType.UnusedMessageType"/>, which is indistinguishable from
/// <see cref="CanMessageType.NoReply"/> — a silently malformed CAN id rather than a build error.
/// </remarks>
public interface ICanMessage<TSelf> : ICanMessageBody<TSelf> where TSelf : struct, ICanMessage<TSelf>
{
    /// <summary>
    /// CAN message type identifying this message (placed in the CAN id)
    /// </summary>
    static abstract CanMessageType MessageType { get; }
}

/// <summary>
/// A message whose payload is a <see cref="CanMessageGeneric"/>: the parameters of its table that are being
/// sent, packed in table order, plus a bitmap saying which those are.
/// </summary>
/// <remarks>
/// These are the messages CANlib defines by a parameter table rather than by a struct, and the generator
/// gives each one a type of its own so that it is used like any other message: a value with a property per
/// parameter, which the ordinary typed send path takes because it is still an <see cref="ICanMessage{TSelf}"/>
/// over the same 64 bytes the expansion board reads.
/// <para>
/// Every parameter is optional, so each property is nullable: reading one gives null when the message is not
/// carrying that parameter, and assigning null takes it back out. The table and the packing rules are the
/// implementation's business — <see cref="CanGenericWriter"/> and <see cref="CanGenericParser"/> are the
/// letter-keyed path underneath, for the caller that only knows the table at run time.
/// </para>
/// </remarks>
public interface ICanGenericMessage<TSelf> : ICanMessage<TSelf> where TSelf : struct, ICanGenericMessage<TSelf>
{
    /// <summary>
    /// The parameter table this message is built against, which is the contract between the two ends of the
    /// link: the sender packs the present parameters in table order and sets the matching bit of the
    /// message's paramMap, and the receiver walks the same table to find them again.
    /// </summary>
    static abstract ImmutableArray<CanParamDescriptor> ParamTable { get; }

    /// <summary>
    /// Take the parameters of this message from a G-code command, converted to the types the table declares.
    /// </summary>
    /// <remarks>
    /// Parameters the command does not mention are left as they are, so a value set explicitly before the
    /// call survives one the command does not carry. Use <see cref="Clear"/> to start from an empty message.
    /// </remarks>
    /// <param name="code">Command to take the parameter values from.</param>
    /// <exception cref="CanGenericParamException">
    /// A value does not fit the parameter it was given for, or the message would overflow.
    /// </exception>
    void FromCode(Code code);

    /// <summary>Take every parameter back out of the message, leaving it as newly constructed.</summary>
    void Clear();
}
