using System.Runtime.CompilerServices;
using DuetControlServer.Link.Protocol.Shared;

namespace DuetControlServer.Link.Protocol.CanMessages;

/// <summary>
/// Common interface implemented by all CAN message body structs that mirror the
/// definitions in CANlib's <c>CanMessageFormats.h</c>.
/// </summary>
/// <remarks>
/// These structs are generated by <c>tools/CanMessageGenerator</c> from the neutral schema in
/// <c>tools/CanMessageGenerator/Schema/can-messages.json</c>, which generates the C++ side from the
/// same description. The layout conventions are:
/// <c>[StructLayout(LayoutKind.Explicit, Pack = 1)]</c> with generator-computed field offsets to match
/// <c>__attribute__((packed))</c>, bitfields emulated via properties over a private backing integer
/// (the lowest declared C++ field occupies the least-significant bits, matching little-endian targets),
/// and fixed C arrays represented as blittable
/// <see cref="System.Runtime.CompilerServices.InlineArrayAttribute"/> buffers so they can be
/// (de)serialized with <c>MemoryMarshal</c>.
/// <para>
/// A few message bodies carry no message type of their own because they are sent under several different
/// types: the <c>CanMessageMultipleDrivesRequest</c> family, <c>CanMessageGeneric</c> and
/// <c>CanMessageM303</c>. CANlib gives those no <c>messageType</c> member either, so they implement this
/// interface rather than <see cref="ICanMessage{TSelf}"/> and the caller supplies the type.
/// </para>
/// </remarks>
public interface ICanMessageBody<TSelf> where TSelf : struct, ICanMessageBody<TSelf>
{
    /// <summary>
    /// Number of payload bytes this message actually occupies. Variable-length messages override this.
    /// </summary>
    virtual uint GetActualDataLength() => (uint)Unsafe.SizeOf<TSelf>();
}

/// <summary>
/// A CAN message body that identifies itself, i.e. one that CANlib declares a <c>messageType</c> for.
/// </summary>
/// <remarks>
/// The message type is <c>static abstract</c> on purpose. Supplying a default here would let a body whose
/// schema entry is missing its <c>messageType</c> compile and then go out on the bus under
/// <see cref="CanMessageType.UnusedMessageType"/>, which is indistinguishable from
/// <see cref="CanMessageType.NoReply"/> — a silently malformed CAN id rather than a build error.
/// </remarks>
public interface ICanMessage<TSelf> : ICanMessageBody<TSelf> where TSelf : struct, ICanMessage<TSelf>
{
    /// <summary>
    /// CAN message type identifying this message (placed in the CAN id)
    /// </summary>
    static abstract CanMessageType MessageType { get; }
}
