using System.Runtime.CompilerServices;
using DuetControlServer.Link.Protocol.Shared;

namespace DuetControlServer.Link.Protocol.CanMessages;

/// <summary>
/// Common interface implemented by all CAN message body structs that mirror the
/// definitions in CANlib's <c>CanMessageFormats.h</c>.
/// </summary>
/// <remarks>
/// These structs are generated by <c>tools/CanMessageGenerator</c> from the neutral schema in
/// <c>tools/CanMessageGenerator/Schema/can-messages.json</c>, which generates the C++ side from the
/// same description. The layout conventions are:
/// <c>[StructLayout(LayoutKind.Explicit, Pack = 1)]</c> with generator-computed field offsets to match
/// <c>__attribute__((packed))</c>, bitfields emulated via properties over a private backing integer
/// (the lowest declared C++ field occupies the least-significant bits, matching little-endian targets),
/// and fixed C arrays represented as blittable
/// <see cref="System.Runtime.CompilerServices.InlineArrayAttribute"/> buffers so they can be
/// (de)serialized with <c>MemoryMarshal</c>.
/// </remarks>
public interface ICanMessage<TSelf> where TSelf : struct, ICanMessage<TSelf>
{
    /// <summary>
    /// CAN message type identifying this message (placed in the CAN id)
    /// </summary>
    /// <remarks>
    /// A few message bodies carry no message type of their own because they are sent under several
    /// different types: the <c>CanMessageMultipleDrivesRequest</c> family, <c>CanMessageGeneric</c> and
    /// <c>CanMessageM303</c>. CANlib gives those no <c>messageType</c> member either, so they inherit
    /// this default and the caller supplies the type instead.
    /// </remarks>
    static virtual CanMessageType MessageType => CanMessageType.UnusedMessageType;

    /// <summary>
    /// Number of payload bytes this message actually occupies. Variable-length messages override this.
    /// </summary>
    virtual uint GetActualDataLength() => (uint)Unsafe.SizeOf<TSelf>();
}
