using System;
using System.Globalization;
using System.IO;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using DuetAPI;
using DuetAPI.ObjectModel;
using NUnit.Framework;
using SystemTests.Host;

namespace SystemTests.Scenarios.Codes;

/// <summary>
/// <para>
/// The job, file and SD card codes, asserted against the object model state RepRapFirmware gives
/// each of them rather than against the lifecycle they drive: the parsed file information
/// <c>job.file</c> carries after a selection (M23, M32, M36, M37), the file position M26 sets and
/// M27 reports, the job counters (<c>job.duration</c>, <c>job.timesLeft</c>, <c>job.lastFileName</c>,
/// <c>job.lastFileSimulated</c>), the volume information M21 and M39 report, the macro state M98
/// exposes through <c>inputs[]</c>, and the file system changes M28/M29, M30 and M470/M471/M472
/// make. The sequencing of pauses, resumes and cancellations is covered by JobLifecycleTests,
/// SyncPauseTests and CancelRestartTests and is not repeated here.
/// </para>
/// <para>
/// M606 is exercised only through the refusal it gives outside a job file: forking the reader
/// duplicates the whole job onto the File2 channel, which is a lifecycle behaviour rather than an
/// object model one, and there is no field that describes the fork other than the second channel's
/// own <c>inputs[]</c> entry appearing.
/// </para>
/// </summary>
[TestFixture]
public class JobFileCodeTests : SystemTests.Host.BenchFixture
{
    /// <summary>
    /// A job file whose header carries the slicer comments both file info parsers understand, so
    /// every parsed field has a known value. The Z move gives the object height: RepRapFirmware
    /// takes it from the highest Z of a G0/G1 in the tail of the file
    /// (FileInfoParser.cpp, the 'G' case of <c>ParseGCodeFile</c>), and it agrees with
    /// layerHeight * numLayers, which is what RepRapFirmware falls back to
    /// (FileInfoParser.cpp <c>ParseFileHeader</c>)
    /// </summary>
    private const string InfoFile = """
        ; generated by TestSlicer 1.2
        ; layer_height = 0.25
        ;NUM_LAYERS:8
        ; filament used [mm] = 123.4
        ;TIME:3600
        G1 Z2 F300
        G4 P1
        """;

    /// <summary>A file carrying one PNG thumbnail of known dimensions and data</summary>
    private const string ThumbnailFile = """
        ; thumbnail begin 32x32 16
        ; QUJDREVGR0hJSktM
        ; thumbnail end
        G1 Z1 F300
        """;

    /// <summary>The base64 payload of <see cref="ThumbnailFile"/>'s thumbnail</summary>
    private const string ThumbnailData = "QUJDREVGR0hJSktM";

    /// <summary>The physical path of a file on the bench's virtual SD card</summary>
    private static string Physical(JobBench bench, string directory, string name)
        => Path.Combine(bench.Host.Sd.Root, directory, name);

    /// <summary>
    /// The index of the HTTP channel in inputs[], found by name because the channel order is not
    /// part of the contract under test
    /// </summary>
    private static async Task<int> HttpInputIndexAsync(DcsTestHost host)
    {
        using (await host.Model.AccessReadOnlyAsync(CancellationToken.None))
        {
            for (int i = 0; i < host.Model.Inputs.Count; i++)
            {
                if (host.Model.Inputs[i]?.Name == CodeChannel.HTTP)
                {
                    return i;
                }
            }
        }
        throw new AssertionException("inputs[] does not contain the HTTP channel");
    }

    /// <summary>
    /// How long a code that reports on the job is given. These codes read the file position through
    /// the job processor, so a bound shorter than the default fails the test that asked rather than
    /// holding the suite up for a minute
    /// </summary>
    private const int ReportTimeoutMs = 15_000;

    /// <summary>The file position and length M27 reports</summary>
    private static (long Position, long Length) ParsePrintStatus(string reply)
    {
        Match match = Regex.Match(reply, @"SD printing byte (\d+)/(\d+)");
        if (!match.Success)
        {
            throw new AssertionException($"M27 did not report a file position: \"{reply.Trim()}\"");
        }
        return (long.Parse(match.Groups[1].Value, CultureInfo.InvariantCulture),
                long.Parse(match.Groups[2].Value, CultureInfo.InvariantCulture));
    }

    /// <summary>
    /// An object model expression as a number, or NaN when it does not hold one. A field the model
    /// leaves null fails the assertion that reads it rather than the test that asked
    /// </summary>
    private static async Task<double> NumberAsync(DcsTestHost host, string expression)
    {
        string raw = await host.EvaluateRawAsync(expression);
        return double.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out double value) ? value : double.NaN;
    }

    /// <summary>
    /// The same reading, once the job monitor has published it. The job counters are recomputed on
    /// an interval rather than by the code that feeds them, so a reading taken in the same
    /// millisecond as the reply describes the moment before it
    /// </summary>
    private static async Task<double> SettledNumberAsync(DcsTestHost host, string expression, int timeoutMs = 5_000)
    {
        DateTime deadline = DateTime.UtcNow.AddMilliseconds(timeoutMs);
        double value;
        do
        {
            value = await NumberAsync(host, expression);
            if (!double.IsNaN(value))
            {
                return value;
            }
            await Task.Delay(50);
        }
        while (DateTime.UtcNow < deadline);
        return value;
    }

    /// <summary>
    /// An expression's text once it reads as expected, or its last reading when it never does. The
    /// fields a finished job leaves behind are written by the job monitor rather than by the code
    /// that stopped the job, so they settle shortly after the reply
    /// </summary>
    private static async Task<string> SettledRawAsync(DcsTestHost host, string expression, string expected, int timeoutMs = 5_000)
    {
        DateTime deadline = DateTime.UtcNow.AddMilliseconds(timeoutMs);
        string value;
        do
        {
            value = await host.EvaluateRawAsync(expression);
            if (value == expected)
            {
                return value;
            }
            await Task.Delay(50);
        }
        while (DateTime.UtcNow < deadline);
        return value;
    }

    /// <summary>The data a fragment or thumbnail answer carries, or null when it carries none</summary>
    private static string? FragmentData(JsonElement root, string key)
        => root.TryGetProperty(key, out JsonElement fragment) && fragment.TryGetProperty("data", out JsonElement data)
            ? data.GetString()
            : null;

    /// <summary>
    /// The JSON object a code answered with. A malformed answer fails as an assertion naming the
    /// code, because every one of these codes answers a machine-readable object
    /// </summary>
    private static JsonElement ParseJson(string code, string reply)
    {
        try
        {
            return JsonDocument.Parse(reply.Trim()).RootElement.Clone();
        }
        catch (JsonException e)
        {
            throw new AssertionException($"{code} did not answer with valid JSON: \"{reply.Trim()}\" ({e.Message})");
        }
    }

    /// <summary>
    /// M20 lists the names the SD card holds, from the G-code directory by default and from the
    /// directory P names otherwise
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp case 20: the directory defaults to <c>Platform::GetGCodeDir()</c>, and with no S
    /// parameter the names are listed after a "GCode files:" header, quoted and comma separated,
    /// for the RepRapFirmware compatibility the bench runs in
    /// </remarks>
    [Test]
    public async Task M20ListsTheFilesOnTheSdCard()
    {
        await using JobBench bench = await JobControlBench.StartAsync(prepareSd: sd =>
        {
            sd.WriteGCode("first.gcode", "G4 P1\n");
            sd.WriteGCode("second.gcode", "G4 P1\n");
        });

        string gcodes = await bench.Host.ExecuteCodeAsync("M20");
        string sys = await bench.Host.ExecuteCodeAsync("M20 P\"0:/sys\"");

        Assert.Multiple(() =>
        {
            Assert.That(gcodes, Does.Contain("GCode files:"),
                        "M20 heads the list with GCode files: (GCodes2.cpp case 20)");
            Assert.That(gcodes, Does.Contain("\"first.gcode\""),
                        "M20 lists first.gcode, which the virtual SD card holds");
            Assert.That(gcodes, Does.Contain("\"second.gcode\""),
                        "M20 lists second.gcode, which the virtual SD card holds");
            Assert.That(gcodes, Does.Not.Contain("config.g"),
                        "M20 lists the G-code directory, not the system directory");
            Assert.That(sys, Does.Contain("\"config.g\""),
                        "M20 P lists the named directory (GCodes2.cpp case 20, the P parameter)");
            Assert.That(sys, Does.Contain("\"pause.g\""),
                        "M20 P\"0:/sys\" lists every file the system directory holds");
        });
    }

    /// <summary>
    /// M21 mounts the SD card, which is what <c>volumes[0]</c> describes, and M39 reports the same
    /// numbers the object model holds
    /// </summary>
    /// <remarks>
    /// MassStorage.cpp OBJECT_MODEL table: <c>mounted</c> is unconditional, while <c>capacity</c>,
    /// <c>freeSpace</c> and <c>partitionSize</c> are reported only while the volume is mounted.
    /// GCodes2.cpp case 21 mounts the card and case 39 reports the same values, with S2 giving them
    /// as the SDinfo JSON object
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M21MountsTheCardAndM39ReportsIt()
    {
        await using JobBench bench = await JobControlBench.StartAsync();

        await bench.Host.ExecuteCodeAsync("M21");
        string report = await bench.Host.ExecuteCodeAsync("M39");
        JsonElement info = ParseJson("M39 S2", await bench.Host.ExecuteCodeAsync("M39 S2")).GetProperty("SDinfo");

        await Assert.MultipleAsync(async () =>
        {
            Assert.That(await bench.Host.EvaluateRawAsync("volumes[0].mounted"), Is.EqualTo("true"),
                        "M21 leaves volumes[0].mounted true (MassStorage.cpp OBJECT_MODEL mounted)");
            Assert.That(await NumberAsync(bench.Host, "volumes[0].capacity"), Is.GreaterThan(0.0),
                        "a mounted volume reports volumes[0].capacity in bytes (MassStorage.cpp OBJECT_MODEL capacity)");
            Assert.That(await NumberAsync(bench.Host, "volumes[0].freeSpace"), Is.GreaterThan(0.0),
                        "a mounted volume reports volumes[0].freeSpace in bytes (MassStorage.cpp OBJECT_MODEL freeSpace)");
            Assert.That(report, Does.Contain("SD card in slot 0: capacity"),
                        "M39 reports the slot and its capacity (GCodes2.cpp case 39)");
            Assert.That(info.TryGetProperty("present", out JsonElement present) ? present.GetInt32() : 0, Is.EqualTo(1),
                        "M39 S2 reports the mounted card as present (GCodes2.cpp case 39, format 2)");
            Assert.That(info.TryGetProperty("capacity", out JsonElement jsonCapacity) ? jsonCapacity.GetInt64() : 0L,
                        Is.EqualTo((long)await NumberAsync(bench.Host, "volumes[0].capacity")),
                        "M39 S2 reports the same capacity as volumes[0].capacity");
        });
    }

    /// <summary>
    /// M23 selects a file and publishes what the file info parser found in it, without starting it
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp case 23 calls <c>PrintMonitor::StartingPrint</c>, which parses the file and
    /// publishes it through <c>PrintingFileInfoUpdated</c>. The fields are the PrintMonitor.cpp
    /// OBJECT_MODEL table of <c>job.file</c>: size, height and layerHeight to two decimals,
    /// numLayers, generatedBy, printTime, and the filament array. Only M24 starts the job
    /// (<c>StartedPrint</c>), so the machine is still idle afterwards
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M23SelectsTheFileAndPublishesItsInfo()
    {
        await using JobBench bench = await JobControlBench.StartAsync(prepareSd: sd => sd.WriteGCode("info.gcode", InfoFile));
        long size = new FileInfo(Physical(bench, "gcodes", "info.gcode")).Length;

        // The startup files have to be done with before "still idle" says anything about M23
        await bench.Host.WaitForStatusAsync(MachineStatus.Idle);
        string reply = await bench.Host.ExecuteCodeAsync("M23 \"0:/gcodes/info.gcode\"");

        await Assert.MultipleAsync(async () =>
        {
            Assert.That(reply, Does.Contain("info.gcode"),
                        "M23 names the file it selected (GCodes2.cpp case 23)");
            Assert.That(await bench.Host.EvaluateRawAsync("job.file.fileName"), Is.EqualTo("0:/gcodes/info.gcode"),
                        "M23 sets job.file.fileName (PrintMonitor.cpp filenameBeingPrinted)");
            Assert.That(await bench.Host.EvaluateAsync("job.file.size"), Is.EqualTo(size),
                        "M23 sets job.file.size to the file length in bytes (PrintMonitor.cpp fileSize)");
            Assert.That(await bench.Host.EvaluateAsync("job.file.height"), Is.EqualTo(2.0).Within(0.005),
                        "M23 sets job.file.height in mm (PrintMonitor.cpp objectHeight)");
            Assert.That(await bench.Host.EvaluateAsync("job.file.layerHeight"), Is.EqualTo(0.25).Within(0.005),
                        "M23 sets job.file.layerHeight in mm (PrintMonitor.cpp layerHeight)");
            Assert.That(await bench.Host.EvaluateAsync("job.file.numLayers"), Is.EqualTo(8),
                        "M23 sets job.file.numLayers (PrintMonitor.cpp numLayers)");
            Assert.That(await bench.Host.EvaluateRawAsync("job.file.generatedBy"), Is.EqualTo("TestSlicer 1.2"),
                        "M23 sets job.file.generatedBy (PrintMonitor.cpp generatedBy)");
            Assert.That(await NumberAsync(bench.Host, "job.file.printTime"), Is.EqualTo(3600),
                        "M23 sets job.file.printTime in seconds (PrintMonitor.cpp printTime)");
            Assert.That(await bench.Host.EvaluateAsync("job.file.filament[0]"), Is.EqualTo(123.4).Within(0.05),
                        "M23 sets job.file.filament[0] in mm (PrintMonitor.cpp filamentNeeded)");
            Assert.That(await bench.Host.EvaluateRawAsync("state.status"), Is.EqualTo("idle"),
                        "M23 selects without starting, so the machine stays idle (RepRap.cpp GetStatusIndex)");
        });
    }

    /// <summary>
    /// M36 answers with the same information for a named file and for the selected one
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp case 36 with fraction 0 calls <c>RepRap::GetFileInfoResponse</c> (RepRap.cpp),
    /// which answers <c>err</c> 0 with fileName, size, height, layerHeight, numLayers, printTime,
    /// filament and generatedBy for a valid file, and <c>err</c> 1 for one it cannot read. Without a
    /// filename it answers for the file being printed
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M36ReportsFileInformation()
    {
        await using JobBench bench = await JobControlBench.StartAsync(prepareSd: sd => sd.WriteGCode("info.gcode", InfoFile));
        long size = new FileInfo(Physical(bench, "gcodes", "info.gcode")).Length;

        JsonElement root = ParseJson("M36", await bench.Host.ExecuteCodeAsync("M36 \"0:/gcodes/info.gcode\""));
        string missing = await bench.Host.ExecuteCodeAsync("M36 \"0:/gcodes/nothing.gcode\"");
        await bench.Host.ExecuteCodeAsync("M23 \"0:/gcodes/info.gcode\"");
        string selected = await bench.Host.ExecuteCodeAsync("M36");

        Assert.Multiple(() =>
        {
            Assert.That(root.GetProperty("err").GetInt32(), Is.Zero,
                        "M36 answers err 0 for a file it could read (RepRap.cpp GetFileInfoResponse)");
            Assert.That(root.GetProperty("size").GetInt64(), Is.EqualTo(size),
                        "M36 reports the file size in bytes (RepRap.cpp GetFileInfoResponse)");
            Assert.That(root.GetProperty("height").GetDouble(), Is.EqualTo(2.0).Within(0.005),
                        "M36 reports the object height in mm (RepRap.cpp GetFileInfoResponse)");
            Assert.That(root.GetProperty("layerHeight").GetDouble(), Is.EqualTo(0.25).Within(0.005),
                        "M36 reports the layer height in mm (RepRap.cpp GetFileInfoResponse)");
            Assert.That(root.GetProperty("numLayers").GetInt32(), Is.EqualTo(8),
                        "M36 reports the number of layers (RepRap.cpp GetFileInfoResponse)");
            Assert.That(root.GetProperty("printTime").GetInt32(), Is.EqualTo(3600),
                        "M36 reports the slicer print time in seconds (RepRap.cpp GetFileInfoResponse)");
            Assert.That(root.GetProperty("generatedBy").GetString(), Is.EqualTo("TestSlicer 1.2"),
                        "M36 reports the slicer that generated the file (RepRap.cpp GetFileInfoResponse)");
            Assert.That(root.GetProperty("filament")[0].GetDouble(), Is.EqualTo(123.4).Within(0.05),
                        "M36 reports the filament needed per extruder in mm (RepRap.cpp GetFileInfoResponse)");
            Assert.That(ParseJson("M36 with no filename", selected).GetProperty("err").GetInt32(), Is.Zero,
                        "M36 with no filename answers for the selected file (GCodes2.cpp case 36)");
            Assert.That(ParseJson("M36 with no filename", selected).GetProperty("size").GetInt64(), Is.EqualTo(size),
                        "M36 with no filename reports the selected file's size");
            Assert.That(ParseJson("M36 of a missing file", missing).GetProperty("err").GetInt32(), Is.EqualTo(1),
                        "M36 answers err 1 for a file it cannot read (RepRap.cpp GetFileInfoResponse)");
        });
    }

    /// <summary>
    /// M36.1 returns the base64 data of an embedded thumbnail at the offset the object model gives
    /// for it
    /// </summary>
    /// <remarks>
    /// FileInfoParser.cpp <c>ProcessThumbnail</c> stores width, height, encoded size, format and the
    /// file offset of each thumbnail, reported through the PrintMonitor.cpp thumbnails table.
    /// GCodes2.cpp case 36 fraction 1 reads the file from that offset through
    /// <c>RepRap::GetFileFragment</c> (RepRap.cpp), which strips the comment markers and answers
    /// with the data and the next offset
    /// </remarks>
    [Test]
    public async Task M361ReturnsTheEmbeddedThumbnail()
    {
        await using JobBench bench = await JobControlBench.StartAsync(prepareSd: sd => sd.WriteGCode("thumb.gcode", ThumbnailFile));
        await bench.Host.ExecuteCodeAsync("M23 \"0:/gcodes/thumb.gcode\"");

        await Assert.MultipleAsync(async () =>
        {
            Assert.That(await bench.Host.EvaluateAsync("job.file.thumbnails[0].width"), Is.EqualTo(32),
                        "job.file.thumbnails[0].width comes from the thumbnail header (FileInfoParser.cpp ProcessThumbnail)");
            Assert.That(await bench.Host.EvaluateAsync("job.file.thumbnails[0].height"), Is.EqualTo(32),
                        "job.file.thumbnails[0].height comes from the thumbnail header (FileInfoParser.cpp ProcessThumbnail)");
            Assert.That(await bench.Host.EvaluateAsync("job.file.thumbnails[0].size"), Is.EqualTo(ThumbnailData.Length),
                        "job.file.thumbnails[0].size is the encoded length the header declares (FileInfoParser.cpp ProcessThumbnail)");
            Assert.That(await bench.Host.EvaluateRawAsync("job.file.thumbnails[0].format"), Is.EqualTo("png"),
                        "a thumbnail begin block is PNG (FileInfoParser.cpp ProcessThumbnail, param 0)");
        });

        long offset = (long)await bench.Host.EvaluateAsync("job.file.thumbnails[0].offset");
        JsonElement thumbnail = ParseJson("M36.1", await bench.Host.ExecuteCodeAsync($"M36.1 P\"0:/gcodes/thumb.gcode\" S{offset}"))
                                    .GetProperty("thumbnail");
        Assert.Multiple(() =>
        {
            Assert.That(thumbnail.TryGetProperty("data", out JsonElement data) ? data.GetString() ?? string.Empty : string.Empty,
                        Does.Contain(ThumbnailData),
                        "M36.1 returns the base64 data found at job.file.thumbnails[0].offset (RepRap.cpp GetFileFragment)");
            Assert.That(thumbnail.GetProperty("next").GetInt64(), Is.Zero,
                        "M36.1 answers next 0 once the thumbnail has ended (RepRap.cpp GetFileFragment)");
        });
    }

    /// <summary>
    /// M36.2 returns a fragment of a file as text
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp case 36 fraction 2 reads "the height map, or another file" through
    /// <c>RepRap::GetFileFragment</c> (RepRap.cpp), which for a fragment that is not a thumbnail
    /// opens the file with <c>OpenSysFile</c>: an unqualified name is therefore looked up in the
    /// system directory, which is where the height map files it is meant for live
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M362ReturnsAFileFragment()
    {
        await using JobBench bench = await JobControlBench.StartAsync(prepareSd: sd => sd.WriteGCode("info.gcode", InfoFile));

        string qualified = await bench.Host.ExecuteCodeAsync("M36.2 P\"0:/gcodes/info.gcode\" S0");
        string unqualified = await bench.Host.ExecuteCodeAsync("M36.2 P\"config.g\" S0");

        Assert.Multiple(() =>
        {
            Assert.That(FragmentData(ParseJson("M36.2", qualified), "fragment") ?? string.Empty,
                        Does.Contain("generated by TestSlicer 1.2"),
                        "M36.2 returns the text at the offset it was given (RepRap.cpp GetFileFragment)");
            Assert.That(FragmentData(ParseJson("M36.2 of an unqualified name", unqualified), "fragment") ?? string.Empty,
                        Does.Contain("M953"),
                        "M36.2 resolves an unqualified name in the system directory (RepRap.cpp GetFileFragment, OpenSysFile)");
        });
    }

    /// <summary>
    /// M24 starts the selected file and the job counters follow it: M27 reports the same file
    /// position the object model holds, against the same file length, and stopping the job moves the
    /// file name into job.lastFileName
    /// </summary>
    /// <remarks>
    /// PrintMonitor.cpp OBJECT_MODEL table: <c>filePosition</c> is
    /// <c>GCodes::GetPrintingFilePosition</c>, which is what GCodes2.cpp case 27 prints alongside
    /// the length of the file being printed; <c>duration</c> and <c>lastFileName</c> are reported
    /// while printing and once it has stopped respectively. Case 27 answers "Not SD printing." while
    /// no file is being printed, which a file that is only selected is not
    /// (PrintMonitor.cpp <c>StartedPrint</c> is what sets <c>isPrinting</c>)
    /// </remarks>
    [Test]
    public async Task M24AndM27TrackTheFilePosition()
    {
        await using JobBench bench = await JobControlBench.StartAsync(prepareSd: sd =>
            sd.WriteGCode("job.gcode", "G90\nG1 X50 Y50 F3000\n" + JobControlBench.FillerMoves(pairs: 60, feed: 600)));
        long size = new FileInfo(Physical(bench, "gcodes", "job.gcode")).Length;

        await bench.Host.ExecuteCodeAsync("M23 \"0:/gcodes/job.gcode\"");
        await bench.Host.ExecuteCodeAsync("M24");
        await bench.Host.WaitForStatusAsync(MachineStatus.Processing);
        Assert.That(await bench.Host.EvaluateRawAsync("state.status"), Is.EqualTo("processing"),
                    "M24 puts the machine into processing (RepRap.cpp GetStatusIndex)");

        // The pause holds the file position still, so the model describes one moment
        await bench.Host.ExecuteCodeAsync("M25");
        await bench.Host.WaitForStatusAsync(MachineStatus.Paused);

        long modelPosition = 0;
        await Assert.MultipleAsync(async () =>
        {
            modelPosition = (long)await NumberAsync(bench.Host, "job.filePosition");
            Assert.That(await bench.Host.EvaluateAsync("job.file.size"), Is.EqualTo(size),
                        "job.file.size is the length of the file being printed (PrintMonitor.cpp fileSize)");
            Assert.That(modelPosition, Is.GreaterThan(0).And.LessThanOrEqualTo(size),
                        "job.filePosition lies within the file being printed (PrintMonitor.cpp filePosition)");
            Assert.That(await NumberAsync(bench.Host, "job.duration"), Is.GreaterThanOrEqualTo(0),
                        "job.duration counts the job in seconds while it is printing (PrintMonitor.cpp duration)");
            Assert.That(await bench.Host.EvaluateRawAsync("job.lastFileName"), Is.EqualTo("null"),
                        "job.lastFileName stays null while the file is printing (PrintMonitor.cpp lastFileName)");
        });

        (long position, long length) = ParsePrintStatus(await bench.Host.ExecuteCodeAsync("M27", timeoutMs: ReportTimeoutMs));
        Assert.Multiple(() =>
        {
            Assert.That(length, Is.EqualTo(size),
                        "M27 reports the length of the file being printed (GCodes2.cpp case 27)");
            Assert.That(position, Is.EqualTo(modelPosition),
                        "M27 reports job.filePosition (GCodes2.cpp case 27, GCodes::GetPrintingFilePosition)");
        });

        await bench.Host.ExecuteCodeAsync("M0");
        await bench.Host.WaitForStatusAsync(MachineStatus.Idle);

        await Assert.MultipleAsync(async () =>
        {
            Assert.That(await SettledRawAsync(bench.Host, "job.lastFileName", "0:/gcodes/job.gcode"), Is.EqualTo("0:/gcodes/job.gcode"),
                        "the stopped job's file becomes job.lastFileName (PrintMonitor.cpp lastFileName)");
            Assert.That(await bench.Host.EvaluateRawAsync("job.lastFileSimulated"), Is.EqualTo("false"),
                        "a printed job is not a simulated one (job.lastFileSimulated)");
            Assert.That(await bench.Host.EvaluateRawAsync("job.duration"), Is.EqualTo("null"),
                        "job.duration is reported only while printing (PrintMonitor.cpp duration)");
            Assert.That(await SettledNumberAsync(bench.Host, "job.lastDuration"), Is.GreaterThanOrEqualTo(0),
                        "job.lastDuration holds what the finished job took, in seconds (PrintMonitor.cpp lastDuration)");
            Assert.That(await bench.Host.ExecuteCodeAsync("M27", timeoutMs: ReportTimeoutMs),
                        Does.Contain("Not SD printing."),
                        "M27 reports no print once the job has stopped (GCodes2.cpp case 27)");
        });
    }

    /// <summary>
    /// M26 says where in the selected file the job is to start, and the file position the job then
    /// reports never goes back before it
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp case 26 stores the offset in <c>ms.fileOffsetToPrint</c>, which case 24 uses when
    /// it starts the file (<c>StartPrinting(fromStart)</c>); the position the job reads from there on
    /// is what PrintMonitor.cpp reports as <c>filePosition</c>
    /// </remarks>
    [Test]
    public async Task M26SetsWhereTheJobStarts()
    {
        const string header = "G90\nG1 X20 Y20 F3000\n";
        await using JobBench bench = await JobControlBench.StartAsync(prepareSd: sd =>
            sd.WriteGCode("job.gcode", header + JobControlBench.FillerMoves(pairs: 60, feed: 600)));

        await bench.Host.ExecuteCodeAsync("M23 \"0:/gcodes/job.gcode\"");
        await bench.Host.ExecuteCodeAsync($"M26 S{header.Length}", timeoutMs: ReportTimeoutMs);
        await bench.Host.ExecuteCodeAsync("M24");
        await bench.Host.WaitForStatusAsync(MachineStatus.Processing);

        await bench.Host.ExecuteCodeAsync("M25");
        await bench.Host.WaitForStatusAsync(MachineStatus.Paused);

        Assert.That(await NumberAsync(bench.Host, "job.filePosition"), Is.GreaterThanOrEqualTo(header.Length),
                    "M26 S starts the job at that offset, so job.filePosition never precedes it (GCodes2.cpp case 26)");

        await bench.Host.ExecuteCodeAsync("M0");
        await bench.Host.WaitForStatusAsync(MachineStatus.Idle);
    }

    /// <summary>
    /// M28 captures the codes that follow it into a file instead of executing them, and M29 closes
    /// the capture without being captured itself
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp case 28 opens the file in the G-code directory and answers
    /// "Writing to file: &lt;name&gt;"; case 29 is intercepted before it reaches the handler, which
    /// is why the file holds every code between the two and not the M29
    /// </remarks>
    [Test]
    public async Task M28CapturesCodesUntilM29()
    {
        await using JobBench bench = await JobControlBench.StartAsync(configExtra: "global captured = 0\n");

        Assert.That(await bench.Host.ExecuteCodeAsync("M28 \"0:/gcodes/capture.gcode\""),
                    Does.Contain("Writing to file: 0:/gcodes/capture.gcode"),
                    "M28 names the file it is writing to (GCodes2.cpp case 28)");

        await bench.Host.ExecuteCodeAsync("G91");
        await bench.Host.ExecuteCodeAsync("G1 X5 F600");
        await bench.Host.ExecuteCodeAsync("set global.captured = 1");
        await bench.Host.ExecuteCodeAsync("M29");

        string captured = await File.ReadAllTextAsync(Physical(bench, "gcodes", "capture.gcode"));
        await Assert.MultipleAsync(async () =>
        {
            Assert.That(captured, Does.Contain("G1 X5"),
                        "the move between M28 and M29 was written to the file (GCodes2.cpp case 28)");
            Assert.That(captured, Does.Contain("global.captured"),
                        "every code between M28 and M29 is captured, meta commands included");
            Assert.That(captured, Does.Not.Contain("M29"),
                        "M29 ends the capture rather than being captured (GCodes2.cpp case 29)");
            Assert.That(await bench.Host.EvaluateAsync("global.captured"), Is.Zero,
                        "a captured code does not execute");
            Assert.That(await bench.Host.EvaluateAsync("move.axes[0].userPosition"), Is.Zero,
                        "the captured move did not move the machine (move.axes[0].userPosition)");
        });

        // The captured file is a job file like any other, so it can be selected and inspected
        await bench.Host.ExecuteCodeAsync("M23 \"0:/gcodes/capture.gcode\"");
        Assert.That(await bench.Host.EvaluateAsync("job.file.size"),
                    Is.EqualTo(new FileInfo(Physical(bench, "gcodes", "capture.gcode")).Length),
                    "job.file.size reports what M28 wrote (PrintMonitor.cpp fileSize)");
    }

    /// <summary>M30 deletes a file from the G-code directory</summary>
    /// <remarks>
    /// GCodes2.cpp case 30 deletes the named file relative to <c>Platform::GetGCodeDir()</c> and
    /// reports "delete failed" when it cannot. Deleting a file changes no object model field, so the
    /// file system and the M20 listing are what say it happened
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M30DeletesAFile()
    {
        await using JobBench bench = await JobControlBench.StartAsync(prepareSd: sd => sd.WriteGCode("doomed.gcode", "G4 P1\n"));
        string path = Physical(bench, "gcodes", "doomed.gcode");
        Assert.That(File.Exists(path), Is.True, "the file exists before M30 runs");

        await bench.Host.ExecuteCodeAsync("M30 \"0:/gcodes/doomed.gcode\"");

        Assert.Multiple(async () =>
        {
            Assert.That(File.Exists(path), Is.False, "M30 deleted the file (GCodes2.cpp case 30)");
            Assert.That(await bench.Host.ExecuteCodeAsync("M20"), Does.Not.Contain("doomed.gcode"),
                        "M20 no longer lists the deleted file");
        });
        Assert.That(await bench.Host.ExecuteCodeAsync("M30 \"0:/gcodes/doomed.gcode\""),
                    Does.Contain("delete failed"),
                    "M30 reports a failure to delete (GCodes2.cpp case 30)");
    }

    /// <summary>
    /// M470 creates a directory, M471 renames into it, and M472 deletes it with its contents
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp cases 470, 471 and 472: P names the directory to create or delete, S and T the
    /// old and new names for a rename, D1 allows a rename to overwrite an existing target and R1
    /// makes a delete recursive. None of them writes an object model field, so the file system is
    /// what the assertions read
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M470M471AndM472ManageTheFileSystem()
    {
        await using JobBench bench = await JobControlBench.StartAsync(prepareSd: sd => sd.WriteGCode("moving.gcode", "G4 P1\n"));

        await bench.Host.ExecuteCodeAsync("M470 P\"0:/gcodes/archive\"");
        Assert.That(Directory.Exists(Path.Combine(bench.Host.Sd.Root, "gcodes", "archive")), Is.True,
                    "M470 created the directory (GCodes2.cpp case 470)");

        await bench.Host.ExecuteCodeAsync("M471 S\"0:/gcodes/moving.gcode\" T\"0:/gcodes/archive/moved.gcode\"");
        Assert.Multiple(() =>
        {
            Assert.That(File.Exists(Physical(bench, "gcodes", "moving.gcode")), Is.False,
                        "M471 moved the file away from its old name (GCodes2.cpp case 471)");
            Assert.That(File.Exists(Path.Combine(bench.Host.Sd.Root, "gcodes", "archive", "moved.gcode")), Is.True,
                        "M471 moved the file to its new name (GCodes2.cpp case 471)");
        });

        Assert.That(await bench.Host.ExecuteCodeAsync("M472 P\"0:/gcodes/archive\""),
                    Does.Contain("delete failed"),
                    "M472 without R1 refuses to delete a directory that is not empty (GCodes2.cpp case 472)");

        await bench.Host.ExecuteCodeAsync("M472 P\"0:/gcodes/archive\" R1");
        Assert.That(Directory.Exists(Path.Combine(bench.Host.Sd.Root, "gcodes", "archive")), Is.False,
                    "M472 R1 deleted the directory and its contents (GCodes2.cpp case 472)");
    }

    /// <summary>
    /// M37 simulates a whole file: the machine reports simulating while it runs, the job is marked
    /// as simulated afterwards, and the simulated time is written back into the file
    /// </summary>
    /// <remarks>
    /// GCodes3.cpp <c>SimulateFile</c> selects the file and starts printing it in simulation mode,
    /// which RepRap.cpp <c>GetStatusIndex</c> reports as "simulating" while the print monitor is
    /// printing. GCodes.cpp <c>StopPrint</c> then records the simulated time into the file unless F0
    /// asked it not to (<c>MassStorage::RecordSimulationTime</c>, the "; Simulated print time"
    /// comment FileInfoParser.h names), and the file info parser reads it back as
    /// <c>job.file.simulatedTime</c>
    /// </remarks>
    [Test]
    public async Task M37SimulatesAFile()
    {
        // Slow padding, so the simulation is still running when the model is read
        await using JobBench bench = await JobControlBench.StartAsync(prepareSd: sd =>
            sd.WriteGCode("sim.gcode", "G90\nG1 X10 Y10 F3000\n" + JobControlBench.FillerMoves(pairs: 60, feed: 600)));

        // F0 leaves the file alone, so this is the simulation without the write-back the next test
        // covers on its own
        Task<string> simulation = bench.Host.ExecuteCodeAsync("M37 P\"0:/gcodes/sim.gcode\" F0");
        await bench.Host.WaitForStatusAsync(MachineStatus.Simulating);
        Assert.That(await bench.Host.EvaluateRawAsync("job.file.fileName"), Is.EqualTo("0:/gcodes/sim.gcode"),
                    "the simulated file is the one being printed (PrintMonitor.cpp fileName)");

        await simulation;
        await bench.Host.WaitForStatusAsync(MachineStatus.Idle, timeoutMs: 60_000);

        await Assert.MultipleAsync(async () =>
        {
            Assert.That(await SettledRawAsync(bench.Host, "job.lastFileSimulated", "true"), Is.EqualTo("true"),
                        "the finished job was a simulation (job.lastFileSimulated)");
            Assert.That(await SettledRawAsync(bench.Host, "job.lastFileName", "0:/gcodes/sim.gcode"), Is.EqualTo("0:/gcodes/sim.gcode"),
                        "the simulated file becomes job.lastFileName (PrintMonitor.cpp lastFileName)");
            Assert.That(await SettledNumberAsync(bench.Host, "job.lastDuration"), Is.GreaterThanOrEqualTo(0),
                        "job.lastDuration holds the simulated duration (GCodes.cpp StopPrint, lastDuration)");
        });
    }

    /// <summary>
    /// M37 without F0 writes the simulated time back into the file it simulated, where the file info
    /// parser reads it as job.file.simulatedTime
    /// </summary>
    /// <remarks>
    /// GCodes.cpp <c>StopPrint</c> calls <c>MassStorage::RecordSimulationTime</c> when the
    /// simulation completes normally and F did not say otherwise (GCodes2.cpp case 37), appending
    /// or replacing the "; Simulated print time" comment FileInfoParser.h names, which
    /// FileInfoParser.cpp reads back into <c>printingFileInfo.simulatedTime</c>
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M37WritesTheSimulatedTimeIntoTheFile()
    {
        await using JobBench bench = await JobControlBench.StartAsync(prepareSd: sd =>
            sd.WriteGCode("sim.gcode", "G90\nG1 X10 Y10 F3000\n" + JobControlBench.FillerMoves(pairs: 30, feed: 600)));

        Task<string> simulation = bench.Host.ExecuteCodeAsync("M37 P\"0:/gcodes/sim.gcode\"");
        await bench.Host.WaitForStatusAsync(MachineStatus.Simulating);
        await simulation;
        await bench.Host.WaitForStatusAsync(MachineStatus.Idle, timeoutMs: 20_000);

        Assert.That(await File.ReadAllTextAsync(Physical(bench, "gcodes", "sim.gcode")),
                    Does.Contain("; Simulated print time"),
                    "the simulated time is appended to the file (MassStorage::RecordSimulationTime)");

        await bench.Host.ExecuteCodeAsync("M23 \"0:/gcodes/sim.gcode\"");
        Assert.That(await SettledNumberAsync(bench.Host, "job.file.simulatedTime"), Is.GreaterThanOrEqualTo(0),
                    "the recorded time is read back as job.file.simulatedTime (PrintMonitor.cpp simulatedTime)");
    }

    /// <summary>
    /// M37 with no P parameter reports the simulation mode, and M37 S turns it on and off
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp case 37: with neither P nor S it reports
    /// "Simulation mode: &lt;on|off&gt;, move time: &lt;n&gt; sec, other time: &lt;n&gt; sec", and S
    /// changes the mode through GCodes3.cpp <c>ChangeSimulationMode</c>. The mode alone does not make
    /// the machine report "simulating": RepRap.cpp <c>GetStatusIndex</c> needs a file being printed
    /// as well
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M37ReportsAndChangesTheSimulationMode()
    {
        await using JobBench bench = await JobControlBench.StartAsync();

        Assert.That(await bench.Host.ExecuteCodeAsync("M37"), Does.Contain("Simulation mode: off"),
                    "M37 with no parameters reports the simulation mode (GCodes2.cpp case 37)");

        await bench.Host.ExecuteCodeAsync("M37 S1");
        await Assert.MultipleAsync(async () =>
        {
            Assert.That(await bench.Host.ExecuteCodeAsync("M37"), Does.Contain("Simulation mode: on"),
                        "M37 S1 turns simulation on (GCodes3.cpp ChangeSimulationMode)");
            Assert.That(await bench.Host.EvaluateRawAsync("state.status"), Is.EqualTo("idle"),
                        "simulation mode with no file being printed is still idle (RepRap.cpp GetStatusIndex)");
        });

        await bench.Host.ExecuteCodeAsync("M37 S0");
        Assert.That(await bench.Host.ExecuteCodeAsync("M37"), Does.Contain("Simulation mode: off"),
                    "M37 S0 turns simulation off again (GCodes3.cpp ChangeSimulationMode)");
    }

    /// <summary>M38 reports the CRC32 checksum of a file</summary>
    /// <remarks>
    /// GCodes2.cpp case 38 hashes the file through GCodes3.cpp <c>StartHash</c> and
    /// <c>AdvanceHash</c>, which answer with the CRC32 as eight lower-case hexadecimal digits, and
    /// "Cannot open file: &lt;name&gt;" for a file that is not there
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M38ReportsTheFileChecksum()
    {
        const string content = "M117 known content\n";
        await using JobBench bench = await JobControlBench.StartAsync(prepareSd: sd => sd.WriteGCode("hashed.gcode", content));

        Assert.Multiple(async () =>
        {
            Assert.That((await bench.Host.ExecuteCodeAsync("M38 \"0:/gcodes/hashed.gcode\"")).Trim(),
                        Is.EqualTo("091d63b8"),
                        "M38 reports the CRC32 of the file as eight hex digits (GCodes3.cpp AdvanceHash)");
            Assert.That(await bench.Host.ExecuteCodeAsync("M38 \"0:/gcodes/absent.gcode\""),
                        Does.Contain("Cannot open file"),
                        "M38 reports a file it cannot open (GCodes2.cpp case 38)");
        });
    }

    /// <summary>
    /// M73 gives the job monitor the slicer's own estimate, which is what job.timesLeft.slicer
    /// reports while the file is printing
    /// </summary>
    /// <remarks>
    /// PrintMonitor.cpp <c>ProcessM73</c> stores R as the time left in minutes; the OBJECT_MODEL
    /// entry <c>timesLeft.slicer</c> is <c>EstimateTimeLeft(slicerBased)</c>, which reports the
    /// stored value less the time since it was stored, and null when no file is being printed
    /// </remarks>
    [Test]
    public async Task M73SetsTheSlicerTimeEstimate()
    {
        await using JobBench bench = await JobControlBench.StartAsync(prepareSd: sd =>
            sd.WriteGCode("job.gcode", "G90\nG1 X50 Y50 F3000\n" + JobControlBench.FillerMoves(pairs: 60, feed: 600)));

        await bench.Host.ExecuteCodeAsync("M73 R10");
        string withNoJob = await bench.Host.EvaluateRawAsync("job.timesLeft.slicer");

        await bench.Host.ExecuteCodeAsync("M32 \"0:/gcodes/job.gcode\"");
        await bench.Host.WaitForStatusAsync(MachineStatus.Processing);
        await bench.Host.ExecuteCodeAsync("M73 R10");
        double whilePrinting = await SettledNumberAsync(bench.Host, "job.timesLeft.slicer");

        await bench.Host.ExecuteCodeAsync("M25");
        await bench.Host.WaitForStatusAsync(MachineStatus.Paused);
        await bench.Host.ExecuteCodeAsync("M0");
        await bench.Host.WaitForStatusAsync(MachineStatus.Idle);
        string afterTheJob = await bench.Host.EvaluateRawAsync("job.timesLeft.slicer");

        Assert.Multiple(() =>
        {
            Assert.That(withNoJob, Is.EqualTo("null"),
                        "job.timesLeft.slicer is null while no file is printing (PrintMonitor.cpp EstimateTimeLeft)");
            Assert.That(whilePrinting, Is.GreaterThan(9 * 60).And.LessThanOrEqualTo(10 * 60),
                        "M73 R10 sets job.timesLeft.slicer to ten minutes in seconds (PrintMonitor.cpp ProcessM73)");
            Assert.That(afterTheJob, Is.EqualTo("null"),
                        "the estimate goes back to null once the job has stopped (PrintMonitor.cpp EstimateTimeLeft)");
        });
    }

    /// <summary>
    /// M98 runs a macro and the channel reports it: one stack level deeper, in a macro, with the
    /// macro named as the file it is running. M98 R inside the macro flags it as restartable
    /// </summary>
    /// <remarks>
    /// GCodeBuffer.cpp OBJECT_MODEL table: <c>stackDepth</c> is <c>GetStackDepth</c>, the number of
    /// machine states above the base one; <c>inMacro</c> is <c>machineState->doingFileMacro</c>;
    /// <c>currentFile</c> is <c>machineState->fname</c>, which <c>GCodeBuffer::StartNewFile</c>
    /// assigns the name the macro was started with; and <c>macroRestartable</c> is the flag
    /// GCodes2.cpp case 98 sets from R, reporting it through <c>reprap.InputsUpdated()</c>
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M98RunsAMacroAndReportsTheMacroState()
    {
        await using JobBench bench = await JobControlBench.StartAsync(
            configExtra: "global depthInMacro = 0\nglobal inMacro = false\nglobal macroFile = \"none\"\nglobal restartable = false\n");
        int http = await HttpInputIndexAsync(bench.Host);

        bench.Host.Sd.WriteSys("depth.g", $"""
            set global.macroRuns = global.macroRuns + 1
            set global.depthInMacro = inputs[{http}].stackDepth
            set global.inMacro = inputs[{http}].inMacro
            set global.macroFile = inputs[{http}].currentFile
            M98 R1
            set global.restartable = inputs[{http}].macroRestartable
            """);

        await bench.Host.ExecuteCodeAsync("M98 P\"depth.g\"");

        await Assert.MultipleAsync(async () =>
        {
            Assert.That(await bench.Host.GlobalAsync("macroRuns"), Is.EqualTo(1),
                        "M98 P ran the macro once (GCodes2.cpp case 98)");
            Assert.That(await bench.Host.GlobalAsync("depthInMacro"), Is.EqualTo(1),
                        "inside the macro the channel is one level deep (GCodeBuffer.cpp stackDepth)");
            Assert.That(await bench.Host.EvaluateRawAsync("global.inMacro"), Is.EqualTo("true"),
                        "inside the macro inputs[].inMacro is true");
            Assert.That(await bench.Host.EvaluateRawAsync("global.macroFile"), Does.Contain("depth.g"),
                        "inside the macro inputs[].currentFile names it (GCodeBuffer.cpp currentFile, machineState->fname)");
            Assert.That(await bench.Host.EvaluateRawAsync("global.restartable"), Is.EqualTo("true"),
                        "M98 R1 flags the running macro as restartable (GCodes2.cpp case 98, SetMacroRestartable)");
            Assert.That(await bench.Host.EvaluateAsync($"inputs[{http}].stackDepth"), Is.Zero,
                        "the stack is back to its base once the macro returned (GCodeBuffer.cpp stackDepth)");
            Assert.That(await bench.Host.EvaluateRawAsync($"inputs[{http}].inMacro"), Is.EqualTo("false"),
                        "inputs[].inMacro is false once the macro returned");
        });

        Assert.That(await bench.Host.ExecuteCodeAsync("M98 P\"missing.g\""),
                    Does.Contain("Macro file missing.g not found"),
                    "M98 reports a macro it cannot find (GCodes2.cpp case 98)");
    }

    /// <summary>
    /// M226, M600 and M601 pause the job from within the file, and the object model describes where
    /// it stopped: paused, with the file position of the pause and a pause duration that counts
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp cases 226, 600 and 601 all reach <c>DoSynchronousPause</c>, which records the
    /// restore point and the file position (GCodes.cpp, <c>ms.GetPauseRestorePoint().filePos</c>).
    /// PrintMonitor.cpp reports <c>pauseDuration</c> and keeps <c>duration</c> running while paused,
    /// and RepRap.cpp <c>GetStatusIndex</c> reports "paused"
    /// </remarks>
    [Test]
    public async Task M226PausesWithThePausePointInTheModel()
    {
        await using JobBench bench = await JobControlBench.StartAsync(prepareSd: sd =>
            sd.WriteGCode("job.gcode", """
                G90
                G1 X40 Y40 F3000
                M226
                G1 X10 Y10 F3000
                """));
        long size = new FileInfo(Physical(bench, "gcodes", "job.gcode")).Length;

        await bench.Host.ExecuteCodeAsync("M32 \"0:/gcodes/job.gcode\"");
        await bench.Host.WaitForStatusAsync(MachineStatus.Paused);

        long modelPosition = 0;
        await Assert.MultipleAsync(async () =>
        {
            modelPosition = (long)await NumberAsync(bench.Host, "job.filePosition");
            Assert.That(await bench.Host.EvaluateRawAsync("state.status"), Is.EqualTo("paused"),
                        "M226 pauses the job (RepRap.cpp GetStatusIndex)");
            Assert.That(modelPosition, Is.GreaterThan(0).And.LessThanOrEqualTo(size),
                        "job.filePosition is where the file paused (PrintMonitor.cpp filePosition)");
            Assert.That(await NumberAsync(bench.Host, "job.pauseDuration"), Is.GreaterThanOrEqualTo(0),
                        "job.pauseDuration counts the pause in seconds (PrintMonitor.cpp pauseDuration)");
            Assert.That(await NumberAsync(bench.Host, "job.duration"), Is.GreaterThanOrEqualTo(0),
                        "job.duration keeps running while the job is paused (PrintMonitor.cpp duration)");
        });

        string printStatus = await bench.Host.ExecuteCodeAsync("M27", timeoutMs: ReportTimeoutMs);

        await bench.Host.ExecuteCodeAsync("M24");
        await bench.Host.WaitForStatusAsync(MachineStatus.Idle);

        (long position, long length) = ParsePrintStatus(printStatus);
        Assert.Multiple(async () =>
        {
            Assert.That(await SettledRawAsync(bench.Host, "job.lastFileName", "0:/gcodes/job.gcode"), Is.EqualTo("0:/gcodes/job.gcode"),
                        "the resumed job ran to its end (PrintMonitor.cpp lastFileName)");
            Assert.That(length, Is.EqualTo(size), "M27 still reports the length of the file being printed");
            Assert.That(position, Is.EqualTo(modelPosition),
                        "M27 reports the paused job's file position (GCodes2.cpp case 27)");
        });
    }

    /// <summary>
    /// M600 and M601 pause the same way M226 does, differing only in the reason and the macro, and
    /// all three are refused outside a job file
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp cases 226, 600 and 601: outside a file channel they answer
    /// "use M226/600/601 only within a file being printed". M600 pauses for
    /// <c>PrintPausedReason::filamentChange</c> and M601 for <c>PrintPausedReason::gcode</c>, both
    /// through the same <c>DoSynchronousPause</c>
    /// </remarks>
    [Test]
    public async Task M600AndM601PauseFromWithinTheFile()
    {
        await using JobBench bench = await JobControlBench.StartAsync(prepareSd: sd =>
            sd.WriteGCode("job.gcode", """
                G90
                G1 X30 Y30 F3000
                M600
                G1 X60 Y60 F3000
                M601
                G1 X10 Y10 F3000
                """));

        Assert.Multiple(async () =>
        {
            Assert.That(await bench.Host.ExecuteCodeAsync("M600"),
                        Does.Contain("use M226/600/601 only within a file being printed"),
                        "M600 outside a job file is refused (GCodes2.cpp case 600)");
            Assert.That(await bench.Host.ExecuteCodeAsync("M601"),
                        Does.Contain("use M226/600/601 only within a file being printed"),
                        "M601 outside a job file is refused (GCodes2.cpp case 601)");
        });

        await bench.Host.ExecuteCodeAsync("M32 \"0:/gcodes/job.gcode\"");
        await bench.Host.WaitForStatusAsync(MachineStatus.Paused);
        Assert.That(await NumberAsync(bench.Host, "job.filePosition"), Is.GreaterThan(0),
                    "M600 paused with the file position of the pause point (PrintMonitor.cpp filePosition)");

        await bench.Host.ExecuteCodeAsync("M24");
        await bench.Host.WaitForPauseAtAsync(60.0, 60.0);
        Assert.That(await bench.Host.EvaluateRawAsync("state.status"), Is.EqualTo("paused"),
                    "M601 pauses the job in turn (RepRap.cpp GetStatusIndex)");

        await bench.Host.ExecuteCodeAsync("M24");
        await bench.Host.WaitForStatusAsync(MachineStatus.Idle);
        Assert.That(await SettledRawAsync(bench.Host, "job.lastFileName", "0:/gcodes/job.gcode"), Is.EqualTo("0:/gcodes/job.gcode"),
                    "the job ran to its end through both pauses (PrintMonitor.cpp lastFileName)");
    }

    /// <summary>
    /// M0, M1 and M2 outside a job file cancel a paused print, and are refused when there is nothing
    /// to cancel
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp cases 0, 1 and 2: from a file channel they stop the print as its normal
    /// completion; from anywhere else they cancel a print that is paused, running cancel.g or, if
    /// that is missing, stop.g; and with no paused print they answer
    /// "Pause the print before attempting to cancel it" as an error, running neither macro
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M0M1AndM2OutsideAJobAreRefused()
    {
        await using JobBench bench = await JobControlBench.StartAsync();

        Assert.Multiple(async () =>
        {
            Assert.That(await bench.Host.ExecuteCodeAsync("M0"),
                        Does.Contain("Pause the print before attempting to cancel it"),
                        "M0 with no paused print is refused (GCodes2.cpp case 0)");
            Assert.That(await bench.Host.ExecuteCodeAsync("M1"),
                        Does.Contain("Pause the print before attempting to cancel it"),
                        "M1 with no paused print is refused (GCodes2.cpp case 1)");
            Assert.That(await bench.Host.ExecuteCodeAsync("M2"),
                        Does.Contain("Pause the print before attempting to cancel it"),
                        "M2 with no paused print is refused (GCodes2.cpp case 2)");
        });

        await Assert.MultipleAsync(async () =>
        {
            Assert.That(await bench.Host.GlobalAsync("stopRan"), Is.Zero,
                        "a refused M0 runs no stop.g (GCodes2.cpp case 0)");
            Assert.That(await bench.Host.GlobalAsync("cancelRan"), Is.Zero,
                        "a refused M0 runs no cancel.g (GCodes2.cpp case 0)");
            Assert.That(await bench.Host.EvaluateRawAsync("state.status"), Is.EqualTo("idle"),
                        "the machine stays idle (RepRap.cpp GetStatusIndex)");
        });
    }

    /// <summary>
    /// M2 inside the job file ends the job, exactly as M0 and M1 do from there
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp cases 0, 1 and 2 from a file channel wait for standstill and call
    /// <c>StopPrint(StopPrintReason::normalCompletion)</c>, which runs stop.g and moves the file
    /// name into <c>job.lastFileName</c> (PrintMonitor.cpp)
    /// </remarks>
    [Test]
    public async Task M2InsideTheJobFileEndsTheJob()
    {
        await using JobBench bench = await JobControlBench.StartAsync(prepareSd: sd =>
            sd.WriteGCode("job.gcode", "G90\nG1 X25 Y25 F3000\n" + JobControlBench.FillerMoves(pairs: 30, feed: 600) +
                                       "M2\nG1 X100 Y100 F3000\n"));

        await bench.Host.ExecuteCodeAsync("M32 \"0:/gcodes/job.gcode\"");
        await bench.Host.WaitForStatusAsync(MachineStatus.Processing);
        await bench.Host.WaitForStatusAsync(MachineStatus.Idle);

        await Assert.MultipleAsync(async () =>
        {
            Assert.That(await bench.Host.GlobalAsync("stopRan"), Is.EqualTo(1),
                        "M2 in the file ends the job through stop.g (GCodes.cpp StopPrint)");
            Assert.That(await SettledRawAsync(bench.Host, "job.lastFileName", "0:/gcodes/job.gcode"), Is.EqualTo("0:/gcodes/job.gcode"),
                        "the ended job's file becomes job.lastFileName (PrintMonitor.cpp lastFileName)");
            Assert.That(await bench.Host.EvaluateRawAsync("job.lastFileAborted"), Is.EqualTo("false"),
                        "ending a job with M2 is a normal completion (job.lastFileAborted)");
            Assert.That(await bench.Host.EvaluateAsync("move.axes[0].userPosition"), Is.EqualTo(25.0).Within(0.01),
                        "nothing after the M2 ran (move.axes[0].userPosition)");
        });
    }

    /// <summary>M606 forks the reader, and only from within a job file</summary>
    /// <remarks>
    /// GCodes5.cpp <c>ForkInputReader</c>: outside the File channel it answers
    /// "this command is valid only when running a job from a stored file" as a warning, and with no
    /// S parameter it reports which mode the reader is running in
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M606OutsideAJobFileIsRefused()
    {
        await using JobBench bench = await JobControlBench.StartAsync();

        Assert.Multiple(async () =>
        {
            Assert.That(await bench.Host.ExecuteCodeAsync("M606 S1"),
                        Does.Contain("this command is valid only when running a job from a stored file"),
                        "M606 S1 outside a job file is refused (GCodes5.cpp ForkInputReader)");
            Assert.That(await bench.Host.ExecuteCodeAsync("M606"),
                        Does.Contain("File reader is running in standard mode"),
                        "M606 with no S reports the reader mode (GCodes5.cpp ForkInputReader)");
        });
    }
}
