using System;
using System.IO;
using System.Threading.Tasks;
using NUnit.Framework;
using SystemTests.Host;

namespace SystemTests.Scenarios.Codes;

/// <summary>
/// Kinematics and bed/axis compensation codes against the object model: M556 skew, M557 grid
/// definition, M374/M375/G29 S1/S2/M561 height map file handling, M376 taper, M425 backlash,
/// M593 input shaping, M665/M666 delta parameters, M667 (retired), M669 kinematics selection and
/// M671 leadscrew positions. Expected values come from the RepRapFirmware handlers and object
/// model tables cited on each test. G29 S0 (probing) needs probing hardware and is covered
/// elsewhere
/// </summary>
[TestFixture]
public class KinematicsCompensationCodeTests : SystemTests.Host.BenchFixture
{
    private static string SocketPath() => Path.Combine(Path.GetTempPath(), $"dsf-fake-{Guid.NewGuid():N}.sock");

    /// <summary>
    /// X, Y and Z axes on board 1 (board 0 runs DuetCANMaster and has no drivers), free to move
    /// without homing. M953 comes first: with the bus disabled the configuration's CAN messages
    /// would be answered with BusError, as the real controller answers them. The closing G92 marks
    /// all three axes homed so a test can assert a code un-homes them
    /// </summary>
    private const string XyzConfig = """
        M953
        M569 P1.0 S1
        M569 P1.1 S1
        M569 P1.2 S1
        M584 X1.0 Y1.1 Z1.2
        M92 X80 Y80 Z400
        M906 X800 Y800 Z800
        M201 X500 Y500 Z100
        M203 X6000 Y6000 Z600
        M566 X900 Y900 Z60
        M208 X0:200 Y0:200 Z0:200
        M564 H0 S0
        G92 X0 Y0 Z0
        """;

    /// <summary>
    /// A hand-written 5x5 height map in RepRapFirmware's v2 file format: header comment line,
    /// column label line, grid parameter line, then one row of comma-separated heights per Y step.
    /// Every point reads 0.1, so the mesh deviation statistics are mean 0.1, deviation 0
    /// </summary>
    /// <remarks>
    /// Format from HeightMap::SaveToFile and HeightMap::LoadFromFile in
    /// lib/RepRapFirmware/src/Movement/BedProbing/Grid.cpp; the header comment prefix is
    /// GridDefinition::HeightMapComment and the label line is HeightMapLabelLines[2]
    /// </remarks>
    private const string HeightMapCsv = """
        RepRapFirmware height map file v2 generated by SystemTests, min error 0.100, max error 0.100, mean 0.100, deviation 0.000
        axis0,axis1,min0,max0,min1,max1,radius,spacing0,spacing1,num0,num1
        X,Y,20.00,180.00,20.00,180.00,-1.00,40.00,40.00,5,5
        0.100,0.100,0.100,0.100,0.100
        0.100,0.100,0.100,0.100,0.100
        0.100,0.100,0.100,0.100,0.100
        0.100,0.100,0.100,0.100,0.100
        0.100,0.100,0.100,0.100,0.100
        """;

    private static async Task<DcsTestHost> StartXyzHostAsync(ScriptedCanMaster canMaster, bool withHeightMap = false)
    {
        canMaster.AckCanRequestsWithStandardReplies();
        DcsTestHost host = await DcsTestHost.StartAsync(canMaster, sd =>
        {
            sd.WriteSys("config.g", XyzConfig + DcsTestHost.ConfigDoneMarker);
            if (withHeightMap)
            {
                sd.WriteSys("heightmap.csv", HeightMapCsv);
            }
        });
        await host.WaitForConfigDoneAsync();
        return host;
    }

    /// <summary>
    /// M556 S with axis factors writes the skew tangents as value/S, and P selects whether XY or
    /// YX is compensated. A bare M556 reports the tangents in RRF's exact wording
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp case 556: X sets tangents[0] (tanXY), Y sets tangents[1] (tanYZ), Z sets
    /// tangents[2] (tanXZ), each divided by S (Move::SetAxisCompensation, tan accessors in
    /// Move.h); P &lt;= 0 sets compensateXY true (Move::SetXYCompensation). OM fields from the
    /// move.compensation.skew table in Movement/Move.cpp
    /// </remarks>
    [Test]
    public async Task M556SetsSkewCompensation()
    {
        using ScriptedCanMaster canMaster = new(SocketPath());
        await using DcsTestHost host = await StartXyzHostAsync(canMaster);

        await host.ExecuteCodeAsync("M556 S100 X2 Y1 Z0.5");
        double tanXY = await host.EvaluateAsync("move.compensation.skew.tanXY");
        double tanYZ = await host.EvaluateAsync("move.compensation.skew.tanYZ");
        double tanXZ = await host.EvaluateAsync("move.compensation.skew.tanXZ");
        string compensateXY = await host.EvaluateRawAsync("move.compensation.skew.compensateXY");
        Assert.Multiple(() =>
        {
            Assert.That(tanXY, Is.EqualTo(0.02).Within(1e-5), "M556 X sets move.compensation.skew.tanXY = X/S (RRF GCodes2.cpp case 556, Move::SetAxisCompensation)");
            Assert.That(tanYZ, Is.EqualTo(0.01).Within(1e-5), "M556 Y sets move.compensation.skew.tanYZ = Y/S (RRF tangents[1] is tanYZ)");
            Assert.That(tanXZ, Is.EqualTo(0.005).Within(1e-5), "M556 Z sets move.compensation.skew.tanXZ = Z/S (RRF tangents[2] is tanXZ)");
            Assert.That(compensateXY, Is.EqualTo("true"), "move.compensation.skew.compensateXY defaults to true and M556 without P leaves it");
        });

        await host.ExecuteCodeAsync("M556 P1");
        Assert.That(await host.EvaluateRawAsync("move.compensation.skew.compensateXY"), Is.EqualTo("false"),
                    "M556 P1 clears move.compensation.skew.compensateXY (RRF SetXYCompensation(P <= 0))");

        string report = await host.ExecuteCodeAsync("M556");
        Assert.That(report.Trim(), Is.EqualTo("Axis compensations - YX: 0.02000, YZ: 0.01000, ZX: 0.00500"),
                    "bare M556 reports the tangents in RRF's format (GCodes2.cpp case 556)");
    }

    /// <summary>
    /// M557 with axis ranges and S spacing defines the default probe grid, reported under
    /// move.compensation.probeGrid; the P point-count form derives the spacing from the range
    /// </summary>
    /// <remarks>
    /// GCodes::DefineGrid in GCodes6.cpp writes the default grid; with P the spacing becomes
    /// (max - min)/(P - 1) * 0.9999. OM fields from the GridDefinition tables in
    /// Movement/BedProbing/Grid.cpp (mins, maxs, spacings at 1 decimal place, radius -1 for a
    /// rectangular grid)
    /// </remarks>
    [Test]
    public async Task M557DefinesProbeGrid()
    {
        using ScriptedCanMaster canMaster = new(SocketPath());
        await using DcsTestHost host = await StartXyzHostAsync(canMaster);

        await host.ExecuteCodeAsync("M557 X20:180 Y20:180 S40");
        string axis0 = await host.EvaluateRawAsync("move.compensation.probeGrid.axes[0]");
        string axis1 = await host.EvaluateRawAsync("move.compensation.probeGrid.axes[1]");
        double min0 = await host.EvaluateAsync("move.compensation.probeGrid.mins[0]");
        double max0 = await host.EvaluateAsync("move.compensation.probeGrid.maxs[0]");
        double min1 = await host.EvaluateAsync("move.compensation.probeGrid.mins[1]");
        double max1 = await host.EvaluateAsync("move.compensation.probeGrid.maxs[1]");
        double spacing0 = await host.EvaluateAsync("move.compensation.probeGrid.spacings[0]");
        double spacing1 = await host.EvaluateAsync("move.compensation.probeGrid.spacings[1]");
        double radius = await host.EvaluateAsync("move.compensation.probeGrid.radius");
        Assert.Multiple(() =>
        {
            Assert.That(axis0, Is.EqualTo("X"), "M557 sets move.compensation.probeGrid.axes[0] (RRF GCodes::DefineGrid)");
            Assert.That(axis1, Is.EqualTo("Y"), "M557 sets move.compensation.probeGrid.axes[1]");
            Assert.That(min0, Is.EqualTo(20), "M557 X range sets move.compensation.probeGrid.mins[0]");
            Assert.That(max0, Is.EqualTo(180), "M557 X range sets move.compensation.probeGrid.maxs[0]");
            Assert.That(min1, Is.EqualTo(20), "M557 Y range sets move.compensation.probeGrid.mins[1]");
            Assert.That(max1, Is.EqualTo(180), "M557 Y range sets move.compensation.probeGrid.maxs[1]");
            Assert.That(spacing0, Is.EqualTo(40), "M557 S sets move.compensation.probeGrid.spacings[0]");
            Assert.That(spacing1, Is.EqualTo(40), "M557 S sets move.compensation.probeGrid.spacings[1]");
            Assert.That(radius, Is.EqualTo(-1), "a rectangular M557 grid keeps move.compensation.probeGrid.radius = -1");
        });

        string report = await host.ExecuteCodeAsync("M557");
        Assert.That(report.Trim(), Is.EqualTo("Grid: X20.0:180.0, Y20.0:180.0, radius -1.0, X spacing 40.0, Y spacing 40.0, 25 points"),
                    "bare M557 reports the grid in RRF's format (GridDefinition::PrintParameters)");

        await host.ExecuteCodeAsync("M557 X0:100 Y0:100 P5");
        Assert.That(await host.EvaluateAsync("move.compensation.probeGrid.spacings[0]"), Is.EqualTo(100.0 / 4.0 * 0.9999).Within(1e-3),
                    "M557 P derives move.compensation.probeGrid.spacings[0] as range/(P-1) * 0.9999 (RRF DefineGrid)");
    }

    /// <summary>
    /// M376 H above 1 enables tapered bed compensation and publishes the height; H at or below 1
    /// disables the taper, which reports as a null fade height
    /// </summary>
    /// <remarks>
    /// Move::SetTaperHeight in Movement/Move3.cpp: useTaper = (h &gt; 1.0). The
    /// move.compensation.fadeHeight entry in Movement/Move.cpp reports taperHeight only while
    /// useTaper is set and NaN otherwise, which serialises as null. Report wording from
    /// GCodes2.cpp case 376
    /// </remarks>
    [Test]
    public async Task M376SetsTaperHeight()
    {
        await using JobBench bench = await JobControlBench.StartAsync();

        await bench.Host.ExecuteCodeAsync("M376 H10");
        Assert.That(await bench.Host.EvaluateAsync("move.compensation.fadeHeight"), Is.EqualTo(10).Within(1e-3),
                    "M376 H sets move.compensation.fadeHeight (RRF Move::SetTaperHeight)");
        Assert.That((await bench.Host.ExecuteCodeAsync("M376")).Trim(), Is.EqualTo("Bed compensation taper height is 10.0mm"),
                    "bare M376 reports the taper height in RRF's format (GCodes2.cpp case 376)");

        await bench.Host.ExecuteCodeAsync("M376 H0");
        Assert.That(await bench.Host.EvaluateRawAsync("move.compensation.fadeHeight"), Is.EqualTo("null"),
                    "M376 H0 disables the taper: move.compensation.fadeHeight reports null (RRF useTaper = h > 1.0)");
        Assert.That((await bench.Host.ExecuteCodeAsync("M376")).Trim(), Is.EqualTo("Bed compensation is not tapered"),
                    "bare M376 with the taper disabled reports so (GCodes2.cpp case 376)");
    }

    /// <summary>
    /// M425 axis letters set the per-axis backlash distance and S the correction distance factor
    /// </summary>
    /// <remarks>
    /// Move::ConfigureBacklashCompensation in Movement/Move2.cpp. OM fields:
    /// move.axes[].backlash (3 decimal places) and move.backlashFactor in Movement/Move.cpp
    /// </remarks>
    [Test]
    public async Task M425SetsBacklashCompensation()
    {
        using ScriptedCanMaster canMaster = new(SocketPath());
        await using DcsTestHost host = await StartXyzHostAsync(canMaster);

        await host.ExecuteCodeAsync("M425 X0.5 Y0.25 S5");
        double backlashX = await host.EvaluateAsync("move.axes[0].backlash");
        double backlashY = await host.EvaluateAsync("move.axes[1].backlash");
        double backlashZ = await host.EvaluateAsync("move.axes[2].backlash");
        double factor = await host.EvaluateAsync("move.backlashFactor");
        Assert.Multiple(() =>
        {
            Assert.That(backlashX, Is.EqualTo(0.5).Within(1e-4), "M425 X sets move.axes[0].backlash (RRF Move::ConfigureBacklashCompensation)");
            Assert.That(backlashY, Is.EqualTo(0.25).Within(1e-4), "M425 Y sets move.axes[1].backlash");
            Assert.That(backlashZ, Is.EqualTo(0), "an axis M425 does not name keeps zero backlash");
            Assert.That(factor, Is.EqualTo(5), "M425 S sets move.backlashFactor (RRF backlashCorrectionDistanceFactor)");
        });

        string report = await host.ExecuteCodeAsync("M425");
        Assert.That(report.Trim(), Is.EqualTo("Backlash correction (mm) X: 0.500 Y: 0.250 Z: 0.000, correction distance multiplier 5"),
                    "bare M425 reports the backlash in RRF's format (Move::ConfigureBacklashCompensation)");
    }

    /// <summary>
    /// M593 P"zvd" publishes the shaper type, frequency and damping, and the three ZVD impulses
    /// with their delays; M593 P"none" disables shaping down to a single unit impulse
    /// </summary>
    /// <remarks>
    /// AxisShaper::Configure in Movement/AxisShaper.cpp: for zvd, k = exp(-zeta*pi/sqrt(1-zeta^2)),
    /// j = (1+k)^2, amplitudes 1/j and 2k/j with the last impulse filling to a sum of 1, delays at
    /// half and one damped period. OM fields (type, frequency, damping, amplitudes, delays in
    /// seconds) from the AxisShaper object model tables in the same file
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M593ConfiguresInputShaping()
    {
        await using JobBench bench = await JobControlBench.StartAsync();

        await bench.Host.ExecuteCodeAsync("M593 P\"zvd\" F50 S0.2");

        const double zeta = 0.2;
        const double frequency = 50.0;
        double sqrtOneMinusZetaSquared = Math.Sqrt(1.0 - zeta * zeta);
        double dampedFrequency = frequency * sqrtOneMinusZetaSquared;
        double k = Math.Exp(-zeta * Math.PI / sqrtOneMinusZetaSquared);
        double j = (1.0 + k) * (1.0 + k);

        string type = await bench.Host.EvaluateRawAsync("move.shaping.type");
        double reportedFrequency = await bench.Host.EvaluateAsync("move.shaping.frequency");
        double damping = await bench.Host.EvaluateAsync("move.shaping.damping");
        double amplitudeCount = await bench.Host.EvaluateAsync("#move.shaping.amplitudes");
        double delayCount = await bench.Host.EvaluateAsync("#move.shaping.delays");
        Assert.Multiple(() =>
        {
            Assert.That(type, Is.EqualTo("zvd"), "M593 P sets move.shaping.type (RRF AxisShaper::Configure)");
            Assert.That(reportedFrequency, Is.EqualTo(50).Within(1e-2), "M593 F sets move.shaping.frequency (Hz)");
            Assert.That(damping, Is.EqualTo(0.2).Within(1e-3), "M593 S sets move.shaping.damping (zeta)");
            Assert.That(amplitudeCount, Is.EqualTo(3), "a ZVD shaper has three impulses in move.shaping.amplitudes (RRF numImpulses)");
            Assert.That(delayCount, Is.EqualTo(3), "a ZVD shaper has three entries in move.shaping.delays (RRF numImpulses)");
        });

        // The counts guard the indexed reads: an element read on a shorter array cannot evaluate
        double amplitude0 = await bench.Host.EvaluateAsync("move.shaping.amplitudes[0]");
        double amplitude1 = await bench.Host.EvaluateAsync("move.shaping.amplitudes[1]");
        double amplitude2 = await bench.Host.EvaluateAsync("move.shaping.amplitudes[2]");
        double delay0 = await bench.Host.EvaluateAsync("move.shaping.delays[0]");
        double delay1 = await bench.Host.EvaluateAsync("move.shaping.delays[1]");
        double delay2 = await bench.Host.EvaluateAsync("move.shaping.delays[2]");
        Assert.Multiple(() =>
        {
            Assert.That(amplitude0, Is.EqualTo(1.0 / j).Within(2e-3), "move.shaping.amplitudes[0] = 1/(1+k)^2 for zvd");
            Assert.That(amplitude1, Is.EqualTo(2.0 * k / j).Within(2e-3), "move.shaping.amplitudes[1] = 2k/(1+k)^2 for zvd");
            Assert.That(amplitude2, Is.EqualTo(1.0 - (1.0 / j) - (2.0 * k / j)).Within(2e-3), "move.shaping.amplitudes[2] fills the sum to 1");
            Assert.That(delay0, Is.EqualTo(0), "move.shaping.delays[0] is always 0");
            Assert.That(delay1, Is.EqualTo(0.5 / dampedFrequency).Within(2e-4), "move.shaping.delays[1] is half the damped period, in seconds");
            Assert.That(delay2, Is.EqualTo(1.0 / dampedFrequency).Within(2e-4), "move.shaping.delays[2] is one damped period, in seconds");
        });
    }

    /// <summary>
    /// M593 P"none" disables input shaping: the type reports none, the impulse train collapses to
    /// a single unit impulse, and a bare M593 says shaping is disabled
    /// </summary>
    /// <remarks>
    /// AxisShaper::Configure in Movement/AxisShaper.cpp: type none sets numImpulses = 1, and the
    /// report branch answers "Input shaping is disabled"
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M593NoneDisablesInputShaping()
    {
        await using JobBench bench = await JobControlBench.StartAsync();

        await bench.Host.ExecuteCodeAsync("M593 P\"zvd\" F50 S0.2");
        await bench.Host.ExecuteCodeAsync("M593 P\"none\"");
        Assert.That(await bench.Host.EvaluateRawAsync("move.shaping.type"), Is.EqualTo("none"),
                    "M593 P\"none\" sets move.shaping.type back to none (RRF AxisShaper::Configure)");
        Assert.That((await bench.Host.ExecuteCodeAsync("M593")).Trim(), Is.EqualTo("Input shaping is disabled"),
                    "bare M593 with shaping off reports so (AxisShaper::Configure)");
        Assert.That(await bench.Host.EvaluateAsync("#move.shaping.amplitudes"), Is.EqualTo(1),
                    "a disabled shaper is a single unit impulse (RRF numImpulses = 1)");
    }

    /// <summary>
    /// M665 with L switches to delta kinematics and writes the delta geometry, including the axis
    /// limits derived from B and H, and clears the homed flags
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp case 665 (mode switch when L is seen and the kinematics is not delta, then
    /// SetAllAxesNotHomed) and LinearDeltaKinematics::Configure in
    /// Movement/Kinematics/LinearDeltaKinematics.cpp: B sets X/Y minima to -printRadius and maxima
    /// to printRadius, H sets the Z maximum. OM fields from the LinearDeltaKinematics tables in
    /// the same file, name "delta" from LinearDeltaKinematics::GetName(true)
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M665ConfiguresDeltaGeometry()
    {
        using ScriptedCanMaster canMaster = new(SocketPath());
        await using DcsTestHost host = await StartXyzHostAsync(canMaster);

        Assert.That(await host.EvaluateRawAsync("move.axes[2].homed"), Is.EqualTo("true"), "the config's G92 homed Z");

        await host.ExecuteCodeAsync("M665 L300 R150 B120 H350 X0.5 Y-0.5 Z0.25");
        string name = await host.EvaluateRawAsync("move.kinematics.name");
        double towerCount = await host.EvaluateAsync("#move.kinematics.towers");
        Assert.Multiple(() =>
        {
            Assert.That(name, Is.EqualTo("delta"), "M665 L switches move.kinematics.name to delta (RRF GCodes2.cpp case 665)");
            Assert.That(towerCount, Is.EqualTo(3), "a single L value gives three towers (RRF numTowers)");
        });

        double deltaRadius = await host.EvaluateAsync("move.kinematics.deltaRadius");
        double printRadius = await host.EvaluateAsync("move.kinematics.printRadius");
        double homedHeight = await host.EvaluateAsync("move.kinematics.homedHeight");
        double diagonal0 = await host.EvaluateAsync("move.kinematics.towers[0].diagonal");
        double diagonal2 = await host.EvaluateAsync("move.kinematics.towers[2].diagonal");
        double angle0 = await host.EvaluateAsync("move.kinematics.towers[0].angleCorrection");
        double angle1 = await host.EvaluateAsync("move.kinematics.towers[1].angleCorrection");
        double xMin = await host.EvaluateAsync("move.axes[0].min");
        double xMax = await host.EvaluateAsync("move.axes[0].max");
        double zMax = await host.EvaluateAsync("move.axes[2].max");
        string zHomed = await host.EvaluateRawAsync("move.axes[2].homed");
        Assert.Multiple(() =>
        {
            Assert.That(deltaRadius, Is.EqualTo(150).Within(1e-3), "M665 R sets move.kinematics.deltaRadius");
            Assert.That(printRadius, Is.EqualTo(120).Within(1e-3), "M665 B sets move.kinematics.printRadius");
            Assert.That(homedHeight, Is.EqualTo(350).Within(1e-3), "M665 H sets move.kinematics.homedHeight");
            Assert.That(diagonal0, Is.EqualTo(300).Within(1e-3), "M665 L sets move.kinematics.towers[0].diagonal");
            Assert.That(diagonal2, Is.EqualTo(300).Within(1e-3), "M665 L propagates to move.kinematics.towers[2].diagonal");
            Assert.That(angle0, Is.EqualTo(0.5).Within(1e-3), "M665 X sets move.kinematics.towers[0].angleCorrection");
            Assert.That(angle1, Is.EqualTo(-0.5).Within(1e-3), "M665 Y sets move.kinematics.towers[1].angleCorrection");
            Assert.That(xMin, Is.EqualTo(-120).Within(1e-3), "M665 B sets move.axes[0].min to -printRadius (RRF LinearDeltaKinematics::Configure case 665)");
            Assert.That(xMax, Is.EqualTo(120).Within(1e-3), "M665 B sets move.axes[0].max to printRadius");
            Assert.That(zMax, Is.EqualTo(350).Within(1e-3), "M665 H sets move.axes[2].max to the homed height");
            Assert.That(zHomed, Is.EqualTo("false"), "M665 clears the homed flags (RRF SetAllAxesNotHomed)");
        });
    }

    /// <summary>
    /// M666 on a delta writes the per-tower endstop adjustments and the bed tilt as
    /// percentage/100, and a bare M666 reports them in RRF's wording
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp case 666 and LinearDeltaKinematics::Configure case 666 in
    /// Movement/Kinematics/LinearDeltaKinematics.cpp: X/Y/Z set endstopAdjustments, A and B store
    /// xTilt and yTilt divided by 100. OM fields from the LinearDeltaKinematics tables
    /// </remarks>
    [Test]
    public async Task M666SetsDeltaEndstopAdjustments()
    {
        using ScriptedCanMaster canMaster = new(SocketPath());
        await using DcsTestHost host = await StartXyzHostAsync(canMaster);

        await host.ExecuteCodeAsync("M665 L300 R150 B120 H350");
        Assert.That(await host.EvaluateRawAsync("move.kinematics.name"), Is.EqualTo("delta"),
                    "M665 L switches to delta before M666 (RRF GCodes2.cpp case 665)");

        await host.ExecuteCodeAsync("M666 X0.15 Y-0.2 Z0.05 A1 B-0.5");
        double adjustment0 = await host.EvaluateAsync("move.kinematics.towers[0].endstopAdjustment");
        double adjustment1 = await host.EvaluateAsync("move.kinematics.towers[1].endstopAdjustment");
        double adjustment2 = await host.EvaluateAsync("move.kinematics.towers[2].endstopAdjustment");
        double xTilt = await host.EvaluateAsync("move.kinematics.xTilt");
        double yTilt = await host.EvaluateAsync("move.kinematics.yTilt");
        Assert.Multiple(() =>
        {
            Assert.That(adjustment0, Is.EqualTo(0.15).Within(1e-3), "M666 X sets move.kinematics.towers[0].endstopAdjustment (RRF LinearDeltaKinematics::Configure case 666)");
            Assert.That(adjustment1, Is.EqualTo(-0.2).Within(1e-3), "M666 Y sets move.kinematics.towers[1].endstopAdjustment");
            Assert.That(adjustment2, Is.EqualTo(0.05).Within(1e-3), "M666 Z sets move.kinematics.towers[2].endstopAdjustment");
            Assert.That(xTilt, Is.EqualTo(0.01).Within(1e-4), "M666 A sets move.kinematics.xTilt as A/100");
            Assert.That(yTilt, Is.EqualTo(-0.005).Within(1e-4), "M666 B sets move.kinematics.yTilt as B/100");
        });

        string report = await host.ExecuteCodeAsync("M666");
        Assert.That(report.Trim(), Is.EqualTo("Endstop adjustments X0.15 Y-0.20 Z0.05, tilt X1.00% Y-0.50%"),
                    "bare M666 reports the adjustments in RRF's format (LinearDeltaKinematics::Configure)");
    }

    /// <summary>
    /// M667 is retired: it answers with an error naming M669 and changes nothing, so the
    /// kinematics stays at RRF's cartesian boot default
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp case 667 for the reply; RepRap/Move construction gives a machine that has run
    /// no kinematics code cartesian kinematics, so move.kinematics.name reports "cartesian"
    /// (CoreKinematics::GetName)
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M667RepliesRetiredInFavourOfM669()
    {
        await using JobBench bench = await JobControlBench.StartAsync();

        string reply = await bench.Host.ExecuteCodeAsync("M667 S1");
        Assert.That(reply, Does.Contain("M667 is no longer supported - use M669 instead"),
                    "M667 answers with RRF's retirement error (GCodes2.cpp case 667)");
        Assert.That(await bench.Host.EvaluateRawAsync("move.kinematics.name"), Is.EqualTo("cartesian"),
                    "a refused M667 leaves move.kinematics.name at RRF's cartesian boot default");
    }

    /// <summary>
    /// M669 K1 selects CoreXY: the kinematics name changes, the inverse matrix carries the CoreXY
    /// motor coupling, the forward matrix is its inverse, and the homed flags are cleared
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp case 669 (SetKinematics then SetAllAxesNotHomed on a change) and the
    /// CoreKinematics constructor in Movement/Kinematics/CoreKinematics.cpp: for coreXY the
    /// inverse matrix rows are [1,1,0], [1,-1,0], [0,0,1] and Recalc inverts it into the forward
    /// matrix [0.5,0.5,0], [0.5,-0.5,0], [0,0,1]. OM fields (name, forwardMatrix, inverseMatrix)
    /// from the CoreKinematics object model tables in the same file
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M669SelectsCoreXY()
    {
        using ScriptedCanMaster canMaster = new(SocketPath());
        await using DcsTestHost host = await StartXyzHostAsync(canMaster);

        await host.ExecuteCodeAsync("M669 K1");
        string name = await host.EvaluateRawAsync("move.kinematics.name");
        string xHomed = await host.EvaluateRawAsync("move.axes[0].homed");
        Assert.Multiple(() =>
        {
            Assert.That(name, Is.EqualTo("coreXY"), "M669 K1 sets move.kinematics.name (RRF CoreKinematics::GetName)");
            Assert.That(xHomed, Is.EqualTo("false"), "a kinematics change clears the homed flags (RRF GCodes2.cpp case 669)");
        });

        // The matrices are read from the live model: their rows are plain arrays that the meta
        // expression evaluator cannot index into, and the values are what matters here
        float inverse00, inverse01, inverse10, inverse11, inverse22;
        float forward00, forward01, forward10, forward11, forward22;
        using (await host.Model.AccessReadOnlyAsync(System.Threading.CancellationToken.None))
        {
            DuetAPI.ObjectModel.CoreKinematics? core = host.Model.Move.Kinematics as DuetAPI.ObjectModel.CoreKinematics;
            Assert.That(core, Is.Not.Null, "M669 K1 publishes CoreKinematics under move.kinematics");
            inverse00 = core!.InverseMatrix[0][0];
            inverse01 = core.InverseMatrix[0][1];
            inverse10 = core.InverseMatrix[1][0];
            inverse11 = core.InverseMatrix[1][1];
            inverse22 = core.InverseMatrix[2][2];
            forward00 = core.ForwardMatrix[0][0];
            forward01 = core.ForwardMatrix[0][1];
            forward10 = core.ForwardMatrix[1][0];
            forward11 = core.ForwardMatrix[1][1];
            forward22 = core.ForwardMatrix[2][2];
        }
        Assert.Multiple(() =>
        {
            Assert.That(inverse00, Is.EqualTo(1).Within(1e-3), "coreXY move.kinematics.inverseMatrix[0][0] = 1");
            Assert.That(inverse01, Is.EqualTo(1).Within(1e-3), "coreXY move.kinematics.inverseMatrix[0][1] = 1");
            Assert.That(inverse10, Is.EqualTo(1).Within(1e-3), "coreXY move.kinematics.inverseMatrix[1][0] = 1");
            Assert.That(inverse11, Is.EqualTo(-1).Within(1e-3), "coreXY move.kinematics.inverseMatrix[1][1] = -1");
            Assert.That(inverse22, Is.EqualTo(1).Within(1e-3), "coreXY leaves Z uncoupled: inverseMatrix[2][2] = 1");
            Assert.That(forward00, Is.EqualTo(0.5).Within(1e-3), "the forward matrix is the inverse: forwardMatrix[0][0] = 0.5");
            Assert.That(forward01, Is.EqualTo(0.5).Within(1e-3), "forwardMatrix[0][1] = 0.5");
            Assert.That(forward10, Is.EqualTo(0.5).Within(1e-3), "forwardMatrix[1][0] = 0.5");
            Assert.That(forward11, Is.EqualTo(-0.5).Within(1e-3), "forwardMatrix[1][1] = -0.5");
            Assert.That(forward22, Is.EqualTo(1).Within(1e-3), "forwardMatrix[2][2] = 1");
        });

        double inverseRows = await host.EvaluateAsync("#move.kinematics.inverseMatrix");
        double forwardRows = await host.EvaluateAsync("#move.kinematics.forwardMatrix");
        Assert.Multiple(() =>
        {
            Assert.That(inverseRows, Is.EqualTo(3), "move.kinematics.inverseMatrix has one row per axis (RRF CoreKinematics array table, count reprap.GetGCodes().GetTotalAxes())");
            Assert.That(forwardRows, Is.EqualTo(3), "move.kinematics.forwardMatrix has one row per visible axis");
        });
    }

    /// <summary>
    /// M671 on cartesian kinematics stores the Z leadscrew coordinates and correction parameters
    /// under move.kinematics.tiltCorrection, and configuring positions zeroes the last corrections
    /// </summary>
    /// <remarks>
    /// ZLeadscrewKinematics::Configure in Movement/Kinematics/ZLeadscrewKinematics.cpp: X/Y arrays
    /// set the screw positions, S the maximum correction, P the screw pitch, F the correction
    /// factor. OM fields from the ZLeadscrewKinematics tables in the same file. M669 K0 first, so
    /// the test does not depend on the boot default kinematics
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M671SetsLeadscrewPositions()
    {
        using ScriptedCanMaster canMaster = new(SocketPath());
        await using DcsTestHost host = await StartXyzHostAsync(canMaster);

        await host.ExecuteCodeAsync("M669 K0");
        string configureReply = await host.ExecuteCodeAsync("M671 X10:190 Y5:195 S2.5 P0.7 F1.2");
        Assert.That(configureReply.Trim(), Is.Empty,
                    "cartesian kinematics accepts M671 silently (RRF ZLeadscrewKinematics::Configure)");

        double screwX0 = await host.EvaluateAsync("move.kinematics.tiltCorrection.screwX[0]");
        double screwX1 = await host.EvaluateAsync("move.kinematics.tiltCorrection.screwX[1]");
        double screwY0 = await host.EvaluateAsync("move.kinematics.tiltCorrection.screwY[0]");
        double screwY1 = await host.EvaluateAsync("move.kinematics.tiltCorrection.screwY[1]");
        double maxCorrection = await host.EvaluateAsync("move.kinematics.tiltCorrection.maxCorrection");
        double screwPitch = await host.EvaluateAsync("move.kinematics.tiltCorrection.screwPitch");
        double correctionFactor = await host.EvaluateAsync("move.kinematics.tiltCorrection.correctionFactor");
        Assert.Multiple(() =>
        {
            Assert.That(screwX0, Is.EqualTo(10).Within(1e-3), "M671 X sets move.kinematics.tiltCorrection.screwX[0] (RRF ZLeadscrewKinematics::Configure)");
            Assert.That(screwX1, Is.EqualTo(190).Within(1e-3), "M671 X sets move.kinematics.tiltCorrection.screwX[1]");
            Assert.That(screwY0, Is.EqualTo(5).Within(1e-3), "M671 Y sets move.kinematics.tiltCorrection.screwY[0]");
            Assert.That(screwY1, Is.EqualTo(195).Within(1e-3), "M671 Y sets move.kinematics.tiltCorrection.screwY[1]");
            Assert.That(maxCorrection, Is.EqualTo(2.5).Within(1e-3), "M671 S sets move.kinematics.tiltCorrection.maxCorrection");
            Assert.That(screwPitch, Is.EqualTo(0.7).Within(1e-3), "M671 P sets move.kinematics.tiltCorrection.screwPitch");
            Assert.That(correctionFactor, Is.EqualTo(1.2).Within(1e-3), "M671 F sets move.kinematics.tiltCorrection.correctionFactor");
        });

        // The count guards the element read: an element read on a shorter array cannot evaluate
        Assert.That(await host.EvaluateAsync("#move.kinematics.tiltCorrection.lastCorrections"), Is.EqualTo(2),
                    "M671 sizes move.kinematics.tiltCorrection.lastCorrections to the leadscrew count (RRF numLeadscrews)");
        Assert.That(await host.EvaluateAsync("move.kinematics.tiltCorrection.lastCorrections[0]"), Is.EqualTo(0),
                    "configuring positions zeroes move.kinematics.tiltCorrection.lastCorrections");

        string report = await host.ExecuteCodeAsync("M671");
        Assert.That(report.Trim(), Is.EqualTo("Z leadscrew coordinates (10.0,5.0) (190.0,195.0), factor 1.20, maximum correction 2.50mm, manual adjusting screw pitch 0.70mm"),
                    "bare M671 reports the leadscrews in RRF's format (ZLeadscrewKinematics::Configure)");
    }

    /// <summary>
    /// G29 S1 loads sys/heightmap.csv and enables mesh compensation. The map is a hand-written v2
    /// file, so no probing hardware is involved
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp case 29 dispatches S1 to GCodes::LoadHeightMap (GCodes6.cpp), which loads
    /// sys/heightmap.csv by default and activates the map: move.compensation.type reports "mesh"
    /// (Move::GetCompensationTypeString), .file the loaded file, .liveGrid the file's grid and
    /// .meshDeviation the map statistics (Move::LoadHeightMapFromFile, OM tables in
    /// Movement/Move.cpp)
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task G29S1LoadsHeightMap()
    {
        using ScriptedCanMaster canMaster = new(SocketPath());
        await using DcsTestHost host = await StartXyzHostAsync(canMaster, withHeightMap: true);

        string loadReply = await host.ExecuteCodeAsync("G29 S1");
        Assert.That(loadReply.Trim(), Is.Empty, "G29 S1 loads the map silently with no probe configured (RRF GCodes::LoadHeightMap)");
        Assert.That(await host.EvaluateRawAsync("move.compensation.type"), Is.EqualTo("mesh"),
                    "G29 S1 sets move.compensation.type to mesh (RRF Move::GetCompensationTypeString)");
        Assert.That(await host.EvaluateRawAsync("move.compensation.file"), Does.EndWith("heightmap.csv"),
                    "G29 S1 sets move.compensation.file to the loaded map");

        double liveMin0 = await host.EvaluateAsync("move.compensation.liveGrid.mins[0]");
        double liveMax0 = await host.EvaluateAsync("move.compensation.liveGrid.maxs[0]");
        double liveSpacing0 = await host.EvaluateAsync("move.compensation.liveGrid.spacings[0]");
        double meshMean = await host.EvaluateAsync("move.compensation.meshDeviation.mean");
        double meshDeviation = await host.EvaluateAsync("move.compensation.meshDeviation.deviation");
        Assert.Multiple(() =>
        {
            Assert.That(liveMin0, Is.EqualTo(20).Within(1e-3), "move.compensation.liveGrid.mins[0] comes from the file's grid");
            Assert.That(liveMax0, Is.EqualTo(180).Within(1e-3), "move.compensation.liveGrid.maxs[0] comes from the file's grid");
            Assert.That(liveSpacing0, Is.EqualTo(40).Within(1e-3), "move.compensation.liveGrid.spacings[0] comes from the file's grid");
            Assert.That(meshMean, Is.EqualTo(0.1).Within(1e-3), "move.compensation.meshDeviation.mean is the map's mean height (RRF Move::LoadHeightMapFromFile)");
            Assert.That(meshDeviation, Is.EqualTo(0).Within(1e-3), "a uniform map has zero move.compensation.meshDeviation.deviation");
        });
    }

    /// <summary>
    /// G29 S2 disables mesh compensation and drops the loaded map. The map is loaded through M375
    /// first so the clearing is observable independently of the G29 S1 path
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp case 29 dispatches S2 to GCodes::ClearBedMapping (GCodes6.cpp), after which
    /// move.compensation.type is "none" and .file null (usingMesh cleared, OM tables in
    /// Movement/Move.cpp)
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task G29S2ClearsLoadedHeightMap()
    {
        using ScriptedCanMaster canMaster = new(SocketPath());
        await using DcsTestHost host = await StartXyzHostAsync(canMaster, withHeightMap: true);

        await host.ExecuteCodeAsync("M375");
        Assert.That(await host.EvaluateRawAsync("move.compensation.type"), Is.EqualTo("mesh"),
                    "M375 loads the map before G29 S2 clears it (RRF GCodes::LoadHeightMap)");

        await host.ExecuteCodeAsync("G29 S2");
        Assert.That(await host.EvaluateRawAsync("move.compensation.type"), Is.EqualTo("none"),
                    "G29 S2 sets move.compensation.type back to none (RRF GCodes::ClearBedMapping)");
        Assert.That(await host.EvaluateRawAsync("move.compensation.file"), Is.EqualTo("null"),
                    "G29 S2 clears move.compensation.file");
    }

    /// <summary>
    /// M375 loads sys/heightmap.csv and enables mesh compensation, exactly as G29 S1 does
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp case 375 calls GCodes::LoadHeightMap in GCodes6.cpp; OM effects as for G29 S1
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M375LoadsHeightMap()
    {
        using ScriptedCanMaster canMaster = new(SocketPath());
        await using DcsTestHost host = await StartXyzHostAsync(canMaster, withHeightMap: true);

        string loadReply = await host.ExecuteCodeAsync("M375");
        Assert.That(await host.EvaluateRawAsync("move.compensation.type"), Is.EqualTo("mesh"),
                    "M375 sets move.compensation.type to mesh (RRF Move::GetCompensationTypeString)");
        Assert.That(await host.EvaluateRawAsync("move.compensation.file"), Does.EndWith("heightmap.csv"),
                    "M375 sets move.compensation.file to the loaded map");
        Assert.That(await host.EvaluateAsync("move.compensation.liveGrid.spacings[0]"), Is.EqualTo(40).Within(1e-3),
                    "move.compensation.liveGrid.spacings[0] comes from the file's grid");
        Assert.That(loadReply.Trim(), Is.Empty, "M375 loads the map silently with no probe configured (RRF GCodes::LoadHeightMap)");
    }

    /// <summary>
    /// M374 saves the loaded height map to a named file in sys, in RRF's v2 format. M374 after a
    /// real probing run needs probe hardware, so the map under test is loaded from a file first
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp case 374 calls GCodes::SaveHeightMap; reply wording from
    /// GCodes::TrySaveHeightMap in GCodes6.cpp ("height map saved to file ..."), file format from
    /// HeightMap::SaveToFile and GridDefinition::WriteHeadingAndParameters in
    /// Movement/BedProbing/Grid.cpp
    /// </remarks>
    [Category("KnownGap")]
    [Test]
    public async Task M374SavesLoadedHeightMap()
    {
        using ScriptedCanMaster canMaster = new(SocketPath());
        await using DcsTestHost host = await StartXyzHostAsync(canMaster, withHeightMap: true);

        await host.ExecuteCodeAsync("M375");
        Assert.That(await host.EvaluateRawAsync("move.compensation.type"), Is.EqualTo("mesh"),
                    "M375 loads the map M374 saves (RRF GCodes::LoadHeightMap)");

        string saveReply = await host.ExecuteCodeAsync("M374 P\"saved-map.csv\"");
        string savedPath = Path.Combine(host.Sd.Root, "sys", "saved-map.csv");
        Assert.That(File.Exists(savedPath), Is.True, "M374 P writes the map to 0:/sys (RRF GCodes::SaveHeightMap)");
        string[] savedLines = await File.ReadAllLinesAsync(savedPath);
        Assert.Multiple(() =>
        {
            Assert.That(savedLines[0], Does.StartWith("RepRapFirmware height map file v2"),
                        "a saved map starts with RRF's v2 header comment (HeightMap::SaveToFile)");
            Assert.That(savedLines[1], Is.EqualTo("axis0,axis1,min0,max0,min1,max1,radius,spacing0,spacing1,num0,num1"),
                        "a saved map carries RRF's v2 label line (GridDefinition::WriteHeadingAndParameters)");
            Assert.That(savedLines[2], Does.StartWith("X,Y,20.00,180.00,20.00,180.00,"),
                        "the saved grid parameters match the loaded grid");
            Assert.That(saveReply, Does.Contain("height map saved to file"),
                        "M374 reports the save in RRF's wording (GCodes::TrySaveHeightMap)");
        });
    }

    /// <summary>
    /// M561 disables bed compensation: the loaded map is dropped, the compensation type reports
    /// none and the file is cleared
    /// </summary>
    /// <remarks>
    /// GCodes2.cpp case 561 calls GCodes::ClearBedMapping in GCodes6.cpp; usingMesh is cleared so
    /// move.compensation.type reports "none" and .file null (OM tables in Movement/Move.cpp)
    /// </remarks>
    [Test]
    public async Task M561ClearsBedCompensation()
    {
        using ScriptedCanMaster canMaster = new(SocketPath());
        await using DcsTestHost host = await StartXyzHostAsync(canMaster, withHeightMap: true);

        await host.ExecuteCodeAsync("M375");
        Assert.That(await host.EvaluateRawAsync("move.compensation.type"), Is.EqualTo("mesh"),
                    "M375 loads the map M561 clears (RRF GCodes::LoadHeightMap)");

        string clearReply = await host.ExecuteCodeAsync("M561");
        Assert.That(clearReply.Trim(), Is.Empty, "M561 answers silently (RRF GCodes2.cpp case 561)");
        Assert.That(await host.EvaluateRawAsync("move.compensation.type"), Is.EqualTo("none"),
                    "M561 sets move.compensation.type back to none (RRF GCodes::ClearBedMapping)");
        Assert.That(await host.EvaluateRawAsync("move.compensation.file"), Is.EqualTo("null"),
                    "M561 clears move.compensation.file");
    }
}
