using DuetAPI.Commands;
using DuetAPI.ObjectModel;
using System;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace DuetControlServer.Files.ImageProcessing
{
    /// <summary>
    /// Functions for parsing thumbnails generated by Prusa Slicer
    /// </summary>
    public static class PrusaSlicerImageParser
    {
        /// <summary>
        /// Extract thumbnails generated by Prusa Slicer from a file
        /// </summary>
        /// <param name="reader">Stream reader to read from</param>
        /// <param name="codeParserBuffer">Parser buffer</param>
        /// <param name="parsedFileInfo">File information</param>
        /// <param name="code">Code to reuse while parsing</param>
        /// <returns>Asynchronous task</returns>
        public static async Task ProcessAsync(StreamReader reader, CodeParserBuffer codeParserBuffer, ParsedFileInfo parsedFileInfo, Code code)
        {
            StringBuilder encodedImage = new();

            //Read the image header info that is currently in the code
            string[] thumbnailTokens = code.Comment.Trim().Split(' ');

            //Stop processing since the thumbnail may be corrupt.
            if (thumbnailTokens.Length != 4)
            {
                throw new ImageProcessingException();
            }
            string[] dimensions = thumbnailTokens[2].Split('x');
            if (dimensions.Length != 2)
            {
                throw new ImageProcessingException();
            }

            ParsedThumbnail thumbnail = new()
            {
                Width = int.Parse(dimensions[0]),
                Height = int.Parse(dimensions[1])
            };

            int encodedLength = int.Parse(thumbnailTokens[3]);
            encodedImage.Clear();
            code.Reset();


            //Keep reading the data from the file
            while (codeParserBuffer.GetPosition(reader) < reader.BaseStream.Length)
            {
                Program.CancellationToken.ThrowIfCancellationRequested();
                if (!await Code.ParseAsync(reader, code, codeParserBuffer))
                {
                    continue;
                }



                if (code.Type != CodeType.Comment)
                {
                    return;
                }

                if (string.IsNullOrEmpty(code.Comment))
                {
                    code.Reset();
                    continue;
                }

                if (code.Comment.Contains("thumbnail begin", StringComparison.InvariantCultureIgnoreCase))
                {
                    //Exit if we find another start tag before ending the previous image
                    throw new ImageProcessingException();
                }
                else if (code.Comment.Contains("thumbnail end", StringComparison.InvariantCultureIgnoreCase))
                {
                    if (encodedImage.Length == encodedLength)
                    {
                        thumbnail.EncodedImage = "data:image/png;base64," + encodedImage.ToString();
                        parsedFileInfo.Thumbnails.Add(thumbnail);
                        return;
                    }
                }
                else
                {
                    encodedImage.Append(code.Comment.Trim());
                }
                code.Reset();
            }
        }
    }
}

