#!/bin/sh

# Stop DPS instances
if [ -d /run/systemd/system ]; then
    if systemctl -q is-active duetpluginservice; then
        systemctl -q --no-ask-password stop duetpluginservice || true
    fi

    if systemctl -q is-active duetpluginservice-root; then
        systemctl -q --no-ask-password stop duetpluginservice-root || true
    fi
fi

