#!/bin/sh

# Stop DPS instances
if [ -d /run/systemd/system ]; then
    if systemctl -q is-active duetpluginservice; then
        deb-systemd-invoke stop duetpluginservice >/dev/null || true
    fi

    if systemctl -q is-active duetpluginservice-root; then
        deb-systemd-invoke stop duetpluginservice-root >/dev/null || true
    fi
fi

