#!/bin/sh

# Stop DPS instances
if (systemctl -q is-active duetpluginservice); then
    systemctl -q --no-ask-password stop duetpluginservice
fi

if (systemctl -q is-active duetpluginservice-root); then
    systemctl -q --no-ask-password stop duetpluginservice-root
fi

