name: Build and and deploy DSF packages

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Deployment target"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - unstable
        - stable

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install NodeJS environment (TODO: Update to 16 when v3.5 is out)
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14

      # Install .NET environment
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6

      # Install required tools
      - name: Install dependencies
        run: sudo apt install -y dpkg-sig libxml2-utils
      
      # Import GPG key for package signing
      - name: Configure GPG key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      # Build DSF
      - name: Build DSF packages
        run: |
          cd pkg
          ./build.sh --signing-key=C406404B2459FE0B1C6CC19D3738126EDA91C86B --target-arch=armhf --dest-dir=./out
          ./build.sh --signing-key=C406404B2459FE0B1C6CC19D3738126EDA91C86B --target-arch=arm64 --dest-dir=./out

      # Upload armhf packages to pkg.duet3d.com
      - name: Upload package files
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: pkg.duet3d.com
          port: 22
          username: ${{ secrets.PKG_SSH_USER }}
          password: ${{ secrets.PKG_SSH_PASS }}
          privateKey: ${{ secrets.PKG_SSH_KEY }}
          localPath: ./pkg/out
          remotePath: /var/www/pkg/dists/${{ inputs.target }}/armv7

      # Refresh package lists if the dev target is selected
      - name: Refresh package lists
        if: inputs.target == "dev"
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: pkg.duet3d.com
          username: ${{ secrets.PKG_SSH_USER }}
          key: ${{ secrets.PKG_SSH_KEY }}
          script: update-pkg-feed dev
